### ISSUE TITLE
Include path with placeholders in path-parameters.adoc

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-restdocs#103]
Currently path-parameters.adoc contains a table of parameters, but since their position within the URL has meaning (unlike query parameters), it would be useful to have the URL unmodified in the output as a reference.

**Comment by wilkinsona** [comment]
Any opinion on where the unmodified URL should go? A few options to get the ball rolling:

 - Table title in path-parameters.adoc
 - Somewhere else in path-parameters.adoc
 - In a separate snippet

**Comment by mminella** [comment]
I started trying to put together a PR for this (assuming I could crank it out quickly).  I had it working as an additional attribute in the path-parameters.adoc (just a source snip above the table) but writing a clean test for it tripped me up a bit.

**Comment by wilkinsona** [comment]
Thanks for taking a shot at it. I'm not surprised about the test – after the move to using a template engine, I think the tests might be a bit too clever for their own good

**Comment by wilkinsona** [comment]
There's an interesting suggestion [here](https://github.com/spring-projects/spring-restdocs/issues/86#issuecomment-122049672) that I'd missed previously. It makes a good case for producing a separate snippet with the path. It doesn't have to be either/or, though.

**Comment by wilkinsona** [comment]
A brief discussion with @olivergierke moved me away from providing a separate snippet. The request's path or it's HTTP method and path is of limited use as there's no guarantee that it will uniquely identify a particular RESTful resource. Instead, the path parameters snippet has been enhanced to include the path as the title of the table.
