### ISSUE TITLE
Reduce coupling with MockMvc

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#108]
Spring REST Docs is currently fairly heavily coupled to Spring Test's MockMvc. For example, every snippet implementation relies on `MvcResult`. This is proving problematic.

The main area where it's causing trouble is in the support for modifying a result prior to it being documented. The current code makes use of CGLib proxies and method interceptors to workaround some inflexibility in MvcResult and the mock request and response types. I'd like to move to a new abstraction that's specifically designed for Spring REST Docs' requirements. It should be flexible enough to make it easy to modify a result before it's documented, while also only exposing what's necessary for RESTful API documentation.

**Comment by wilkinsona** [comment]
Work in progress is [available in this branch](https://github.com/spring-projects/spring-restdocs/tree/gh-108

/cc @johanhaleby @sg-ad

**Comment by johanhaleby** [comment]
@wilkinsona Great news. Let me know if I can be of assistance.

**Comment by johanhaleby** [comment]
@wilkinsona Could you point me in a direction where I should start looking if I want to integrate this with REST Assured?

**Comment by wilkinsona** [comment]
@johanhaleby I've just reworked things so that all of the MockMvc stuff is now in a separate module, spring-restdocs-mockmvc. Having a look at what that's doing is, hopefully, a reasonable starting point for you. My hope is to start working on a spring-rest docs-restassured module next week as I'd like to verify that the new abstraction holds up. Your help with that would be much appreciated.

**Comment by sg-ad** [comment]
@wilkinsona and @johanhaleby I'd like to contribute as well.  Because my work was done on company time, I've been tangled up in a little bit of legal red tape that was exacerbated by the summer holidays.  It should get resolved this week and I can then show you were I got.  I'll take a look at the new changes that were made to see if it fits at all.

**Comment by johanhaleby** [comment]
@wilkinsona Just drop me a comment or mail and I'll try to help out
@sg-ad Great that you want to help out as well.
