### ISSUE TITLE
Support binary based API response such as a file download REST API

### ISSUE THREAD

**Issue by steviemo** [spring-projects/spring-restdocs#110]
Currently restdocs generates a http-response.doc for such an API as follows:

[source,http]
----
HTTP/1.1 200 OK
Content-Type: image/tiff
Content-Length: 46371
Content-Disposition: attachment; filename="example.tif"

II*�||��7���(1�ImagePrep     ��Pˠ�O�OX����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
----

This cannot be included in an asciidoc:

sciidoctor: WARNING: et-export-example/http-response.adoc: line 1: include file not readable: /path/to/http-response.adoc

**Comment by steviemo** [comment]
Implement your own ContentModifyingReponsePostProcessor to strip the binary content from the respone.

**Comment by wilkinsona** [comment]
Good idea. Note that the API has changed in the latest snapshots, hopefully for the better. Feedback most welcome.

**Comment by steviemo** [comment]
Did this make it in? I seen "Support for documenting multipart requests" in the spring blog post but no mention in the reference docs for RC1. With RC1 I switched from implementing my own ContentModifyingReponsePostProcessor to implementing my own OperationResponsePreprocessor

**Comment by wilkinsona** [comment]
No changes have been made for this issue. The blog post is talking about requests. This issue is about responses.

You're taking the right approach using a preprocessor. You might want to implement a custom `ContentModifier` and construct an instance of the existing content modifying preprocessor with it.

**Comment by steviemo** [comment]
Cheers.
I did notice this ContentModifiier interface but it's not public so I'm unable to implement a custom class- maybe a bug?

**Comment by wilkinsona** [comment]
Indeed it is. I've opened https://github.com/spring-projects/spring-restdocs/issues/121 to make t public
