### ISSUE TITLE
Hide Content-Length from CURL request examples

### ISSUE THREAD

**Issue by orfjackal** [spring-projects/spring-restdocs#111]
Here is an example of one curl-request.adoc generated by REST Docs 1.0.0.M1. Notice that the curl command explicitly sets the `Content-Length` header. This is redundant, because curl will calculate it automatically based on the `-d` content. And if a user wants to try the example himself, he will need to remove the `Content-Length` anyways in order to try variations of the command. It would be better for REST Docs to not show `-H 'Content-Length: ...'` in the curl examples.

```
$ curl 'http://localhost:8080/api/v1/facilities/1/utilization' -i -X PUT -H 'Authorization: Bearer P|1|1441708743453|i4BBmYdzAGxAAILSd9L62pn82PJKKDnfwHfjDNbD6l0' -H 'Content-Type: application/json' -H 'Content-Length: 138' -d '[ {
  "capacityType" : "CAR",
  "usage" : "HSL_TRAVEL_CARD",
  "timestamp" : "2015-09-08T13:39:03.454+03:00",
  "spacesAvailable" : 30
} ]'
```

**Comment by wilkinsona** [comment]
The curl request snippet will only include a `Content-Length` header if you've set one in the test that generates it. Is there something about your test that means that you have to set the header even though you don't want it to appear in the snippet?

**Comment by wilkinsona** [comment]
It's been a couple of weeks now. Closing due to lack of requested information. Please comment with the requested information if you'd like this to be reopened.

**Comment by orfjackal** [comment]
Here is an example project for reproducing this: https://github.com/orfjackal/spring-restdocs-issue-111

[The test in question](https://github.com/orfjackal/spring-restdocs-issue-111/blob/master/src/test/java/com/example/ExampleDocumentation.java#L48-L54) is like this:

    @Test
    public void post_example() throws Exception {
        mockMvc.perform(post("/hello").content("World"))
                .andExpect(status().isOk())
                .andExpect(content().string("Hello World"))
                .andDo(document("post-example"));
    }

It doesn't set the content-length explicitly, but anyways the generated curl snippet includes it:

```
$ cat target/generated-snippets/post-example/curl-request.adoc

[source,bash]
----
$ curl 'http://localhost:8080/hello' -i -X POST -H 'Content-Length: 5' -d 'World'
----
```

I'm suspecting that the cause is that `org.springframework.mock.web.MockHttpServletRequest#getContentLength` will always return a number when content is non-null:

```
	public int getContentLength() {
		return (this.content != null ? this.content.length : -1);
	}
```
