### ISSUE TITLE
Make 1.0.0.RC1 available at http://docs.spring.io/spring-restdocs/docs/

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-restdocs#114]
Currently the 1.0.0.RC1 release states the documentation is available at http://docs.spring.io/autorepo/docs/spring-restdocs/1.0.0.RC1/reference/html5/#getting-started which seems to leak the details of Springs implementation of publishing the documentation. Instead it would be nice to ensure the docs are available at http://docs.spring.io/spring-restdocs/docs/

Details on deploying can be found at on the [Spring Framework wiki](https://github.com/spring-projects/spring-framework/wiki/autorepo-version-updating)

**NOTE** The links on http://projects.spring.io/spring-restdocs/ are dated too

**Comment by wilkinsona** [comment]
Thanks, Rob. That's a deliberate, and temporary, situation while I'm waiting for Trevor to update some symlinks.

**Comment by wilkinsona** [comment]
Everything should be available from http://docs.spring.io/spring-restdocs/docs now. The blog post and project page have been updated accordingly.
