### ISSUE TITLE
Documenting Security

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-restdocs#115]
It would be nice to demonstrate how Spring REST Docs should be used to document security. This is unique because security is a cross cutting concern.

Here is an outline of what I think would be expected:

* Authenticating
* Authentication Required
* Access Denied

# Authenticating

This documents how a user should authenticate. Documentation should be clear how to authenticate to the APIs and then how to use the result of that authentication (if different) to access the APIs.

A few examples of authentication, that might be of interest:

* x-auth-token using Spring Session. For instructions refer to the [HTTP Session guide](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/rest.html)
* HTTP Basic. It may be of interest that Spring Security 4+ provides an [httpBasic RequestPostProcessor](http://docs.spring.io/spring-security/site/docs/4.0.x/reference/htmlsingle/#testing-http-basic-authentication)
* OAuth

# Authentication Required

This occurs when the user has not provided any credentials, but authentication is required. 

How does one document access to resources that require authentication? How does one document what happens when a protected resource without authentication responds. For example, when requesting a protected resource when un authenticated HTTP Basic will respond with:

```http
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="WallyWorld"
```

However, an OAuth protected endpoint would respond with:

```http
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer realm="example"
```

Attempt to access an OAuth protected endpoint when the token is expires would result in:

```http
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer realm="example",error="invalid_token",error_description="The access token expired"
```

# Access Denied

This occurs when authentication is provided, but is not authorized to access the resource.

Access Denied with HTTP Basic might result in:

```http
HTTP/1.1 403 FORBIDDEN
```

Access denied with OAuth might result in:

```http
HTTP/1.1 403 FORBIDDEN
WWW-Authenticate: Bearer error="insufficient_scope", error_description="Insufficient scope for this resource", scope="scim.read"
{
  "error":"insufficient_scope",
  "error_description":"Insufficient scope for this resource","scope":"scim.read"
}
```

**Comment by wilkinsona** [comment]
I don't think security's unique in this regard. There are lots of other cross-cutting concerns in a RESTful API:

- Use of PUT vs PATCH
- Rate limiting
- Links (hypermedia)
- Paging
- Use of HTTP status codes
- Errors

The samples touch on some of these by [describing them in an overview section](https://github.com/spring-projects/spring-restdocs/blob/master/samples/rest-notes-spring-hateoas/src/main/asciidoc/api-guide.adoc#overview). I could add security to one of the existing samples but I'm not convinced that it deserves special treatment.

**Comment by rwinch** [comment]
You are correct that there are other cross cutting concerns. I personally find that these cross cutting concerns are the most difficult things to document. This is particularly true when the result of one request needs to be included in most of (if not all) of the other requests.

A concrete example with security is that when I authenticate I get back some token and that token needs to be included in every request. How is that documented? 

What is interesting to me is that despite being in the overview, the HTTP method is restated in the documentation. Will the documentation state that credentials need to be included in the request? Will it link to how to obtain the credentials? 

At minimum adding samples like this would help improve the implementation. For example, master currently documents a curl example as:

```bash
curl 'http://localhost:8080/notes' -i -H 'Authorization: Basic dXNlcjpwYXNzd29yZA=='
```

Obviously this is fine. However, ideally it should be documented as

```bash
curl -u user:password 'http://localhost:8080/notes' -i 
```

**Comment by wilkinsona** [comment]
One of the key principles of Spring REST Docs is that it doesn't force you to document your API in a particular way. You can take the generated snippets and use them however you see fit. Thus far, I've avoided offering any recommendations or guidance on how to document an API in the reference manual as I don't think that's the right place for it. In my documenting RESTful API's presentation (linked to in the README) I offer some opinions on what makes good RESTful API documentation. That presentation in written form could prove useful, but I'm not sure that it necessarily belongs in this project.

> I personally find that these cross cutting concerns are the most difficult things to document. This is particularly true when the result of one request needs to be included in most of (if not all) of the other requests.

> A concrete example with security is that when I authenticate I get back some token and that token needs to be included in every request. How is that documented?

I like the way that GitHub have handled this in the [authentication section](https://developer.github.com/v3/#authentication) of their API documentation. If asked, I would advise people to do something similar.

> What is interesting to me is that despite being in the overview, the HTTP method is restated in the documentation.

That's just a choice I made in the sample. The section in the overview is there to make two points:

- HTTP verbs are used in a standard way
- The use of PATCH vs PUT for updates

The verb's then mentioned in the documentation for each resource as a reminder. If you don't like that repetition, then Spring REST Docs doesn't force you to have it.

> Will the documentation state that credentials need to be included in the request? Will it link to how to obtain the credentials?

Again, that's something that's totally up to you.

> At minimum adding samples like this would help improve the implementation

I've opened #120 to improve the curl snippet. Thanks for the suggestion.
