### ISSUE TITLE
Add class name option to snippet output file name

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#116]
To add some general request/response pre-processors for each test I'm now moving the following setup found in the docs:

```
@Before
public void setup() {
     this.document = document("{method-name}", 
             preprocessRequest(removeHeaders("Foo")),
             preprocessResponse(prettyPrint()));
     this.mockMvc = MockMvcBuilders
             .webAppContextSetup(this.context)
             .alwaysDo(this.document) 
             .build();
}
```

I came from the approach where I used hardcoded names like: `.andDo(document("products-create-example",`
Off course I can change the method name, but I'm wondering if it wouldn't possible to (optionally) add the class name to the outputted file name, or even better put in a subfolder.

E.g. when having `ProductApiTests.createExample` we could do something like:

* `document("{method-name}")`
* `document("{class-name}-{method-name}")`
* `document("{class_name}_{method_name}")`
* `document("{class-name}\{method-name}")`
* etc...

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

I thought about this when I implemented `{method-name}` and couldn't convince myself that it was useful enough to be worth it. I kept coming back to just using the class name directly in your `@Before` method. For example:

```java
@Before
public void setup() {
     this.document = document("product-api-tests/{method-name}", 
             preprocessRequest(removeHeaders("Foo")),
             preprocessResponse(prettyPrint()));
     this.mockMvc = MockMvcBuilders
             .webAppContextSetup(this.context)
             .alwaysDo(this.document) 
             .build();
}
```

The only situations were this would be ideal that I could think of are:

- You want to be able to copy and paste the `setup` method
- You want to use an abstract base class for the tests that'll have the `setup` method in it

Does you use case fall into one of those two, or have I overlooked something?

It's still possible to do what you want, you just have to write a bit more code at the moment. In 1.0.0.RC1 you can use a `StandardWriterResolver` with a custom `PlaceholderResolver`:

```
MockMvc mockMvc = MockMvcBuilders
		.webAppContextSetup(this.context)
		.apply(documentationConfiguration(this.restDocumentation).writerResolver(
				new StandardWriterResolver(new PlaceholderResolver() {
					@Override
					public String resolvePlaceholder(String placeholderName) {
						// …
					}

				}))).build();
```

Unfortunately the default `PlaceholderResolver`, `RestDocumentationContextPlaceholderResolver`, isn't as extensible as it could be. I've just fixed that in 5dc28b9 so you can subclass it and override `resolvePlaceholder`.

All that said, I'm not against adding support for `{ClassName}`, `{class-name}`, and `{class_name}` if people would find it generally useful.

**Comment by marceloverdijk** [comment]
Yes I use a abstract base class for all my documentation test classes.
In this base class I setup the `MockMvc` and `RestDocumentationResultHandler` instances.

**Comment by marceloverdijk** [comment]
💪
