### ISSUE TITLE
rest-notes-spring-data-rest gradle building removed from M1 -> RC1

### ISSUE THREAD

**Issue by steviemo** [spring-projects/spring-restdocs#117]
Gradle building has been removed from the milestone to the release candidate.

**Comment by wilkinsona** [comment]
That was intentional. Supporting both build systems in the same project was proving to be more trouble than it was worth. See the `rest-notes-spring-hateoas` sample for a Gradle-based build.

**Comment by steviemo** [comment]
No worries - having a gradle wrapper is so much handier though as you don't have to worry about build tool versions - just check it out and ./gradlew clean build
