### ISSUE TITLE
Using Spring REST Docs with Slate

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#124]
https://github.com/tripit/slate

I really like the UI, but it requires hand-written Markdown. You could use custom snippet templates to generate Slate-friendly Markdown rather than Asciidoc and some additional processing to merge everything together.

It'd be nice to have a sample that illustrates this approach. Producing the sample might also highlight some areas where Spring REST Docs could be enhanced to make things easier.

**Comment by spencergibb** [comment]
:+1: that does look nice.

**Comment by shakuzen** [comment]
:+1:

**Comment by MaciejHadam** [comment]
+1 to sample

**Comment by wilkinsona** [comment]
@MaciejHadam There's [a branch in this repository](https://github.com/spring-projects/spring-restdocs/tree/slate/samples/rest-notes-slate) that shows how to use Slate with Spring REST Docs and Gradle. You might also be interested in the [Chaos Loris](https://github.com/strepsirrhini-army/chaos-loris) project that uses Spring REST Docs and Slate with Maven.
