### ISSUE TITLE
Documentation Incorrect for documentationConfiguration

### ISSUE THREAD

**Issue by juicegit** [spring-projects/spring-restdocs#130]
In the getting started documentation it states to get reference of `documentationConfiguration` from `RestDocumentation` when it should be `MockMvcRestDocumentation`.

          The MockMvc instance is configured using a RestDocumentationConfigurer. An instance of this class can be obtained from the static documentationConfiguration() method on org.springframework.restdocs.RestDocumentation.

**Comment by wilkinsona** [comment]
Thanks, but @pcvolkmer beat you to it. See #118.
