### ISSUE TITLE
Host header cannot be removed by a preprocessor

### ISSUE THREAD

**Issue by kpb** [spring-projects/spring-restdocs#134]
For example:
```java
this.mockMvc.perform(get("/index").accept(MediaType.APPLICATION_JSON))
                    .andExpect(status().isOk())
                    .andDo(document("index", preprocessRequest(removeHeaders("Host"))));
```
http-request.adoc still contains:

GET /deployment/cluster/current HTTP/1.1
Host: host.address
Accept: application/json

and the generated html contains the same.

I've tried all the other preprocessors  (prettyPrint, replacePattern, etc.) to the preProcessRequest and preProcessResponse with no luck.

**Comment by wilkinsona** [comment]
The `Host` header is a special case. A valid HTTP/1.1 request requires a `Host` header so `HttpRequestSnippet` will [always add one if the header's missing](https://github.com/spring-projects/spring-restdocs/blob/v1.0.0.RC1/spring-restdocs-core/src/main/java/org/springframework/restdocs/http/HttpRequestSnippet.java#L82-L84).

The other preprocessors should all work, and there are [integration tests for request and response preprocessing](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-mockmvc/src/test/java/org/springframework/restdocs/mockmvc/MockMvcRestDocumentationIntegrationTests.java#L241-L319) that run on every build.

If you'd like me to investigate further, please provide a sample project that reproduces the problem.

**Comment by kpb** [comment]
Are there any other special cases?

I just removed Content-Type from the response with preprocessResponse(removeHeaders("Content-Type")), so I'll close this.

**Comment by wilkinsona** [comment]
The `Host` header is the only special case. I'm going to re-open this to remind me to update the documentation.

**Comment by kpb** [comment]
Or, maybe throw an Illegal Arg Exception if someone passes a param into a preprocessor that won't work.

**Comment by wilkinsona** [comment]
Unfortunately, that would require the preprocessor to have knowledge of the behaviour of a particular snippet and I don't want to introduce that coupling.

**Comment by wilkinsona** [comment]
I've updated the documentation to describe the special treatment of the `Host` header by the HTTP request snippet.

If you really don't want the Host header to appear in the `http-request.adoc` snippet then you can subclass `HttpRequestSnippet` and override `createModel(Operation)`. Call `super.createModel(Operation)` and then update the map to remove the `Host` header.

**Comment by wilkinsona** [comment]
Having looked at #111, I don't think the `Host` should be a special case. It would be more appropriate to handle it in the same was as the `Content-Length` header is now handled, i.e. the header is added automatically but can still be removed via a preprocessor if desired.
