### ISSUE TITLE
Provide easy way to add context path to sample curl request

### ISSUE THREAD

**Issue by kpb** [spring-projects/spring-restdocs#135]
I have a project named 'myapp'. When I deploy to a web server, the context path is '/myapp'.

Requests to a Controller with a RequestMapping(value="/some/resource") will be accessed with:

```bash
$ curl http://example.com/myapp/some/resource ...
```

The generated snippet will create:

```bash
$ curl http://example.com/some/resource
```
which is only useful for apps deployed to the root context. I don't see an easy way to change this via config. (setting the contextPath on the MockMvc.perform() won't work, because the RequestMapping doesn't include the contextPath).

**Comment by wilkinsona** [comment]
This is already possible. As [described in the documentation](http://docs.spring.io/spring-restdocs/docs/1.0.0.RC1/reference/html5/#configuration-uris), you should use `contextPath` on `MockHttpServletRequestBuilder` to configure the context path. I've just added a test in 5051429 that verifies the behaviour.

**Comment by kpb** [comment]
Don't you get a 
```java
java.lang.IllegalArgumentException: requestURI [/some/resource] does not start with contextPath [/context]
```
Not sure how this should work in practice.

**Comment by wilkinsona** [comment]
Did you look at the test that I added? You need to provide a request URI that begins with the context path. Mock MVC is then smart enough to strip off the context path before it figures out which request mapping will handle the request, just as would happen in a real servlet container. In your case, you should set the context path to `/myapp` and use `/myapp/some/resource` as the request URI:

```java
mockMvc.perform(get("/myapp/some/resource/").contextPath("/myapp"))
		.andExpect(status().isOk()).andDo(document("custom-context-path"));
```

You might also like to read the [relevant section of the Spring MVC Test documentation](http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/integration-testing.html#spring-mvc-test-server-performing-requests).

**Comment by kpb** [comment]
Thanks. I did look at the tests you added. What I was missing was adding the context path to the url as well as via contextPath(). 

Thanks again.
