### ISSUE TITLE
Can't use attributes in snippets

### ISSUE THREAD

**Issue by kpb** [spring-projects/spring-restdocs#136]
Maybe I'm just doing it wrong:

```java
this.mockMvc.perform(get("/hello"))
                .andExpect(status().isOk())
                .andDo(document("hello", curlRequest(attributes(key("foo").value("bar")))));
```

and then in my curl-request.snippet
```
Foo is: {{foo}}
```
Gives me a:
```
org.springframework.restdocs.mustache.MustacheException$Context: No method or field with name 'foo' on line 5
```
I have a small project with this test in it - but just noticed that github doesn't seem to support attaching an archive to an issue. Let me know if getting you a complete project would help.

**Comment by wilkinsona** [comment]
The curl request snippet is [one of the default snippets](http://docs.spring.io/spring-restdocs/docs/1.0.0.RC1/reference/html5/#configuration-default-snippets). That default snippet will be failing as it hasn't been configured with any attributes.

Try changing the default snippets so that the curl snippet isn't one of them. For example:

```java
this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
        .apply(documentationConfiguration(this.restDocumentation).snippets()
                .withDefaults(httpRequest(), httpResponse()))
        .build();
```

**Comment by kpb** [comment]
Well, that works. It could be better documented - since I thought I was modifying the default snippet.

I was going to make a doc change and pull request - but I'm not sure where it belongs.

**Comment by wilkinsona** [comment]
That's a fair point. The javadoc for `curlRequest` (and the other methods that return a `Snippet`) could be improved to make it clear that you'll get a new `Snippet` instance.
