### ISSUE TITLE
Wrong class mentioned in documentation section "Setting up Spring MVC test"

### ISSUE THREAD

**Issue by FrVaBe** [spring-projects/spring-restdocs#137]
See section "Generating documentation snippets -> Setting up Spring MVC test" of the documentation.

> The MockMvc instance is configured using a RestDocumentationConfigurer. An instance of this class can be obtained from the static documentationConfiguration() method on org.springframework.restdocs.RestDocumentation.

As far as I see in 1.0.0.RC1 it is not **org.springframework.restdocs.RestDocumentation** that offers the **documentationConfiguration()** method but **org.springframework.restdocs.mockmvc.MockMvcRestDocumentation**

**Comment by wilkinsona** [comment]
Thanks. This has already been fixed in the latest snapshots: http://docs.spring.io/spring-restdocs/docs/1.0.x-SNAPSHOT/reference/html5/#getting-started-documentation-snippets-setup

**Comment by FrVaBe** [comment]
Perfect. Sorry for the touble in this case.
