### ISSUE TITLE
Question about JsonFieldType

### ISSUE THREAD

**Issue by jrrickard** [spring-projects/spring-restdocs#138]
Date is technically an object in JavaScript and is represented as a String in JSON, so I have been using JsonFieldType.String when I am documenting. Is Date a special enough case to warrant another "type" definition for documentation purposes?

**Comment by wilkinsona** [comment]
`JsonFieldType` is intended to enumerate all of the types that are supported by JSON. There's no JSON standard for representing a date so I don't think it's appropriate to add a `Date` type.

Note that `fieldWithType` takes an `Object` so, if you're not using the [support for determining the type automatically](http://docs.spring.io/spring-restdocs/docs/1.0.0.RC1/reference/html5/#documenting-your-api-request-response-payloads-json-field-types), you can pass whatever you like in as the type. The `toString` method of whatever you pass in will be used in the resulting documentation snippet.
