### ISSUE TITLE
Provide ability to configure curl snippet to emit request parameters on POST/PUT as Query Parameters

### ISSUE THREAD

**Issue by jrrickard** [spring-projects/spring-restdocs#139]
Feel free to reject this because I'm sure it's a corner case related to terrible API design.

Here is my situation:

The legacy API I am trying to document makes use of query parameters on POST/PUT calls. The curl snippet that is getting generated is not correct for my request. 

For example:

```
curl 'https://localhost:8443/path' -i -X PUT -H 'Accept: application/json' -d 'mode=EXTENDED'
```

That's incorrect for how we have the request setup, instead it should be something like:

```
curl 'https://localhost:8443/path?mode=EXTENDED' -i -X PUT -H 'Accept: application/json'
```

I think this is the responsible bit of code in CurlRequestSnippet :

```
else if (isPutOrPost(request)) {
			String queryString = request.getParameters().toQueryString();
			if (StringUtils.hasText(queryString)) {
				writer.print(String.format(" -d '%s'", queryString));
			}
		}
```

I can come up with a solution to this and submit a PR if you're interested in taking on a change like that. If no, I'll work around it on my end :)

Thanks!

**Comment by wilkinsona** [comment]
@jrrickard Thanks for the offer of a PR, but I think I've just taken care of this one in 0d2c24c. Now, if you provide parameters as query parameters, then they'll stay as query parameters and won't be used to populate curl's `-d` option.

**Comment by jrrickard** [comment]
Thanks for the speedy response @wilkinsona! Appreciate it.
