### ISSUE TITLE
Unable to import project in STS

### ISSUE THREAD

**Issue by dhaval201279** [spring-projects/spring-restdocs#141]
Hi,

I am trying to import this project. However, I am facing issue whilst doing following steps -
1. Download the zip
2. Unzip it
3 Import unzipped project as Gradle Project in STS
4. Execute Build Model

After 4th step, I am getting following error trace - 
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Downloads\spring-restdocs-master\build.gradle' line: 140

* What went wrong:
A problem occurred evaluating root project 'spring-restdocs'.
> java.lang.NullPointerException (no error message)

Request you to let me know how to fix workspace setup issue?

Regards,

**Comment by wilkinsona** [comment]
Sounds like a bug in the Gradle tooling in Eclipse/STS. I don't use it. Instead I run `./gradlew eclipse` on the command line and then use File -> Import... -> Existing Projects into Workspace.
