### ISSUE TITLE
All links in the spring-restdocs documentation to a github page get 404s because of missing slash

### ISSUE THREAD

**Issue by haisi** [spring-projects/spring-restdocs#147]
In the official spring-restdocs documentation site all links to github are wrong because slashes were forgotten.

You probably need ```/{samples}/rest-notes-spring-hateoas[One sample]``` instead of ```{samples}/rest-notes-spring-hateoas[One sample]```

An example link to the spring-restdocs sample is the following:
https://github.com/spring-projects/spring-restdocs/tree/v1.0.0.RELEASEsamples/rest-notes-spring-hateoas
and not to
https://github.com/spring-projects/spring-restdocs/tree/v1.0.0.RELEASE/samples/rest-notes-spring-hateoas

**Comment by wilkinsona** [comment]
Sorry, how annoying. Thanks for letting me know. The fixed documentation should be available from http://docs.spring.io/spring-restdocs/docs/1.0.x-SNAPSHOT/reference/html5/ once the CI build completes and the cron job that auto-publishes the documentation has run. Within the next 20-30 minutes hopefully.
