### ISSUE TITLE
Wrong links to sample projects

### ISSUE THREAD

**Issue by mvitz** [spring-projects/spring-restdocs#148]
The links to the sample projects on http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-sample-applications are wrong.
The "One sample" link points to https://github.com/spring-projects/spring-restdocs/tree/v1.0.0.RELEASEsamples/rest-notes-spring-hateoas instead of https://github.com/spring-projects/spring-restdocs/tree/v1.0.0.RELEASEsamples/rest-notes-spring-hateoas (notice the missing / after RELEASE and before samples. The templates just contain a placeholder ({samples}) but I couldn't find out where this is resolved.
Same problem with "the other" link.

**Comment by wilkinsona** [comment]
Thanks. This one was fixed in #147.
