### ISSUE TITLE
Make MustacheTemplateEngine's Compiler configurable

### ISSUE THREAD

**Issue by iabudiab** [spring-projects/spring-restdocs#149]
Currently there is no (easy) way to configure the `Mustache.Compiler` used in the `MustacheTemplateEngine`, thus it is not (easily) possible to define own/custom formatter, null values, escaper..etc to handle template compiling.

Two workarounds are possible, but not optimal:
- Accessing the `Compiler` in a `MustacheTemplateEngine` instance per reflection.
- Custom `TemplateEngine` subclass with configurable `Compiler`, which is I am currently using.

**Comment by wilkinsona** [comment]
Would providing some overloaded constructors on `MustacheTemplateEngine` meet your needs? 

Related to this, `MustacheTemplateEngine` using a `StandadTemplateResourceResolver` by default is currently specified in `RestDocumentationMockMvcConfigurer`. That default isn't MockMvc-specific, so it should be in MockMvc-specific code. Tackling both your requirement and the default value of the template resource resolver would result in four constructors:

```java
public MustacheTemplateEngine() {
	this(new StandardTemplateResourceResolver());
}

public MustacheTemplateEngine(TemplateResourceResolver templateResourceResolver) {
	this(templateResourceResolver, Mustache.compiler().escapeHTML(false));
}

public MustacheTemplateEngine(Compiler compiler) {
	this(new StandardTemplateResourceResolver(), compiler);
}

public MustacheTemplateEngine(TemplateResourceResolver templateResourceResolver,
		Compiler compiler) {
	this.templateResourceResolver = templateResourceResolver;
	this.compiler = compiler;
}
```

You can then configure a custom compiler like so:

```
MockMvc mockMvc = MockMvcBuilders
		.webAppContextSetup(this.context)
		.apply(documentationConfiguration(this.restDocumentation).templateEngine(
				new MustacheTemplateEngine(Mustache.compiler().withFormatter(
						customFormatter)))).build();
```

**Comment by iabudiab** [comment]
@wilkinsona Thanks for the speedy reply. 

Sounds good to me. That's exactly what I am currently doing in my `TemplateEngine` subclass anyway. Having this in the framework would render the need for subclassing obsolete.

**Comment by wilkinsona** [comment]
Things have moved on a little since the original discussion. The default use of `StandardTemplateResourceResolver` is now encapsulated in `RestDocumentationConfigurer` that isn't `MockMvc` specific. I don't want to add constructors to `MustacheTemplateEngine` that hard code that default in a second place. The compiler can still be made configurable by providing a single additional constructor:

```java
public MustacheTemplateEngine(TemplateResourceResolver templateResourceResolver,
        Compiler compiler) {
    this.templateResourceResolver = templateResourceResolver;
    this.compiler = compiler;
}
```
