### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by kurron** [spring-projects/spring-restdocs#15]
I have an update to the README file describing how to enable JSON pretty printing when operating in a Spring Boot environment but I'm usure how to proceed.  Normally, I snap a branch and issue a PR but I don't appear to have the ability to create a branch from the GitHub UI.  Is there a document describing the contribution process I can read?

Thanks,
Ron

**Comment by gregturn** [comment]
Fork the repo and make your branch off that. Then you can PR from your own branch.

**Comment by wilkinsona** [comment]
@kurron The approach Greg mentions is described [here](https://help.github.com/articles/using-pull-requests/)

**Comment by kurron** [comment]
Thanks. I'll give that a try.

**Comment by wilkinsona** [comment]
See #16
