### ISSUE TITLE
Improve reusability of StandardWriterResolver

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#150]
If you want to create snippets with a different file extension you can't use `StandardWriterResolver` as it hardcodes the `.adoc` extension.

This relates to #124 as Slate uses Markdown.

**Comment by otrosien** [comment]
Looking forward to this, I'm currently implementing a WiremockSnippetsWriter, which requires me to generate .json files.

**Comment by wilkinsona** [comment]
@otrosien Thanks for letting me know. Is that the only pain point that you're seeing at the moment? In 1.1, I'd like to make it easier to switch between snippet types. Your use case sounds like a very good fit for making sure I've got it right.

**Comment by otrosien** [comment]
@wilkinsona thanks for asking. Indeed, this is the only pain point ATM. The rest is pretty straight-forward, as generating json from a restdocs.Operation object is really simple. 

I'm using gradle for collecting these snippets into a jar file, which can be used by the clients of my rest api for testing against. I'm still undecided how much of the input should be used in wiremock request matching (and if I want to make this configurable somehow). 

I could share some code if you like, and if it is of interest to a broader audience. I would expect that creating rest api stubs is outside of the scope of spring restdocs, but it actually fits really nicely. I basically got inspired to implement this by @dsyer and @spencergibb who mentioned it in their great talk "developer experience with spring cloud".

**Comment by wilkinsona** [comment]
> I could share some code if you like, and if it is of interest to a broader audience

Yes, please

>  I would expect that creating rest api stubs is outside of the scope of spring restdocs, but it actually fits really nicely

I'm not sure that it is out of scope. JSON that's consumed by Wiremock (or whatever) is, arguably, just another form of documentation. It's just in a format that's more machine-friendly than HTML generated with Asciidoctor. In a similar vein, others have expressed an interest in REST Docs being able to produce a Swagger spec.

**Comment by otrosien** [comment]
Alright then, once it's possible to produce a .json I'll be happy to prepare a pull request for wiremock support.

**Comment by wilkinsona** [comment]
Looking forward to it

**Comment by otrosien** [comment]
@wilkinsona I need to followup on this. Just had a look at the code in 1.1.0 M1, and I still don't see the possibility to write json snippets in addition to the normal rest documentation snippets. It seems to me that you need to decide on one template format up-front.

**Comment by wilkinsona** [comment]
@otrosien You can configure the template format on a per-test basis. Do you want a single test to be able to write snippets in a variety of formats?

**Comment by otrosien** [comment]
yes, I want the test to write asciidoctor snippets and at the same time write a wiremock json snippet.

**Comment by wilkinsona** [comment]
A custom `WriterResolver` is the best way to achieve that at the moment. Feel free to open a new issue if you'd like to explore the possibility of making it easier.

**Comment by otrosien** [comment]
I'll give it a try, probably creating a small github project with the current state. You made the StandardWriterResolver final, so there'll be some copy&paste code.

**Comment by otrosien** [comment]
can I actually register two WriterResolvers?

**Comment by wilkinsona** [comment]
> You made the StandardWriterResolver final, so there'll be some copy&paste code.

I did indeed as it hasn't been designed for subclassing. That could change if necessary, but I'd be interested to see how it worked out with composition rather than inheritance. That said, creating your own `StandardWriterResolver` to delegate to is harder than it should be as you need to get hold of the `RestDocumentationContext`.

> can I actually register two WriterResolvers?

No. `TemplatedSnippet` expects to find and use a single `WriterResolver`.

Thinking about this some more, and given that you want to write out JSON, I wonder if it might not be easier to write your own `Snippet` implementation that isn't a subclass of `TemplatedSnippet`. That would give you complete control over writing it out.

**Comment by otrosien** [comment]
@wilkinsona already doing it, but if I want to reuse WriterResolver.resolve() for inserting operation name into the file path, I end up writing a json string to a file with .adoc suffix.
