### ISSUE TITLE
Create request parameter snippet with "Required" column

### ISSUE THREAD

**Issue by shakuzen** [spring-projects/spring-restdocs#152]
How hard would it be for Spring REST Docs to discover whether request parameters are required or not? It might be nice to add this to the default template with a "Required?" column that simply documents "Yes" or "No".

**Comment by wilkinsona** [comment]
The philosophy of Spring REST Docs is to help and encourage people to produce documentation that's accurate and well-structured, even if that requires them to expend a little more effort. While the requirement for a request parameter could be automatically determined in some cases, there are others where it's impossible. I don't want to provide something that only works some of the time and lulls people into a false sense of security about the accuracy of their documentation. [Other tools are available](https://github.com/springfox/springfox) for those who prefer to prioritise speed over documentation quality.

**Comment by shakuzen** [comment]
Thank you for the explanation Andy. I can certainly understand and agree with that reasoning.
