### ISSUE TITLE
Investigate error output produced by Spring HATEOAS sample

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#153]
Reported by @shakuzen on Gitter:

> Have you noticed that in the HATEOS sample for Spring REST Docs that the ApiDocumentation outputs the following error to the console for each perform() call (though there seems to be no problem for the actual test)?
```
[Fatal Error] :1:1: Premature end of file.
ERROR:  'Premature end of file.'
```
> It seems to only happen with the way the HATEOS sample instantiates/uses the `MockMvc` and/or `RestDocumentationResultHandler`. The Spring Data REST sample does not output that error. My project as well did not output that error until I changed to using the `RestDocumentationResultHandler` like the HATEOS sample and configuring the `MockMvc` instance like it does.

**Comment by Pytry** [comment]
I've just started (finally) using rest docs, and I used the HATEOS project as my template. My MockMvc is configured the same as well. I am also getting that same end of file error, even though the tests all pass and the snippets are created.
