### ISSUE TITLE
Could you please provide maven version of project as well ?

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-restdocs#158]

**Comment by wilkinsona** [comment]
Sorry, but I don't understand your question. There's nothing in Spring REST Docs that ties it to any particular build system. Samples and documentation are provided showing how to use it with both Maven and Gradle. What exactly are you looking for?

**Comment by YLombardi** [comment]
I think he ask for an sample project that use maven configuration.

**Comment by wilkinsona** [comment]
The project already has one of those: the [Spring Data REST-based sample](https://github.com/spring-projects/spring-restdocs/tree/master/samples/rest-notes-spring-data-rest) uses Maven.

**Comment by wilkinsona** [comment]
Closing due to lack of response
