### ISSUE TITLE
Mark deprecation and replacement on fields

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-restdocs#159]
It would be good to be able to mark deprecation and replacement on fields in documentation as follows:

```
fieldWithPath("name").description("your real name")
  .deprecation("some reason", "some replacement if any")
```

**Comment by wilkinsona** [comment]
I don't think that this will have broad enough appeal that it warrants there being a specific method for configuring deprecation information for a field. Instead, you should use a custom attribute and a custom template for the fields snippet. You can find more information about this approach [in the documentation](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-customizing-including-extra-information).

**Comment by izeye** [comment]
@wilkinsona Ok. Thanks for the feedback!

**Comment by izeye** [comment]
@wilkinsona Sorry but is it possible to make a field in snippet optional? When I added a `deprecation` field to `response-fields.snippet`, I had to add the attribute to all `fieldWithPath()`.

**Comment by wilkinsona** [comment]
@izeye I'm guessing you'd like an empty entry in the table for fields that are not deprecated, correct?

**Comment by izeye** [comment]
@wilkinsona Yes. Without adding empty attribute values explicitly.

**Comment by wilkinsona** [comment]
It's possible, but you need to use a Mustache Compiler that's configured to use an empty string in place of any null values:

```
Mustache.compiler().nullValue("");
```

Unfortunately, configuring Spring REST Docs to use such a custom Mustache Compiler is harder than it needs to be. See #149 for more information and for some suggestions on how you can configure it today.

**Comment by izeye** [comment]
@wilkinsona Thanks for the pointer. I'll have a look.

**Comment by jarl-dk** [comment]
Too bad this FR is declined...
