### ISSUE TITLE
Support for documenting part names in a multipart request

### ISSUE THREAD

**Issue by rozhok** [spring-projects/spring-restdocs#161]
Hello, have following controller:
```java
@RequestMapping(value = "/{id}/photos", method = POST)
public Object addPhotos(@PathVariable String id,
                                 MultipartRequest images) {
    List<MultipartFile> photos = images.getFiles("photos");
    List<MultipartFile> floorPlans = images.getFiles("plans");
```

Basically it accepts any number of files sorted by some criteria and stores them.

How to document this? As far as I understand, there is no option to document form input names.

Also, if I use uploadFile() then I'm unable to document path variable.

**Comment by wilkinsona** [comment]
> Basically it accepts any number of files sorted by some criteria and stores them.
> How to document this? As far as I understand, there is no option to document form input names.

What does you test look like at the moment?

> Also, if I use uploadFile() then I'm unable to document path variable.

Are you using `RestDocumentationRequestBuilders.fileUpload()`?

**Comment by rozhok** [comment]
```java
    protected void uploadPictures() throws Exception {
        String snippetName = "upload-pictures";

        ClassPathResource plan = new ClassPathResource("plan-1.jpg");
        MockMultipartFile planFile = new MockMultipartFile("plans", plan.getFilename(), "", new FileInputStream(planFile.getFile()));

        ClassPathResource photo = new ClassPathResource("photo-1.jpg");
        MockMultipartFile photoFile = new MockMultipartFile("photos", photo.getFilename(), "", new FileInputStream(photo.getFile()));

        ResultActions reponse = mockMvc.perform(RestDocumentationRequestBuilders
                .fileUpload(format("/api/sutff/{id}/%s", "photos"), id)
                .file(planFile)
                .file(photoFile))
                .andExpect(status().isOk())
                .andDo(document(snippetName,
                                pathParameters(
                                        parameterWithName("id").description("Unique id")
                                )
                        )
                )
                .andDo(result -> apiGuideCreator.describeSnippet(snippetName, "Upload", "Full description"));
    }
```

**Comment by wilkinsona** [comment]
You didn't answer my question about using `RestDocumentationRequestBuilders.fileUpload()`. Where you using it before when you said that documenting the path parameter didn't work. It works for me, producing the following snippet:

```
./{id}/photos
|===
|Parameter|Description

|id
|Unique id

|===
```

The existing HTTP request snippet should show a correctly formatted `multipart/form-data` request for all the parts you're uploading. For example:

```
[source,http]
----
POST /5/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=6o2knFse3p53ty9dmcQvWAIx1zInP11uCfbm
Host: localhost

--6o2knFse3p53ty9dmcQvWAIx1zInP11uCfbm
Content-Disposition: form-data; name=plans

<<binary data>>
--6o2knFse3p53ty9dmcQvWAIx1zInP11uCfbm
Content-Disposition: form-data; name=photos

<<binary data>>
--6o2knFse3p53ty9dmcQvWAIx1zInP11uCfbm--
----
```

There's no other multipart-specific support beyond that at the moment. What would you like to be able to document? Just the names of the parts, i.e. "photos" and "plans", or more than that?

**Comment by rozhok** [comment]
Sorry for confusing about path parameters, they're working as expected.
I want to document file names also.

Thanks.

**Comment by rozhok** [comment]
Alrait...

Now I have following controller:

```
@ResponseBody
@RequestMapping(value = "/attachments/upload", method = RequestMethod.POST)
public Object createAndUploadAttachment(HttpServletRequest request) throws IOException, ServletException {
    Part filePart = request.getPart("file");
    String fileName = request.getParameter("fileName");
    Assert.notNull(filePart, "Upload data is empty");
    // save file
}
```
I'm doing following tests
```
MockMultipartFile fileToUpload = // doing stuff...
MvcResult mvcResult = mockMvc.perform(RestDocumentationRequestBuilders
        .fileUpload("/api/attachments/upload")
        .file(fileToUpload)
        .param("fileName", fileName)
        .headers(HEADERS)
        .contentType(MediaType.MULTIPART_FORM_DATA))
        .andExpect(status().isOk())
        .andReturn();
```
With no luck. No data comes into controller.

I've tried another way - use post + content(byte[]) with same result.

What is the proper way to test out such uploads?

**Comment by rozhok** [comment]
Also, now uploaded file contents are displayed in generated snippet, I'd like to strip them.

**Comment by wilkinsona** [comment]
> Also, now uploaded file contents are displayed in generated snippet, I'd like to strip them.

I usually avoid the problem of having to strip out the contents of the uploaded file by uploading the bytes for "<<binary data>>", or similar. That relies on you being able to mock out the code that's called by your controller to actually process the file.

> What is the proper way to test out such uploads?

What you've shown looks reasonable, although I can't be sure as the critical piece is how `fileToUpload` is created. Can you share a complete example that illustrates the problem?

**Comment by rozhok** [comment]
```java
 String originalFilename = "document-to-upload.txt";
 MockMultipartFile fileToUpload = new MockMultipartFile("file", originalFilename, "text/plain", "This document intended to be uploaded and attached to thread.".getBytes());
```
Thats it...Nothing special.

**Comment by psamsotha** [comment]
[The simplest case _would_ be useful.](http://stackoverflow.com/a/37183839/2587435)

**Comment by wilkinsona** [comment]
@psamsotha Thanks. That's what I've implemented. It'll be in 1.1.
