### ISSUE TITLE
Add support for documenting attributes in XML payloads

### ISSUE THREAD

**Issue by cschaetzlein** [spring-projects/spring-restdocs#166]
Given following xml
```xml
<persons>
  <person id="1">
    <firstname>John</firstname>
    <lastname>Doo</lastname>
  </person>
</persons>
```
trying to document the payload with

```java
fieldWithPath("/persons/person/@id").type("type").description("the persons id")
```

will lead to a NullPointerException at line 118

`node.getParentNode()` 
in `org.springframework.restdocs.payload.XmlContentHandler.getUndocumentedContent(List<FieldDescriptor> fieldDescriptors)`

since an attribute node has no associated parent node.

**Comment by wilkinsona** [comment]
The current support for documenting XML payloads is only aimed at documenting elements rather than an individual element's attributes
