### ISSUE TITLE
Support Reusable Snippets

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-restdocs#168]
Given a number of `Pageable` payloads (which typically look like the following)

```json
{
  "_embedded": {
  },
  "_links": {
    "self": {
      "href": "..."
    }
  },
  "page": {
    "size": 20,
    "totalElements": 1,
    "totalPages": 1,
    "number": 0
  }
}
```

The following documentation is needed for all of them:

```java
links(
    linkWithRel("first").optional().description("..."),
    linkWithRel("last").optional().description("..."),
    linkWithRel("next").optional().description("..."),
    linkWithRel("prev").optional().description("..."))
```
```java
requestParameters(
    parameterWithName("page").description("..."),
    parameterWithName("size").description("..."),
    parameterWithName("sort").description("..."))
```
```java
responseFields(
    fieldWithPath("page.number").description("..."),
    fieldWithPath("page.size").description("..."),
    fieldWithPath("page.totalPages").description("..."),
    fieldWithPath("page.totalElements").description("..."))
```

There is currently no way to reuse descriptors (without creating a constant for each and every one of them) that will validate properly as the `Snippet`s are not mutable after creation.

There should be a way to reuse collections of descriptors (as opposed to individual descriptors) in multiple snippet declarations.

**Comment by ipsi** [comment]
I'd also like to see this, for the exact same reasons - a lot of our API calls return the same object, with the same fields, and the same links (sometimes with a few extra), so it's going to be annoying, either copy/pasting documentation, or having manual documentation that we need to link to.
