### ISSUE TITLE
Allow certain links to be ignored by default for a media type

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#177]
For example, when you're using HAL, it could be useful to be able to ignore `self` and `curies` links without having to explicitly say so

**Comment by wilkinsona** [comment]
Given the new support for reusing snippets by creating a copy with additional descriptors, I don't think there's any need to do something specific for this usecase. Instead, a custom `links` static method can be used that makes certain links as ignored (and optional if required), for example:

```java
private LinksSnippet links(LinkDescriptor... descriptors) {
	return HypermediaDocumentation.links(linkWithRel("_self").ignored().optional(),
			linkWithRel("curies").ignored()).and(descriptors);
}
```

**Comment by chrylis** [comment]
I would request reconsidering this issue. While this takes care of the repetition per-test, it's still required to manually copy the incantation into each project, when it seems to me that the OOTB links will always be ignored but can still be explicitly documented if desired.

**Comment by wilkinsona** [comment]
I happy to reconsider this if you have a compelling suggestion for the API that would let you opt in to ignoring certain links
