### ISSUE TITLE
Allow adding up links, response fields etc. more easily

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-restdocs#179]
Currently the use of the static factory methods `links(…)`, `responseFields(…)` etc. seem to be tailored towards direct use within a call to `document(…)`. It would be cool if they actually returned objects that I could go on adding stuff to, by returning an accumulated instance. That would allow to nicely define a commons set of links and response fields that can act as a foundation for multiple documentation step but can be augmented for each individual case:

```java
// Some central place
LinksSnippet paginationLinks = links(…);
ResponseFieldsSnippet paginationFields = responseFields(…);

// In a dedicated configuration step
….document("foo",
  paginationLinks.and(linkWithRef(…), linkWithRef(…)),
  paginationFields.and(fieldWithPath(…), fieldWithPath(…)));
```

See how the prepared instances act as a foundation but return a dedicated augmented instance.

**Comment by wilkinsona** [comment]
See also #168. I'm not sure that they're exactly the same, but they're certainly closely related.

**Comment by wilkinsona** [comment]
Having spent some time implementing this, I'm now pretty sure that this duplicates #168.
