### ISSUE TITLE
Jersey's endpoints support

### ISSUE THREAD

**Issue by demoroz** [spring-projects/spring-restdocs#18]
Andy, guys,

It seems that spring-restdocs does not see methods with javax.ws.rs.Path annotations? Is it possible to workaround somehow?

**Comment by wilkinsona** [comment]
It's Spring MVC Test that needs to be able to "see" the JAX-RS endpoints. How have you configured Jersey in your Spring application? Making Spring MVC Test aware of Jersey's filter might be sufficient but I haven't tried it.
