### ISSUE TITLE
Support for documenting array contents

### ISSUE THREAD

**Issue by ipsi** [spring-projects/spring-restdocs#182]
I'm working on a project where we frequently return lists, e.g:

```json
{
  "_embedded": {
    "things": [
      {"...": "...", "_links": {...}},
      {"...": "...", "_links": {...}},
      {"...": "...", "_links": {...}}
    ]
  }
}
```

This is a list of objects, and those objects have their own fields. Rather than having to copy and paste documentation every time a collection of these objects are returned (or even if the object is just returned a lot, which it is), I'd like to be able to centralize that documentation somewhere and automatically link to it from the "response-fields" page.

Is the current intention that we'd document this object manually and then link to that adoc somehow in the description? Somewhat similar to #168.

**Comment by wilkinsona** [comment]
There's also some overlap with #179, I believe.

Whether you want to document the `things` array for every resource that returns it or document it once and then cross-reference is up to you. The intention is that Spring REST Docs will support either approach equally well. It's currently lacking for the former as it pushes you down the path of copy 'n' paste in your tests.

If #168 and #179 don't fully cover what you'd like to be able to do, can you please describe what's missing in this issue? If they do capture your requirements, then this can probably be closed as a duplicate.

**Comment by wilkinsona** [comment]
I'm going to interpret the lack of a response as meaning that #168 and #179 capture the requirements. If that's not the case, please do comment on this issue with details of what's missing and I'll re-open it.
