### ISSUE TITLE
Endpoints operation grouping table

### ISSUE THREAD

**Issue by tzebrowski** [spring-projects/spring-restdocs#183]
When using swagger2/swagger-UI I noticed nice feature which come out-of-box to it's users. Feature which groups all endpoint operation into table and allows you for fast navigation through all of them. Table is located at the top of document. I am wondering if Spring REST Docs has something similar, or is it possible to generate it somehow automatically based on document content (maybe some macro)? What do you think to introduce such feature to  Spring REST Docs, is it possible?
![swagger](https://cloud.githubusercontent.com/assets/16700009/12324237/864f99be-bac1-11e5-8456-029b640ec086.PNG)

**Comment by wilkinsona** [comment]
Spring REST Docs currently has no strong opinion about the layout of your documentation. That may change as a result of #174 but, for now at least, this is really an Asciidoctor question.

You may like to explore the possibility of using the `toc` macro. Combined with an appropriately structured document, you could use it to display a list of the resources in your API.

The first thing to do is to set the `toc` attribute to `macro`:

```
:toc: macro
```

You can then use the toc::[] to include a table of contents anywhere you like in your documentation, and control its title, levels, etc. For example:

```
toc::[levels=1,title=Resources]
```

You could, perhaps, include one "table of contents" that uses `levels=1` which then becomes a list of the resources in your API alongside a more detailed actual table of contents that displays more levels.

Another option that you might want to look into is using Spring REST Docs combined with [Slate](https://github.com/tripit/slate). Slate has a fairly strong opinion about the structure of the documentation. I have a branch that includes [a sample](https://github.com/spring-projects/spring-restdocs/tree/slate/samples/rest-notes-slate) that demonstrates the approach. Spring REST Docs 1.1 will remove some of the boilerplate that's currently required to use Slate (see #124 and the issues that reference it).

**Comment by tzebrowski** [comment]
Thanks for quick reply, I will consider your suggestions!
