### ISSUE TITLE
RestAssured Support & JUnit Dependency

### ISSUE THREAD

**Issue by sg-ad** [spring-projects/spring-restdocs#190]
First, great work on the RestAssured support!  I've started playing with it and it looks good.  I'll experiment with some more advanced stuff later this week.

One thing I noticed is that it seems to assume that JUnit is used to run tests.  The `RestDocumentation` won't have its `RestDocumentationContext` initialized if TestNG is being used.  Should I be initializing things differently?  Here's an example of how I use it:

```java
given()
    .filter(documentationConfiguration(new RestDocumentation("target/generated-snippets")))
    .filter(document("payment-list-example"))
```
Thanks!

**Comment by wilkinsona** [comment]
REST Docs requires JUnit at the moment. #171 is tracking also supporting TestNG.
