### ISSUE TITLE
Allow HeaderRemovingOperatingProcessor to remove all headers

### ISSUE THREAD

**Issue by rhuss** [spring-projects/spring-restdocs#191]
Sometimes headers are not really needed for the examples so it would be nice to have an option to remove them all without having to adapt the template.

**Comment by wilkinsona** [comment]
How about an option that takes one or more regular expressions and removes every header that matches at least one of them? Then, to remove all headers, you could do something like this:

```java
Preprocessors.removeMatchingHeaders(".+")
```

**Comment by rhuss** [comment]
would be perfectly fine. I can prepare a PR for this, it's an easy one ;-)

**Comment by wilkinsona** [comment]
A PR would be much appreciated. Thanks.
