### ISSUE TITLE
Is spring-restdocs compatible with Spring 3 and 2.5? What are other compatibility requirements apart from Java 7?

### ISSUE THREAD

**Issue by tarundatascientist** [spring-projects/spring-restdocs#20]

**Comment by wilkinsona** [comment]
Spring REST Docs uses Spring MVC Test which was introduced in Spring Framework 3.2 so it definitely won't work with a version earlier than that. As expressed in the project's dependencies, using Spring Framework 4.1 is recommended. 4.0 may well work as well but isn't tested.

**Comment by tarundatascientist** [comment]
Thank You for informing. Are there any plans to test with Spring 4.0 and/or with v3.2 and above?

**Comment by wilkinsona** [comment]
I've just taken a closer look and Spring Framework 4.1 is the minimum supported version as the `MockMvcConfigurer` API is new in Spring Framework 4.1. It's used to allow the scheme, host, and port of documented URIs to be configured. It's also a prerequisite for implementing #14. I'll update the README.
