### ISSUE TITLE
[enhancement] User Interface

### ISSUE THREAD

**Issue by geoHeil** [spring-projects/spring-restdocs#205]
http://tripit.github.io/slate/?shell#introduction has already done much for API documentation and provides a nice way to explore an API.

Is it possible to have spring-restdocks create something similar (interactive) as well?

**Comment by wilkinsona** [comment]
> http://tripit.github.io/slate/?shell#introduction has already done much for API documentation and provides a nice way to explore an API.

You can use Spring REST Docs with Slate. There's [a sample](https://github.com/spring-projects/spring-restdocs/tree/v1.1.0.M1/samples/rest-notes-slate) that shows how to do it with 1.1.0.M1.

>  Is it possible to have spring-restdocks create something similar (interactive) as well?

Yes. Please add any opinions you have on how this should look with REST Docs to #174.
