### ISSUE TITLE
Documentation on an endpoint with only String as input in RequestBody

### ISSUE THREAD

**Issue by davinkevin** [spring-projects/spring-restdocs#210]
Hi, 

I try to document something like this : 
```
@RequestMapping(value = "exists", method = RequestMethod.POST, consumes = "text/plain")
public void alreadyExist(@PathVariable UUID id, @RequestBody String email, HttpServletResponse response) {
    ...
}
```

and I've write this kind of simple test : 
```
@Test
    public void should_verify_a_user_doesnt_exist_in_sub() throws Exception {
        String email = "foo.bar@mail.com";

        this.mockMvc
                .perform(
                        post("/api/v1/subscriptions/{id}/users/exists", "0058d39f-daac-01d7-71a4-edbdcea7c480")
                                .contentType(MediaType.TEXT_PLAIN_VALUE)
                                .accept(MediaType.ALL_VALUE)
                                .content(email)
                .andExpect(status().isNoContent())
                .andDo(document("api/v1/subscriptions/id/users/exists/post", preprocessRequest(prettyPrint()), preprocessResponse(prettyPrint()),
                        pathParameters(
                                parameterWithName("id").description("UUID of the subscription")
                        )
                ));

    }
```

All is ok, but I don't find anyway to document the payload of the request. All the method to do that (Payload Documentation) is for working on an object which can be handle by Jackson, and in this case, a String is not a parseable element.

Do I misunderstand something or is it impossible to do that ?

Thanks for your help

**Comment by wilkinsona** [comment]
What help would you like REST Docs to give you? Given that the payload is a String, I'm not sure what benefit you'd get from an auto-generated snippet. Could you not just document the payload directly in your Asciidoctor source?

**Comment by davinkevin** [comment]
Having the same way of generating snippet with primitive and JSON / XML could be better I think.
It could generate a single line table with location (obviously, root of RequestBody), Type and Description.

And, if that is possible, if in the future the input type of the controller change (for a JSON Object for example), the RestDoc will throw a error because the object is not correctly documented.

Right now, I've documented directly in the Asciidoctor source, but I think it isn't a consistent way of documenting the API, this is why I open an issue.

Thanks for your help

**Comment by wilkinsona** [comment]
The problem is that JSON and XML payloads are both strings, albeit with a well-defined structure. How do you propose that a non-conforming string is identified to cause a test failure? Right now, I'm not sure that there's a generally useful way to do what you want. I'd happily be wrong though.

May I suggest that you write your own `Snippet` implementation that does what you want? It may provide some inspiration for something that would be generally useful. I'm happy to help you get started with that process. The source of the existing snippets should also be a good reference.

**Comment by davinkevin** [comment]
Thank for your answer.

Actually, you are right about JSON | XML which are only strings until Jackson (or other) parse it. I totally forgot it.

I will look the snippet documentation to see if I can do something about that.

Thank again for your time / help.

**Comment by wilkinsona** [comment]
Thanks for the follow up. Sounds like this discussion has run its course. We can reopen the issue if that proves not to be the case.
