### ISSUE TITLE
Is it possible to re-use response fields for endpoint returning array of fields?

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-restdocs#221]
Simple example:

Suppose `/api/books/` returns an array like this:

    [{"id":1, "title":"Some book"},{"id":2, "title":"Other book"}]

And `/api/books/1` returns:
    
    {"id":1, "title":"Some book"}

If I have:

    .andDo(document("book-example",
      responseFields(
        fieldWithPath("id").description("..."),
        fieldWithPath("title").description("..."),
    )

Is there a way to re-use that `responseFields` object (given I put in a method or something) to document the array returning endpoint? To avoid having to type all fields again, just prefixing them with `[]` like this:

    .andDo(document("books-example",
      responseFields(
        fieldWithPath("[].id").description("..."),
        fieldWithPath("[].title").description("..."),
    )

**Comment by wilkinsona** [comment]
Interesting requirement. Thanks for opening the issue.

It's similar to what was recently implemented for #168 which allowed a snippet to be reused with new descriptors being added to it. I didn't consider the possibility of reusing a snippet by slightly modifying its existing descriptors.

How about something like this in `ResponseFieldsSnippet`:

```java
/**
 * Returns a new {@code ResponseFieldsSnippet} configured with this snippet's
 * attributes and a copy of its descriptors updated to apply the given {@code prefix}
 * to their paths.
 *
 * @param prefix the prefix to apply to the descriptor paths
 * @return the new snippet
 */
public ResponseFieldsSnippet withPathPrefix(String prefix) {
    // ...
    return new ResponseFieldsSnippet(prefixedDescriptors, this.getAttributes());
}
```

That can then be used like this:

```java
ResponseFieldsSnippet bookFields = responseFields(
		fieldWithPath("id").description("..."),
		fieldWithPath("title").description("..."));

mockMvc.perform(get("/api/books/1"))
        .andDo(document("book-example", bookFields));

mockMvc.perform(get("/api/books/"))
        .andDo(document("books-example", bookFields.withPathPrefix("[].")));
```

**Comment by wimdeblauwe** [comment]
I think that is a good proposal. #168 is also very interesting to have indeed.

**Comment by esixman** [comment]
Thanks.
