### ISSUE TITLE
Should UriModifyingOperationPreprocessor be in the core module?

### ISSUE THREAD

**Issue by psamsotha** [spring-projects/spring-restdocs#225]
There is nothing RestAssured specific about the [`UriModifyingOperationPreprocessor`][1]. IMO, this is enough reason to put it in the core module. Even if MockMvc has no use for it (I don't know, not much of a MockMvc user), it still may be useful for any future implementations. Unless it would break something, were it to be used with MockMvc. Is that the case?

[1]: https://github.com/spring-projects/spring-restdocs/blob/v1.1.0.RC1/spring-restdocs-restassured/src/main/java/org/springframework/restdocs/restassured/operation/preprocess/UriModifyingOperationPreprocessor.java

**Comment by wilkinsona** [comment]
While there's no code dependency on REST Assured, it's conceptually specific to REST Assured as MockMvc has no need for it. Every feature has a cost in terms of what users need to understand. I don't want people who are using MockMvc to have to pay that cost when they'll gain nothing from it. I think this is a case where code duplication is a better alternative to adding functionality to a core module.
