### ISSUE TITLE
Support for the OpenAPI Spec

### ISSUE THREAD

**Issue by eruiz** [spring-projects/spring-restdocs#227]
It would be great if Spring REST Docs could include support for the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification).

As said in the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification):

> The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which allows both humans and _**computers to discover and understand the capabilities of the service**_ without access to source code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can understand and interact with the remote service with a minimal amount of implementation logic. Similar to what interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service.

**Comment by wilkinsona** [comment]
Duplicates #213
