### ISSUE TITLE
Move Asciidoctor Code Block Switch extension into a separate repository

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#229]
It's generally useful so it should be published separately

**Comment by dsyer** [comment]
We already copied the code to Spring Cloud: https://github.com/spring-cloud/spring-cloud-contract/commit/699c7d2121353ba486ad43704f7fe917a9c1bc5a#diff-48fabae9c2e321b2ab4d99057d5dc32eR40. It would be neat to revert that and just pull in a generic extension.
