### ISSUE TITLE
json response is empty for an error in the generated snippets  

### ISSUE THREAD

**Issue by ngandriau** [spring-projects/spring-restdocs#23]
Hi 
I just started "playing" with `spring-restdocs` and really love it.
I have a small `springboot` project with one `@RestController`.
So far, I have integrated `spring-restdocs` successfully to document a successful `GET` and `POST`.
But I have an incomplete result when I try do document the `GET` producing an error.

I have defined a particular ex to produce a `NOT_FOUND` response:
```
@ResponseStatus(value = NOT_FOUND)   
class NoEmailFoundException extends RuntimeException{
```
Then the `GET` method of my controller throws that exception: 
```
@RequestMapping(value="/status/{id}", method = GET)
public EmailStatus getEmailStatus(
            @PathVariable(value = "id") final String id) throws Exception {
        
       Email email =  findEmail(id);

        if(email == null){
            throw new NoEmailFoundException("Could not find email with ID '" + id + "'.");
        }
...
```

When I call this resource from the live application, I get the following response:
```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 22 Feb 2015 22:33:21 GMT

{
  "timestamp" : 1424644401861,
  "status" : 404,
  "error" : "Not Found",
  "exception" : "com....NoEmailFoundException",
  "message" : "Could not find email with ID '123'.",
  "path" : "/email/outbound/status/123"
}⏎ 
```
Which is perfect.

Then I tried to generate the response snippet for this situation.
I took inspiration from the sample: `com.example.notes.ApiDocumentation#errorExample`
```
@Test
public void errorEmailNotFound() throws Exception {
        this.mockMvc.perform(get("/email/outbound/status/123").accept(APPLICATION_JSON))
                .andDo(print())
                .andDo(document("error-email-notfound-example"));
    }
```

The test pass, but the generated snippet does not contain the json response that I get on the live environment:
```
[source,http]
----
HTTP/1.1 404 Not Found


----
```

Am I missing something?
Thanks for your help and for this project.

**Comment by wilkinsona** [comment]
It's a limitation of Spring MVC Test.

Spring Boot registers an error page with the embedded container. When an error response is being returned, the container forwards the request to the error page which causes Spring Boot's `BasicErrorController` to be driven. This produces the JSON output describing the failure. Spring MVC Test is unaware of error pages (and also doesn't fully support the forwarding of requests) so you're left with a "plain" error response.

If you look again at `ApiDocumentation.errorExample` you'll see that I've actually called Spring Boot's error controller directly (`/error`) and have configured the necessary request attributes to mimic the forwarding of an error:

```
this.mockMvc.perform(get("/error")
		.requestAttr(RequestDispatcher.ERROR_STATUS_CODE, 400)
		.requestAttr(RequestDispatcher.ERROR_REQUEST_URI, "/notes")
		.requestAttr(RequestDispatcher.ERROR_MESSAGE,
				"The tag 'http://localhost:8080/tags/123' does not exist"))
```

**Comment by ngandriau** [comment]
Thanks for the explanation Andy
I was not sure why the `ApiDocumentation.errorExample` was different.
This limitation is not a blocker for the documentation. 
I need to learn more about the Spring MVC test.

Any idea when spring-restdocs will be released?

Thanks again

**Comment by wilkinsona** [comment]
No firm plans for a release just yet. That said, I'd like to get a first milestone out in the not too distant future. There are three issues (and possibly a fourth) still to tackle.
