### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by kamaydeo** [spring-projects/spring-restdocs#231]
I have controller methods returning CompletableFuture and mockMvc tests work using asyncDispatch. However, they don't work with spring-restdocs-mockmvc. am I missing anything or is this not supported yet?

Controller code snippet -- 
```java
@GetJson("/{id}")
public CompletableFuture<AssetDto> findById(@PathVariable("id") String id) throws Throwable{
        return CompletableFuture.supplyAsync(() -> assetRepository.findById(id));
}
```
Test code snippet -- 
```groovy
when:
          MvcResult result = mockMvc.perform(get("/assets/1234")).andReturn()
then:
          mockMvc
                .perform(asyncDispatch(result))
                .andExpect(status().isOk())
```

**Comment by wilkinsona** [comment]
As far as I know it should work. I know that `DeferredResult` does. Can you please share a complete example that shows it not working?

**Comment by wilkinsona** [comment]
Closing due to the requested information not being provided. @kamaydeo if you still believe this is a problem, can you please provide a complete example that shows it not working and I'll reopen the issue.
