### ISSUE TITLE
Future plans of REST Assured

### ISSUE THREAD

**Issue by johanhaleby** [spring-projects/spring-restdocs#233]
Jayway is no longer sponsoring the REST Assured project and I'm no longer working there and haven't been so for 9 months. I've made a huge personal investment in REST Assured and I find it a bit unfair that Jayway gets (most) credits for it now that I'm no longer working there and Jayway doesn't contribute to the project. My future plan is to move REST Assured to its own organization on Github and possibly change the package  structure from `com.jayway.restassured` to `io.restassured` in the 3.0 release. But my main concern/objection to this is spring-restdocs. So before I do anything like things I'd like to discuss it with you. I truly understand that this is frustrating for spring-restdocs and I might even consider not changing the package structure if it messes things up too much for you. But if this were to happen, is there anything I can do to make this transition easier for spring-restdocs? Would it perhaps be possible to have two different versions of spring rest-docs for rest assured (perhaps sharing some common code)? Or would it be better if I hurry up and release 3.0 of REST Assured before you've released 1.1.0 final of spring-restdocs so that you could depend on 3.0 instead?

Regards,
/Johan

**Comment by wilkinsona** [comment]
Hi, Johan. Thanks for considering REST Docs in your plans for REST Assured, but please do what's best for you and for REST Assured.

From a REST Docs perspective, I think we can continue on the current course. REST Docs 1.1 will support REST Assured 2.x. We can then add support for REST Assured 3.x as and when it's available. With Spring Framework 5.0 appearing early next year, and a first milestone planned for this summer, REST Docs 2.0 is already in the back of my mind. It'll require Java 8 and Spring Framework 5. It could also require REST Assured 3.0.

That said, Spring Framework 5, and therefore REST Docs 2.0, won't reach a final release till next year so there's room in the schedule for a REST Docs 1.2 release. To that end, a REST Assured 3.0 release with different package names and Maven coordinates would be my preference as it would make it very straightforward to add support for 3.0 while also retaining the existing support for 2.x.

FWIW, I don't think you should hurry up and release 3.0 of REST Assured. I'd hate you to rush the rare opportunities offered by a new major release just for REST Docs' benefit. Instead, REST Docs 1.2 or 2.0 can pick up REST Assured 3.0 as and when it's ready. Support for REST Assured 3.0 would be enough to warrant a new minor release of REST Docs so there needn't even be much delay between REST Assured 3.0 and a release of REST Docs that supports it.

**Comment by johanhaleby** [comment]
Thanks for your comments @wilkinsona, I really appreciate it. I think I'm about ready to release 3.0 pretty soon though. It might not seem very serious but rest-assured has historically not have a fixed road map. I just develop as much as I can with the time I've got and with features/ideas that I get from users or from myself. What I want to say is that I don't have anything huge planned for the 3.0 release except for the potential package name change and removal of deprecated methods.

Would it actually make things worse for you if I release 3.0 in a not so distant future? (Let's say within two weeks)? I don't mind postponing it if that would make things easier. I know this is hard to answer but do you have any idea when you expect rest docs 1.1 do be released?

**Comment by wilkinsona** [comment]
REST Docs 1.1 is imminent. I had hoped to finished it off last week but it didn't happen. It's Spring IO in Barcelona this coming week so it's likely it'll be next week at the earliest now. It'll definitely be before Spring Boot 1.4 which we're aiming to release some time in June.

A REST Assured 3.0 release in the not too distant future won't be a problem. If adoption's strong among would be REST Docs users a 1.2 release that supports it could happen sooner rather than later. If it appears before REST Docs 1.1 is released and I have time to add support for it, then that option remains open. One thing that would help is access to 3.0 snapshots.

**Comment by wilkinsona** [comment]
I've opened #262 to add support for REST Assured 3.0
