### ISSUE TITLE
Improve PlaceHolderResolver extendability 

### ISSUE THREAD

**Issue by kakawait** [spring-projects/spring-restdocs#235]
_Spring Restdocs_ provides a great feature `alwaysDo` with parameterized output directories like `{method-name}`.

If I'm using `{method-name}` _Spring Restdocs_ will simply apply following transformation on testing method name:

```
camelCaseToSeparator(context.getTestMethodName(), "-")
```

However in our team we are using a specific naming convention inspired from [Roy Osherove's naming convention](http://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html) 

```
UnitOfWork_StateUnderTest_ExpectedBehavior
```

example

```
public void sum_SimpleValues_Calculated()
```

Thus when using `{method-name}` with such convention I will obtain following result: `sum_-simple-values_-calculated` that does not looks great (from my point of view).

**I don't ask you to enhance `{method-name}` to fit my convention, obviously!** But when I tried to extend/override `PlaceHolderResolver`... It was not so easy.

`RestDocumentationMockMvcConfigurer` offers an way to configure `WriterResolver` (which contains `PlaceHolderResolver`) but there is no simple way to pass `RestDocumentationContext` to my custom `PlaceHolderResolver`. As @wilkinsona describes here https://github.com/spring-projects/spring-restdocs/issues/116#issuecomment-138851849 

```
MockMvc mockMvc = MockMvcBuilders
        .webAppContextSetup(this.context)
        .apply(documentationConfiguration(this.restDocumentation).writerResolver(
                new StandardWriterResolver(new PlaceholderResolver() {
                    @Override
                    public String resolvePlaceholder(String placeholderName) {
                        // …
                    }

                }))).build();
```

I will be hard to resolve something without `RestDocumentationContext`.

--- 

Actually to succeed I had to create following `interface`

```
interface ContextAwarePlaceHolderResolver extends PropertyPlaceholderHelper.PlaceholderResolver {
    void setContext(RestDocumentationContext context);
}
```

and following `WriterResolver` (`StandardWriterResolver` is `final` I need to delegate)

```
class ContextInjecterStandardWriterResolver implements WriterResolver {
    private final WriterResolver delegate;

    private final ContextAwarePlaceHolderResolver placeholderResolver;

    ContextInjecterStandardWriterResolver(ContextAwarePlaceHolderResolver placeholderResolver) {
        this.placeholderResolver = placeholderResolver;
        delegate = new StandardWriterResolver(placeholderResolver);
    }

    @Override
    public Writer resolve(String operationName, String snippetName, RestDocumentationContext context)
            throws IOException {
        placeholderResolver.setContext(context);
        return delegate.resolve(operationName, snippetName, context);
    }

    @Override
    public void setEncoding(String encoding) {
        delegate.setEncoding(encoding);
    }
}
```

To finally creates an instance of `ContextAwarePlaceHolderResolver` where `RestDocumentationContext` can be retrieved

--- 

To conclude it will be cool to have an easy way to extend `PlaceHolderResolver` with access on `RestDocumentationContext` instance.

**Comment by wilkinsona** [comment]
@kakawait Thanks for opening the issue after our chat on Gitter. Btw, I've created a new room specifically for REST Docs: https://gitter.im/spring-projects/spring-restdocs

I've prototyped one approach [here](https://github.com/wilkinsona/spring-restdocs/tree/gh-235). It looks like this in use:

```java
documentationConfiguration(this.restDocumentation).writerResolver(
		new StandardWriterResolver(new PlaceholderResolverFactory() {

			@Override
			public PlaceholderResolver create(RestDocumentationContext context) {
				return new CustomPlaceholderResolver(context);
			}

		}, "UTF-8", TemplateFormats.asciidoctor()));
```

Feedback welcome

**Comment by kakawait** [comment]
@wilkinsona I do not test your branch yet but from piece of code you just posted it looks perfect! Simple and effective.

**Comment by wilkinsona** [comment]
Thanks for looking so quickly. I'll get this into 1.1.
