### ISSUE TITLE
Provide support for documenting required and optional elements in requests and responses

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#24]
The samples currently use manually written tables to document the structure of requests and responses. This is error prone as there's nothing to verify the contents of the table against the service. We should provide an API, possibly similar to the one used for links, that produces the table and verifies its contents against the service that's being documented.

**Comment by andreasevers** [comment]
I've started implementation of this in a fork.
Can I create a pull request with my current implementation for review?
I've reused a lot of the logic for the links.

**Comment by wilkinsona** [comment]
Sounds great. Yes, please.

**Comment by andreasevers** [comment]
Possible example of the implementation in the pull request would look like:

```
mockMvc.perform(MockMvcRequestBuilders.post("/cat").header("Content-Type", "application/json").content("{\"name\":\"garfield\", \"whiskers\":150}"))
			.andDo(document("index")
					.withRequestFields(
							fieldWithName("name")
								.description("The name of the cat")
								.type(String.class)
								.constraints("Should be a cat-like name. 250 chars max")
								.required(true),
							fieldWithName("whiskers")
								.description("The amount of whiskers the cat has")
								.type(Integer.class)
								.constraints("Should be more than 10 and less than 1000")
								.required(false)));
```

**Comment by RobWin** [comment]
How about using something like RAML or Swagger.yaml to document your API and check you tests against the specification?
See this blog post for an example.

http://www.insaneprogramming.be/blog/2014/08/18/rest-documentation-specification/

**Comment by andreasevers** [comment]
Great, thanks Andrew!

**Comment by wilkinsona** [comment]
@andreasevers Thanks for the PR that helped to get the ball rolling

**Comment by juicegit** [comment]
This looks to have been removed. Can someone please confirm? I set a request field as optional and regardless, I only get 3 attributes for each field (path, description, and type). It looks like this code was removed in a subsequent commit.

**Comment by wilkinsona** [comment]
A field being optional only governs whether or not the test fails if it is documented but missing from the payload. For now at least, you should use the description if you want to document a field's optionality.

**Comment by juicegit** [comment]
@wilkinsona thanks for the reply. That is what I have done "for now" :). Are there plans to support that as a discrete column in the output? I realize that it might be the exception case.

**Comment by wilkinsona** [comment]
@juicegit Take a look at #70. It's (somewhat) related to this.
