### ISSUE TITLE
Enhance reuse of snippets even more to reuse snippets when building snippets

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#242]
I like the new 1.1 functionality to reuse snippets.
Unfortunately I cannot add the response fields of `ResponseFieldsSnippet` when building a new `ResponseFieldsSnippet`.

E.g currently we can use:

```
responseFields(..).add(FieldDescriptor... additionalDescriptors)
responseFields(..).addWithPrefix(String pathPrefix, FieldDescriptor... additionalDescriptors)
```

It would be nice to do something like:

```
responseFields(..).add(ResponseFieldsSnippet snippet)
responseFields(..).addWithPrefix(String pathPrefix, ResponseFieldsSnippet snippet)
```

That way I could easily reuse snippets inside snippets.

**Comment by wilkinsona** [comment]
I considered this when I first implemented the support for reuse and again as part of #224. I'm still not convinced that it's a good idea.

There is more to a snippet than its descriptors, for example a snippet can also have attributes associated with it. Copying attributes from one snippet to another doesn't make sense to me so I think a `responseFields(…).and(ResponseFieldsSnippet)` method is likely to confuse people. It's not clear that it's only the descriptors that are being added. I think the current methods that take one or more descriptors express the intent of adding descriptors and only descriptors much more clearly.

**Comment by marceloverdijk** [comment]
I don't know if it will confuse people to be honest.
The issue I have now is that I cannot optimally reused `ResponseFieldsSnipper` or `FieldDescriptor[]`.
But maybe I should evaluate how I'm doing this right now and discuss it on gitter.

**Comment by wilkinsona** [comment]
No need to move to Gitter. We've got this issue now, so we might as well use it.

I'm certainly happy to be convinced otherwise. Typically, I use a field for the `FieldDescriptor[]` and then refer to that field in the individual tests. For example:

#### Field
```java
private final FieldDescriptor[] weatherFields = new FieldDescriptor[] {
		fieldWithPath("weatherId").description("ID of the weather conditions"),
		fieldWithPath("weatherIcon").description("ID of the weather icon"),
		fieldWithPath("temperature").description("Temperature in degrees celsius"),
		fieldWithPath("timestamp").description("ISO-8601 timestamp of the weather data")};
```

#239 ### First test
```
this.mockMvc.perform(get("/api/weather/now/{country}/{city}", "spain", "barcelona"))
		.andExpect(status().isOk())
		.andDo(document("weather",
				pathParameters(
						parameterWithName("country").description("Name of the country"),
						parameterWithName("city").description("Name of the city")),
				responseFields(
						fieldWithPath("name").description("Name of the weather data"))
						.and(this.weatherFields)));
```

#### Second test
```
this.mockMvc.perform(get("/api/weather/weekly/{country}/{city}", "spain", "barcelona", "bar"))
		.andExpect(status().isOk())
		.andDo(document("weather-forecast",
				pathParameters(
						parameterWithName("country").description("Name of the country"),
						parameterWithName("city").description("Name of the city"),
						parameterWithName("foo").description("Name of the city")),
				responseFields(
						fieldWithPath("name").description("Name of the weather forecast"),
						fieldWithPath("entries").description("Array of weather data"))
						.andWithPrefix("entries[].", this.weatherFields)));
```

**Comment by marceloverdijk** [comment]
Yes I use above pattern and it works quite well. I even use it for e.g. adding the pagination response fields as well like:

```
    responseFields(
                fieldWithPath("elements").type(ARRAY).description("An array of buildings."))
                .andWithPrefix("elements[].", buildingResponseFields())
                .and(paginationResponseFields()));
```

My problem arose when in my buildResponseFields I wanted to reuse some specific fields that are also contained in other resources. To be more specific:

```
public static FieldDescriptor[] buildingResponseFields() {
    return new FieldDescriptor[]{
            fieldWithPath("id").description("The unique id of the building."),
            fieldWithPath("name").description("The name of the building."),
            fieldWithPath("type").description("The type of the building."),
            fieldWithPath("location").description("The location of the building."),
            // reusable
            fieldWithPath("location.place_name").description("The place name of the location of the building."),
            fieldWithPath("location.country").description("The country of the location of the building."),
            fieldWithPath("location.country.alpha2_code").description("The unique alpha2 code of the country of the location of the building."),
            fieldWithPath("location.country.alpha3_code").description("The unique alpha3 code of the country of the location of the building."),
            fieldWithPath("location.country.name").description("The name of the country of the location of the building."),
            fieldWithPath("location.country.continent").description("The continent of the location of the building."),
            fieldWithPath("location.country.continent.code").description("The unique code of the continent of the location of the building."),
            fieldWithPath("location.country.continent.name").description("The name of the continent of the location of the building."),
            fieldWithPath("location.latitude").description("The latitude of the location of the building."),
            fieldWithPath("location.longitude").description("The longitude of the location of the building."))
            // done reusable
            // other building properties
    };
}
```

So I wanted to remove these `location` fields, or better re-use them.
Note that the location nor the country or continent are resources by them self.

As I didn't want to plumber with concatenating arrays (still an option though) I read about reusing snippets and basically I was hoping to do something like:

responseFields()
  .and(fieldWithPath("id").description("The unique id of the building."))
  .and(fieldWithPath("name").description("The name of the building."))
  .and(fieldWithPath("type").description("The type of the building."))
  .and(fieldWithPath("location").description("The location of the building."))
  .andWithPrefix("location.", locationResponseFields())
  .and(paginationResponseFields()));

And when setting up the `locationResponseFields` I would like to re-use the country fields as country is sometimes also used directly in other entities.

For this I was thinking about changing everything from `FieldDescriptor[]` to `ResponseFieldSnippet` 

Maybe I should re-think about simply concatenating the `FieldDescriptor[]`...

**Comment by wilkinsona** [comment]
Perhaps it would help if `andWithPrefix` and `and` were overloaded to also accept a `List`? That would allow you to use `addAll` which is quite a bit more pleasant than concatenating arrays.

Something a bit like this:

```
public static List<FieldDescriptor> locationFields() {
	return Arrays.asList(
			fieldWithPath("location.place_name")
					.description("The place name of the location of the building."),
			fieldWithPath("location.country")
					.description("The country of the location of the building."),
			fieldWithPath("location.country.alpha2_code").description(
					"The unique alpha2 code of the country of the location of the building."),
			fieldWithPath("location.country.alpha3_code").description(
					"The unique alpha3 code of the country of the location of the building."),
			fieldWithPath("location.country.name").description(
					"The name of the country of the location of the building."),
			fieldWithPath("location.country.continent")
					.description("The continent of the location of the building."),
			fieldWithPath("location.country.continent.code").description(
					"The unique code of the continent of the location of the building."),
			fieldWithPath("location.country.continent.name").description(
					"The name of the continent of the location of the building."),
			fieldWithPath("location.latitude")
					.description("The latitude of the location of the building."),
			fieldWithPath("location.longitude")
					.description("The longitude of the location of the building."));
}

public static List<FieldDescriptor> buildingResponseFields() {
	List<FieldDescriptor> buildingResponseFields = new ArrayList<>();
	buildingResponseFields.addAll(Arrays.asList(
			fieldWithPath("id").description("The unique id of the building."),
			fieldWithPath("name").description("The name of the building."),
			fieldWithPath("type").description("The type of the building."),
			fieldWithPath("location").description("The location of the building.")));
	buildingResponseFields.addAll(locationFields());
	return buildingResponseFields;
}
```

**Comment by marceloverdijk** [comment]
@wilkinsona Yes I think that would help a lot!

**Comment by marceloverdijk** [comment]
@wilkinsona it would be useful to use `AbstractFieldsSnippet.applyPathPrefix` outside of `AbstractFieldsSnippet`. Would it be possible to move this some kind of utility class with static access?

That was I could do something like:

```
buildingResponseFields.addAll(applyPathPrefix(locationFields()));
```

And would I be able to remove the `location.` prefix from `locationFields` as sometime I have something like e.g. `primary_location` and `alternate_location`.
