### ISSUE TITLE
Missing documentation/explanation of samples

### ISSUE THREAD

**Issue by jarl-dk** [spring-projects/spring-restdocs#254]
I am trying out the `rest-notes-grails` sample project.

I am running
```
gradle build
```
Which generates
```
build/asciidoc/index.html
```

I assume that this file is the entry point for the documentation. However it contains a lof of "dead links" adoc references to files that does not exist. I don't know which of the below is most likely:

1. I am doing something wrong, in which case I don't know what.
1. The example is not yet mature enough to actually show the complete process to generate the missing files.
1. There is a "bug" in the sense that the example is believed to show a complete workflow, but it aparently fails... (Maybe someone failed to commit some files, what do I know).

In any of the above case, it would be nice to have an explanation in the README.md for that example.

**Comment by wilkinsona** [comment]
There's certainly some room for improvement in the README. That said, `gradle build` should have worked as the task that generates the documentation is configured to depend upon the integration tests which the linked to adoc files.

Running `gradle clean build` against the `v1.1.0.RELEASE` tag:

```
gradle clean build
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.12/userguide/gradle_daemon.html.
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:clean
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:cleanTempDirs
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:compileIntegrationTestJava UP-TO-DATE
:compileIntegrationTestGroovy
:processIntegrationTestResources UP-TO-DATE
:integrationTestClasses
:integrationTest
:mergeTestReports
:asciidoctor
:buildProperties
:jar
:findMainClass
:startScripts
:distTar
:distZip
:war
:bootRepackage:assemble
:check
:build

BUILD SUCCESSFUL

Total time: 29.241 secs
```

As you can see, the `asciidoctor` task has run after the `integrationTest` task. The resulting `build/asciidoc/index.html` doesn't have any dead links.

Can you please provide some more information about what you did and the output that was produced?

**Comment by jlstrater** [comment]
Thanks. I can add some instructions in the README.

**Comment by wilkinsona** [comment]
Yes please, @jlstrater. I'm not totally sure of the idiomatic way to generate the documentation. Do you typically run Gradle directly or via the Grails CLI?
