### ISSUE TITLE
Question: How to refer path variables in generated Snippets?

### ISSUE THREAD

**Issue by cheppsn** [spring-projects/spring-restdocs#257]
The [Spring REST Docs Documentation](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-path-parameters) tells me that I can document path parameters:

> To make the path parameters available for documentation, the request must be built using one of the methods on RestDocumentationRequestBuilders rather than MockMvcRequestBuilders.

If I understand the feature correctly, I should be able to see the `{pathVariable}` inside the generated snippets (at least in the `http-request` snippet). However, no matter whether I use the methods on `RestDocumentationRequestBuilders` or `MockMvcRequestBuilders` the variable is always replaced with the provided value for the performed request (no surprise here, since RestDocumentationRequestBuilders just delegates to MockMvcRequestBuilders).

So, if I have something like

    this.mockMvc
    .perform(RestDocumentationRequestBuilders.get(prefix("/users/{userId}"), "3dbe481f"))
    .andDo(this.docHandler.document(
        pathParameters(parameterWithName("userId").description("..."))));

I get a request snippet and a path variable table:

    GET .../users/3dbe481f HTTP/1.1

Parameter|Description
------------ | -------------
userId|id of user to query

With this information, I can not make the user realize that the documented `userId` variable corresponds to the value `3dbe481f` in the request snippet unless I document the request template explicitly by hand (e.g. ` GET .../users/{userId}` somewhere else in the documentation). This is especially bad, if there are multiple path vars.

Is this the recommended best practice, or is there something broken or did I miss something?

**Comment by cheppsn** [comment]
Nevermind, I just realized that the `request parameter` table caption contains the path with the variables.

**Comment by nailgilaziev** [comment]
Sorry, can you explain more detailed how you solve this issue? 
I have a same problem, I do not want manually handwrite path with pathParams like this
`GET /entities/{entityId}/catalogs/{catalogId}/items/{itemId}`
because I already writer it in tests. but inside http-request I get this:
`GET /entities/1/catalogs/1/items/1`

**Comment by nailgilaziev** [comment]
In other words how to generate a snipped with string value from test code:
`mockMvc.perform(RestDocumentationRequestBuilders.get("/entities/{entityId}/catalogs/{catalogId}/items/{itemId}",1,1,1))`
