### ISSUE TITLE
Line Breaks in cURL and HTTPie Snippets

### ISSUE THREAD

**Issue by psamsotha** [spring-projects/spring-restdocs#260]
It's pretty common to see cURL commands written with line breaks. For example

``` bash
$ curl 'http://localhost/foo' -i -X POST \
   -H 'X-Header-One: ONE' \
   -H 'X-Header-Two: TWO' \
   -d 'a=aplha&b=bravo'
```

It would be nice to have support for this, especially for longer snippets.

**Comment by wilkinsona** [comment]
Nice idea. Thanks for the suggestion.
