### ISSUE TITLE
Support arrays of mixed types

### ISSUE THREAD

**Issue by mrcritical** [spring-projects/spring-restdocs#288]
We often need to create API's that return arrays of mixed types. They all inherit from a parent type, but they have their own fields. I'm not sure how to document these with Rest Docs.

We could manually add the snippets and only document the common fields via Rest Docs. But that greatly reduces the effectiveness of using tests to perform the validation of the API in addition to the documentation of the fields. Any suggestions?

For example:

```
{
    "items": [
       {
          "type": "ROOM_RESERVATION",
          "confirmationNumber": "111111",
          "startDate": "2017-10-01",
          "endDate": "2017-10-08",
          "guests": [
             ...
          ],
          ...
       },
       {
          "type": "NOTE",
          "location": "Room",
          "description": "Take a nap",
          "startDateTime": "2017-10-01T14:00:00",
          "endDateTime": "2017-10-01T16:00:00",
          "guests": [
             ...
          ],
          ...
       },
       ...
    ]
}
```

**Comment by wilkinsona** [comment]
When an API is proving difficult to document, it's often an indication that it's also difficult to consume. In my opinion, that's the case here. Rather than having `type` be a field of each item in the array, I would, if possible, restructure the JSON so that the type becomes a key. Something like this:

```
{
    "items": {
        "roomReservations": [
            {
                "confirmationNumber": "111111",
                "startDate": "2017-10-01",
                "endDate": "2017-10-08",
                "guests": [
                    …
                ],
                …
            },
            …
        ],
        "notes": [
            {
                "location": "Room",
                "description": "Take a nap",
                "startDateTime": "2017-10-01T14:00:00"
                "endDateTime": "2017-10-01T16:00:00",
                "guests": [
                    …
                ],
                …
            },
            …
        ]
    }
}

If a new item type is introduced, this allows a client ignore the whole array of objects, rather than having to process the array defensively looking at the type of each object to determine how to deserialise it.

If changing the design of the API isn't possible then, unfortunately, there's currently no out-of-the-box support for documenting arrays of different types. The closest that you can get is to document all of the possible fields of the objects in the `items` array and mark as optional the fields that are not common to every type. If you want to go one step better than that, you could implement your own snippet using `AbstractFieldsSnippet` as inspiration.

I'm not totally against adding support for this to Spring REST Docs, but I am somewhat reluctant to do so as I do think that changing the API is a better solution to the problem. However, I'm sure there are cases where that isn't possible. Have you thought about how you would like REST Docs to allow you to document this? What sort of API did you have in mind for expressing the different possibilities?

**Comment by mrcritical** [comment]
Unfortunately we are designing API's used by mobile services that require the service to provide mixed items that are mixed in among each other in a specific order (not by type) as determined by various business rules. 

I can say that our non-dynamic docs list out the various type of objects to expect in the "fields" section. Then we hyperlink on the type to another location in the spec that outlines the fields for that particular type. So, in terms of Rest Docs the "type" would be "RoomReservation" or "Note". These "types" would have links that point to a snippet that would define "RoomReservation" and individually "Note".

We will probably have to go this route, using static snippets, for now. However it would be nice if we could dynamically create a snippet from a model object instead (or snippets from a list of model objects). We could then modify the response fields template to add a link to type "type". That would link to where the snippet is located in the doc. This way we can have unit tests detect the current type in the array and validate it against the spec.

Perhaps a response field could be like so, which would allow for listing, with links to the `types` document.
```
responseFields(
   fieldWithPath("items")
      .description("")
      .types( // <- Ends up contributing to generation of a `response-types.snippet` and can be used to create anchors
         type("ResortReservation",  // <-- Name of type
            fieldWithPath("type").description(""),
            fieldWithPath("confirmationNumber").description(""),
            ...
        ),
        type("Note",
          fieldWithPath("location").description()
        )
   )
);
```

Just thinking out loud a bit.

We don't use this type of thing any many places. But we have had a lot of success with API's like this when the use case calls for it. It would be nice to be able to leverage live docs with unit test validation like that provided by Rest Docs.

**Comment by wilkinsona** [comment]
Thanks for the additional info. Let's see if we can hash something out to support your use case.

> mixed items that are mixed in among each other in a specific order

Is this order specific enough that being able to refer to a particular element in the array would be sufficient to document each element's fields? For example, if you could use paths like this:

- `items[0].specificToFirstItem`
- `items[1].specificToSecondItem`

**Comment by mrcritical** [comment]
Sadly, no. It is dependent on a number of factors. Items are only discernible by their type. Order fluctuates. There is also no guarantee all types are present. Just that, if the type is present, then it should be validated per the normal field path descriptors.

The end result is an itinerary of instances that are mostly date and, if present, time driven, but other rules come into play besides date/time, especially when multiple instances have the same date. I don't expect the validation to include those rules as this is probably to far beyond the scope of Rest Docs (though it would be handy).

**Comment by wilkinsona** [comment]
Upon further consideration, I don't think that supporting this will add too much complexity for something that appears to be an edge case. Writing a custom snippet to fit your specific needs is the recommended approach at this time.

**Comment by hughwphamill** [comment]
Hi,

I hope it's appropriate to reopen this discussion, per the comment on #882 to continue the discussion here.

It would be good if restdocs could support polymorphic responses in collections based on a discriminator value, this is something that's supported by the Open API Spec and it'd be great if there was a standard way to call this out in Restdocs also

**Comment by wilkinsona** [comment]
Absolutely. This is the right place to discuss.

This project was started due, in part, to philosophical differences with OpenAPI about how APIs should be implemented and documented. Unfortunately, that means that I don't find the argument that Open API supports something to be particularly compelling.

I am still of the opinion that APIs that use polymorphic responses are hard for clients to consume and should be avoided. As such, it's hard to justify adding what I think would be a lot of complexity to REST Docs in order to support something that would hopefully only be of niche benefit. As I said above, I'm not completely opposed to the idea, but something would have to tip the balance by either showing that the complexity involved has been overestimated or the benefit has been under estimated.

**Comment by hughwphamill** [comment]
That's totally fair, and to be honest I love spring restdocs, I use it on every project and evangelise for it in every org I've worked for.

That said I do think there are valid use cases for polymorphic responses in modern restful APIs.  

Consider a use case where we have a collection of Shipping Addresses belonging to a user, which is an array response inside a User object.

If the Address is located in the USA we will have a Zip Code, if it is in the UK we will have a  Post Code, and if it is somewhere else we may have neither.  We can tailor each addresses response fields to be appropriate for the country in which it is located, and include a type discrimination field to help clients determine the subtype of each address (USAddress, UKAddress, Address) or some similar mechanism.

If we are documenting our API in Spring Restdocs then it would be good to have some way of describing all the variant subtypes to the consuming user, to allow them to write their code to consume a user with multiple addresses in different countries.

Of course you can argue that the response could be modified to be more generic, but the merits of that for consuming clients aside, it's possible to do polymorphic collections and it doesn't break the RESTful spec, so it would be good if our preferred documentation technology supported them.
