### ISSUE TITLE
Unresolved directive in <stdin>

### ISSUE THREAD

**Issue by vrochamaia** [spring-projects/spring-restdocs#290]
Hi, on the both adoc files generated in this project, we can see the follwing error: Unresolved directive in <stdin>. This is the same problem which I face now. Do you have any suggestion to how resolve this problem?

**Comment by wilkinsona** [comment]
> on the both adoc files generated in this project

Which files are you referring to?

**Comment by vrochamaia** [comment]
https://github.com/spring-projects/spring-restdocs/tree/master/samples/rest-notes-spring-data-rest/src/main/asciidoc

**Comment by wilkinsona** [comment]
They're references to the snippets that Spring REST Docs generates as part of running the tests. They're unresolvable when you view the file on GitHub as they haven't been generated. If you build the sample locally and view the generated HTML, you'll see that the snippets have been included successfully.

**Comment by vrochamaia** [comment]
Yeah, but in my project I have the snippets in the target folder and the problem is still happing.

**Comment by wilkinsona** [comment]
Then it sounds the include path must be wrong, but I can't tell what it needs to be from what you've told me thus far. If you can provide me with a sample that illustrates the problem I can take a look for you.

**Comment by vrochamaia** [comment]
![asciidoc-example](https://cloud.githubusercontent.com/assets/7724418/17623366/14cd72a6-6076-11e6-9470-877a1a927075.png)

This is the print of my project folders. My pom file is equal of this project.

**Comment by jlstrater** [comment]
It looks like the snippets might be getting generated after the html. Can you provide the entire project or at least the build file and the task(s) you are running?

**Comment by vrochamaia** [comment]
This html file was generated by me after the execution of the tests.

**Comment by wilkinsona** [comment]
Have you configured the `snippets` attribute in Asciidoctor? You need something like this in your `pom.xml`:

```xml
<plugin>
	<groupId>org.asciidoctor</groupId>
	<artifactId>asciidoctor-maven-plugin</artifactId>
	<version>1.5.3</version>
	<executions>
		<execution>
			<id>generate-docs</id>
			<phase>prepare-package</phase>
			<goals>
				<goal>process-asciidoc</goal>
			</goals>
			<configuration>
				<backend>html</backend>
				<doctype>book</doctype>
				<attributes>
					<snippets>${project.build.directory}/generated-snippets</snippets>
				</attributes>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Note the `<attributes>`:

```xml
<attributes>
	<snippets>${project.build.directory}/generated-snippets</snippets>
</attributes>
```

**Comment by vrochamaia** [comment]
Here is the configuration in my pom.xml:
```
<build>
        <finalName>XXXX</finalName>
        <plugins>
             <plugin>
                 <groupId>org.springframework.boot</groupId>
                 <artifactId>spring-boot-maven-plugin</artifactId>
                 <configuration>
                     <executable>true</executable>
                 </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>**/*Documentation.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>1.5.3</version>
                <executions>
                    <execution>
                        <id>generate-docs</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <backend>html</backend>
                            <doctype>book</doctype>
                            <attributes>
                                <snippets>${project.build.directory}/generated-snippets</snippets>
                            </attributes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/static/docs</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}/generated-docs</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by wilkinsona** [comment]
That looks OK. Can you provide a complete project that reproduces the problem? Without one, the best I can do is to make educated guesses.

**Comment by wilkinsona** [comment]
One other thought:

> This html file was generated by me after the execution of the tests.

What command(s) are you running to execute the tests and then generate the HTML?

**Comment by vrochamaia** [comment]
"asciidoctor api-documentation.adoc" on cmd in Windows

**Comment by vrochamaia** [comment]
This command return to me this error:
![snippets-error](https://cloud.githubusercontent.com/assets/7724418/17630035/f7b8f668-6093-11e6-8b85-80db308c4589.png)

**Comment by wilkinsona** [comment]
That's the problem. If you don't use Maven to generate the HTML, then Asciidoctor won't know about the snippets attribute. Running `mvn prepare-package` will run the tests and then get Asciidoctor to generate the HTML too.

**Comment by vrochamaia** [comment]
Yeah, that was the problem, thank you so much!!!! :+1:

**Comment by iggykarpov** [comment]
I see this:
...
What You Need
Unresolved directive in <stdin> - include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

Unresolved directive in <stdin> - include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

Starting with Spring Initializr
...

here:
https://spring.io/guides/gs/testing-web/

Thanks
