### ISSUE TITLE
Document how to use REST Assured on top of MockMvc

### ISSUE THREAD

**Issue by cannehal** [spring-projects/spring-restdocs#293]
Hi
Are you planning support for this hybrid solution?
Best regards

**Comment by wilkinsona** [comment]
No plans for any such support at the moment. What benefit would it bring you? I'm guessing you like the REST Assured API but you don't want to make actual HTTP requests?

I confess that I haven't actually tried it so there's a chance that it might already work. If you've given it a go, I'd be interested to hear how it went.

**Comment by cannehal** [comment]
That is exactly what I would like to achieve. Rest assured is cleaner and integration tests are easier to read but I don't want to make actual http request.

**Comment by wilkinsona** [comment]
I've just tried it and it would appear that there's nothing to do.

You need three dependencies:

- `com.jayway.restassured:spring-mock-mvc`
- `org.springframework.restdocs:spring-restdocs-mockmvc`
- `org.springframework.restdocs:spring-restdocs-restassured`

You then configure a `MockMvc` instance as you normally would with REST Docs and pass it into REST Assured and that's it. The only difference then is that to generate the documentation you use `apply` rather than `filter` which you'd usually use with Rest Assured.

Put together, it looks like this:

```java
package com.example;

import static com.jayway.restassured.module.mockmvc.RestAssuredMockMvc.given;
import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document;
import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.documentationConfiguration;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.restdocs.JUnitRestDocumentation;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import com.jayway.restassured.module.mockmvc.specification.MockMvcRequestSpecification;

@RunWith(SpringRunner.class)
@WebAppConfiguration
@ContextConfiguration(classes = RestAssuredMockMvcExample.class)
public class RestAssuredMockMvcExampleTests {
	
	@Rule
	public JUnitRestDocumentation restDocumentation = new JUnitRestDocumentation(
			"target/generated-snippets");
	
	@Autowired
	private WebApplicationContext context;
	
	private MockMvcRequestSpecification given;
	
	@Before
	public void setUp() {
		this.given = given().mockMvc(MockMvcBuilders.webAppContextSetup(this.context)
				.apply(documentationConfiguration(this.restDocumentation)
						.snippets().withEncoding("UTF-8"))
				.build());
	}

	@Test
	public void example() {
		this.given
			.get("/")
		.then()
			.statusCode(200)
			.apply(document("example"));
	}

}
```

**Comment by wilkinsona** [comment]
I'm in two minds about adding this to the documentation. It'd probably need to go in a new advanced configuration section to avoid over-complicating things.

**Comment by wilkinsona** [comment]
I haven't seen any other demand for this so either the above has proven sufficient or it's not of general interest. Either way, that's convinced me that adding this to the documentation would over-complicate things.
