### ISSUE TITLE
avoid CSP violations

### ISSUE THREAD

**Issue by dominik42** [spring-projects/spring-restdocs#300]
Hi,

HTML documents created with RESTDocs violates against some default Content Security Policy settings:
- Content Security Policy: The page's settings blocked the loading of a resource at self

The content of two stylesheets (GoogleFonts, FontAwesome) are included as internal style. The default settings of some browsers (Firefox, Chrome) prohibit such structures. The page is shown without any colored tables, custom fonts etc. and the console contains the following errors:

Firefox: Content Security Policy: The page's settings blocked the loading of a resource at self
Chrome: Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'"

It seems, that asciidoctor produces that HTML structure so maybe this is an issue for asciidoctor.

**Comment by wilkinsona** [comment]
As you suspected, this is an Asciidoctor issue.
