### ISSUE TITLE
Support of "conditionally required" vs "optional" fields

### ISSUE THREAD

**Issue by HariAlexiev** [spring-projects/spring-restdocs#301]
I was able to make a custom snippet to take advanteges of .optional method of fieldWithPath(), so it will automatically mark in the rest api doc, if the field is optional or required. However, I have some fields that are "conditionally required", in a sence it is only required if some other field is set to something. Is there a way to mark such fields ?

**Comment by wilkinsona** [comment]
You can add attributes (key-value pairs) to a descriptor and then use a custom snippet template to include those attributes in the generated documentation. Please see [the documentation](http://docs.spring.io/spring-restdocs/docs/1.1.2.RELEASE/reference/html5/#documenting-your-api-customizing-including-extra-information) for further details.
