### ISSUE TITLE
Is is possible to document trivial json responses?

### ISSUE THREAD

**Issue by andysworkshop** [spring-projects/spring-restdocs#309]
Simple quoted strings are valid json. For example `"OK"` and `"STARTED"` are both valid as REST call return values. Is there a way to document these types of response?

**Comment by wilkinsona** [comment]
If you're serving `application/json` then, [strictly speaking](http://www.ietf.org/rfc/rfc4627.txt), just a string isn't valid. REST Docs doesn't necessarily care about that though.

Given that the response is just a String, what support do you want from REST Docs to document it? What sort of snippet would you like it to generate? Typically in this sort of situation, I find it often easiest to use standard MockMvc response matchers to verify the response and to just write the appropriate documentation by hand in your `.adoc` file.

**Comment by andysworkshop** [comment]
RFC-4627 was superceded by RFC-7159 a few years ago and simple values are now permitted, several examples of which are given at the end of [section 13](https://tools.ietf.org/html/rfc7159#section-13).

I was used to being able to both assert and document json output in one step and had hoped to be able to do the same with simple return values. Happy to to write it by hand in the `.adoc` though if the verdict is that this is not worth doing.

**Comment by wilkinsona** [comment]
> RFC-4627 was superceded by RFC-7159 a few years ago and simple values are now permitted, several examples of which are given at the end of section 13.

Thank you

> I was used to being able to both assert and document json output in one step and had hoped to be able to do the same with simple return values

It should be pretty straightforward to write your own snippet for this, particularly if you subclass `TemplatedSnippet`. For example, you could have something like a `ResponseContentSnippet` that asserts that the snippet content exactly matches something, or matches one of a number of options. It could then also generate a snippet that you can include in your `.adoc`. It's not clear to me what format that snippet would take yet. Did you have anything in mind?

Perhaps you could prototype something based on your requirements? If it's looks to be generally useful then it would be a good candidate for inclusion if you were happy to contribute it.

**Comment by wilkinsona** [comment]
This seems to have fizzled out. Closing.
