### ISSUE TITLE
Provide a mechanism to anonymize urls in link objects

### ISSUE THREAD

**Issue by drdamour** [spring-projects/spring-restdocs#31]
during the web session i watched on youtube after it was made so clear that documenting URIs is evil (totally agree) i was dismayed to see the urls in the the links were not anonymized.

I always change my urls to something like
http://example.com/path/to/the/thing
etc.  Having the real URLs in examples is just asking people to treat you as level 2

**Comment by wilkinsona** [comment]
I've considered this in the past but never convinced myself that it was worth the effort – Link URIs will be available via cURL (or whatever) so clients can always shoot themselves in the foot if they really want to. That said, I can certainly see how it would be an extra deterrent that might be enough to make some people think twice and do the right thing.
