### ISSUE TITLE
Add support to mask links not documented

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-restdocs#315]
When using `relaxedLinks(…)` to only selectively document links in the payload, it would be cool if there was an easy way to only show the links documented in the payload. I wouldn't mind having to hand the `LinksSnippet` to a method similar to `Preprocessors.mask(…)` so that the implementation has an easy way to figure out which links to actually mask.

``` java
LinksSnippet snippet = relaxedLinks(linkWithRel("foo").description(…));
```

``` javascript
{ _links : {
  foo : { … },
  … <- no other links shown
}
```

I guess the same can be helpful for `relaxedFields(…)`

**Comment by wilkinsona** [comment]
The links snippet intentionally has no influence over any snippets that document the response payload so an alternative approach will be required.

It sounds like what you actually want is to remove certain links from the response before you document it. That would remove it them from the `http-response.adoc` snippet and remove the need to use relaxed links when producing the links snippet. To do so, you'd use `ContentModifyingOperationPreprocessor` with a custom `ContentModifier` implementation.

Have I understood your goal correctly? Does the above suit your needs?

**Comment by wilkinsona** [comment]
Closing due to lack of response. Modifying the response's content prior to documenting it is the recommended approach.
