### ISSUE TITLE
Support for generating a snippet that contains a portion of a request or response body

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#319]
Building on #318, it should also be possible to document a portion of a request or response body. This could reuse the snippet implemented in #318 with a strategy interface for extracting the portion of the request or response body that should be documented. An implementation of that interface could be provided that uses the same path syntax as the request and response field snippets to identify that portion of the body.

**Comment by wwadge** [comment]
As another use case, it's also currently difficult to extract the just the HTTP method (POST, GET, ...) as well as the unexpanded path /foo/{bar}/.... except in the path-parameters snippet. This makes it difficult to document like this:
```
POST /api/users/{userId}/foo

{ ... request body ....}
 ```

**Comment by wilkinsona** [comment]
@wwadge Thanks for the suggestion, but I don't see accessing the HTTP method or unexpanded path as a use case for what's proposed in this issue. #299 is for documenting the URI (although it's not something that I'm particularly keen on).
