### ISSUE TITLE
Request Parameters doubled

### ISSUE THREAD

**Issue by JohannesFluegel** [spring-projects/spring-restdocs#321]
I use Spring REST Docs 1.1.1.RELEASE.

My url contains request parameters as described in
[Spring REST Docs documentation: Request parameters](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-request-parameters):

`this.mockMvc.perform(get("/devices?page=2&per_page=100")).andDo(document("document"));`

http-request.adoc contains

`GET /devices?page=2&per_page=100&page=2&per_page=100 HTTP/1.1`

The request parameters are doubled.

**Comment by wilkinsona** [comment]
Duplicates #286

**Comment by wilkinsona** [comment]
I suspect that's because `param=change-me` has already made it into the `Map` returned by `request.getParameters()`. What happens if you update the parameters map too?

**Comment by JohannesFluegel** [comment]
With
```
@Override
public OperationRequest preprocess(OperationRequest request) {
	request.getParameters().clear();
	return new OperationRequestFactory().create(
	...
```
it works fine.
