### ISSUE TITLE
Can we combine all service related snippets into single snippet using spring rest docs

### ISSUE THREAD

**Issue by gsambasiva** [spring-projects/spring-restdocs#322]

**Comment by wilkinsona** [comment]
Sorry, I'm not sure that I've understood your question. Can you please describe what you're trying to achieve?

**Comment by gsambasiva** [comment]
I  have written a test method for POST service of Inserting USER like below

@RunWith(SpringRunner.class)
@SpringBootTest(classes = RestDocsApplication.class)
@AutoConfigureRestDocs(outputDir = "target/generated-snippets")
@AutoConfigureMockMvc
@WebAppConfiguration
public class UserControllerDocumentation {
    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private MockMvc mockMvc;
    
    @Autowired 
    private WebApplicationContext webApplicationContext; 
    private void insertUser(User user) throws Exception {
                this.mockMvc.perform(post("/api/v1/users")
                .accept(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(user))
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andDo("insertUser");
     }
}

After running this test , it is generating below default snippets under "**insertUser**" folder 
curl-request.adoc , http-request.adoc , http-response.adoc,httpie-request.adoc.

I want a cobined result for all those 4 default snippets under one file.
Is there any way to achieve this , Please suggest.

**Comment by wilkinsona** [comment]
Thanks. Why do you want to do that? What would you gain from them being in one file?

**Comment by gsambasiva** [comment]
I have so many services to write documentation , and I am trying to include all those generated snippets into one single index.adoc file manually , so I need to include so many generated  snippets manually into index.adoc file for generating main documentation. 
It is giving extra work for me.

Instead of that I want to include one user main snippet i.e is having all USER service related information.
Similarly for other services , I can include only one main snippet into main index.adoc file.

**Comment by wilkinsona** [comment]
Ok, I understand now. Thanks again.

There's no way to do this at the moment. I [prototyped something](https://github.com/wilkinsona/spring-restdocs/commit/6657af0d590be2673f05d7ecd8f1a91244751edc) a while ago that sounds like the sort of thing you want. I don't think I ever opened an issue for it, though. I've done that now: #323.

In the meantime, you might want to investigate an approach similar to what Spring Boot's does in its `spring-boot-actuator-docs` module. It uses [a template](https://github.com/spring-projects/spring-boot/blob/v1.4.1.RELEASE/spring-boot-actuator-docs/src/restdoc/resources/templates/endpoints.adoc.tpl) and a little bit of code to automate things a little.

**Comment by gsambasiva** [comment]
Thanks a lot wilkinsona , for your quick response.
I will take a look on that spring-boot-actuator-docs mudule.
