### ISSUE TITLE
Typo in 'Reusing field descriptors' section for RestAssured

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-restdocs#324]
See http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-request-response-payloads-reusing-field-descriptors. 

The RestAssured example for an array of books is:

```
RestAssured.given(this.spec).accept("application/json")
	.filter(document("books", responseFields(
		fieldWithPath("[]").description("An array of books")) 
		.andWithPrefix("[].", book))) 
	.when().get("/books/1")
	.then().assertThat().statusCode(is(200));
```

The get should be `/books/` and not `/books/1`

**Comment by wilkinsona** [comment]
Thanks for spotting this and taking the time to report it.
