### ISSUE TITLE
cannot set base path parameter

### ISSUE THREAD

**Issue by nikit-cpp** [spring-projects/spring-restdocs#326]
I started with example from here [spring-swagger2markup-demo](https://github.com/Swagger2Markup/spring-swagger2markup-demo)
In swagger-ui I can see "base path" which is set by affect of Spring Boot `server.contextPath` config property: `aaa/v3`
![swagger-ui](http://i.imgur.com/TCHtyrt.png)

Obvously =), base path are presents in swagger's generated adocs:
![basepath-in-swagger](http://i.imgur.com/jCS3zPc.png) 

But it ignored by restdocs
![restdocs](http://i.imgur.com/jhuyHG5.png).

I found what I can set scheme, host and port as described here [doc](http://docs.spring.io/spring-restdocs/docs/1.1.1.RELEASE/reference/html5/#configuration-uris).

It would be great if it could be set up and the basepath (probably among `withScheme()`, `withHost()`, `withPort()`) in restdocs too.

**Comment by wilkinsona** [comment]
I'm not 100% sure that I've understood the problem, but if I have, the section of the documentation that you've linked to describes what you need to do:

> To configure a request’s context path, use the `contextPath` method on `MockHttpServletRequestBuilder`.

Does that help?

**Comment by nikit-cpp** [comment]
Yes, it's (`MockHttpServletRequestBuilder#contextPath`) solves the trouble, thanks!
