### ISSUE TITLE
Packaging the documentation, gradle task needs clarification

### ISSUE THREAD

**Issue by steinerp** [spring-projects/spring-restdocs#331]
[Packaging the documentation](http://docs.spring.io/spring-restdocs/docs/1.1.3.BUILD-SNAPSHOT/reference/html5/#getting-started-build-configuration-gradle-packaging-the-documentation) could be expanded as shown in the StackOverflow answer to [Spring rest docs generated content not found](http://stackoverflow.com/a/40585682/6745479)

> There are two things that you need to do so that the documentation is served when using `bootRun`. The first is to copy the generated documentation into a location that's on the classpath used by `bootRun`:

```
task copyRestDocs(type: Copy) {
    dependsOn asciidoctor
    from "${asciidoctor.outputDir}/html5"
    into "${sourceSets.main.output.resourcesDir}/static/docs"
}
```

> Note that this new task depends on the `asciidoctor` task. This ensures that the documentation has been generated before it's copied.

> Secondly, the `bootRun` task must depend on the new `copyRestDocs` task:

```
bootRun {
    dependsOn copyRestDocs
}
```

**Comment by wilkinsona** [comment]
This is really entirely separate to packaging the documentation as `bootRun` doesn't package the application before it's run.

The documentation for REST Docs needs to strike a balance between explaining everything in detail and being concise and accessible. I'm not keen to document this as I think it's something of an edge case. Furthermore, there's not really anything that's REST Docs' specific in the answer. It's more about knowing how to configure Gradle.
