### ISSUE TITLE
Table of contents blocks body of documentation when window is resized

### ISSUE THREAD

**Issue by zgagnon** [spring-projects/spring-restdocs#332]
When viewing the reference documentation, when the window is resized horizontally, the table of contents blocks the main body so it can't be seen. Please see screenshot
![screen shot 2016-12-01 at 3 08 23 pm](https://cloud.githubusercontent.com/assets/324922/20810529/127d59a8-b7d8-11e6-9e8f-d8cbd12b9611.png)

Note the lack of horizontal scroll bar or ability to collapse the table of contents.

**Comment by wilkinsona** [comment]
Thanks. This was a problem with the docs server rather than Spring REST Docs itself. It should be fixed now.
