### ISSUE TITLE
Provide a way to configure secure port.

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-restdocs#338]
The `UriConfigurer` allows you to configure the `httpPort` (with default value 8080). However we also need a new property to be able to specify the `httpsPort`.

**Comment by ptahchiev** [comment]
I have a test which asserts whenever a client tries to access the login page via HTTP on port 8111 then this client is redirected to HTTPS on port 8112.

**Comment by wilkinsona** [comment]
What does that have to do with REST Docs? You'll need to set the port used for the HTTPS redirect using whatever mechanism is appropriate for whatever performs the redirect. You haven't said what that is so I can't offer any further advice other than suggesting that you configure it as you would if you were testing it without REST Docs being involved.
