### ISSUE TITLE
Tests for the Slate samples are failing. 

### ISSUE THREAD

**Issue by obviam** [spring-projects/spring-restdocs#339]
When running the test in the Slate sample project, some tests are failing.

`ApiDocumentation.indexExample()` for example is failing with
```
org.springframework.restdocs.snippet.SnippetException: The following parts of the payload were not documented:
{
  "_links" : {
    "tags" : {
      "href" : "http://localhost:8080/tags"
    },
    "notes" : {
      "href" : "http://localhost:8080/notes"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile"
    }
  }
}
```

It happens when validating the responseFields

`responseFields(fieldWithPath("_links").description("Links to other resources"))`

Using `subsectionWithPath` instead of `fieldWithPath` fixes the test.

Affected tests:
`indexExample()`
`notesListExample()`
`noteGetExample()`
`tagsListExample()`
`tagGetExample()`

in the `ApiDocumentation.java` **rest-notes-slate** project.

**Comment by wilkinsona** [comment]
Oops. Thanks. The dangers of not having proper CO for the sample that needs Ruby… This should have been changed as part of https://github.com/spring-projects/spring-restdocs/commit/cbd96f301d87078b01c6852723bf0861bdfbca11
