### ISSUE TITLE
Restdocs fails to generate json stub

### ISSUE THREAD

**Issue by zorosz** [spring-projects/spring-restdocs#341]
Restdocs fails to generate json output when using with mockMvc.

Using the following code will result in *.adoc fiels instead of a single json file containing the stub.:

```
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureRestDocs(outputDir = "target/snippets")
@AutoConfigureMockMvc
...
mockMvc.perform(
            post(WebController.CONTROLLER_ENDPOINT)
                .content("some_content")
        ).andExpect(
            status()
                .isOk()
        ).andExpect(
            content()
                .string("some_content")
        ).andDo(document("resource"));
```

results in:
curl-request.adoc
http-request.adoc
http-response.adoc
httpie-request.adoc

**Comment by wilkinsona** [comment]
Why do you expect a JSON stub? The REST Docs project doesn't support producing JSON stubs, although there are some extensions that do so. I also can't seen any sign that you've configured it to use such an extension.

**Comment by zorosz** [comment]
Spring cloud documentation states otherwise:
[https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_generating_stubs_using_restdocs](url)
