### ISSUE TITLE
Wrong base URL in http-response.adoc

### ISSUE THREAD

**Issue by daniwelter** [spring-projects/spring-restdocs#344]
We've noticed that in two separate projects, the hal links in the http-response snippets have the wrong base URL even though the correct URL was inserted in the curl-request and httpie-response snippets. See for example http://www.ebi.ac.uk/ols/docs/api#resources-api: "/ols" is present in the curl request but omitted from the example response _links.

**Comment by wilkinsona** [comment]
Interesting. It seems to be fine in your "Listing Resources" section, but I can see the problem you've described in the API resource and others. Given that it's not happening consistently, it might be rather tricky to track down. Could you please provide a small sample that illustrates the behaviour?

**Comment by daniwelter** [comment]
Apologies, I should have specified that the example response in the Listing Resources section was hard coded and should therefore be ignored. I'm not sure what the reasoning for this was as I'm not the lead developer on this project. Code at https://github.com/EBISPOT/OLS/tree/master/ols-web/src

The code I'm currently working on where I first discovered the issue (no public deployment yet so can't show output for this) lives at https://github.com/EBISPOT/goci/blob/GOCI-1107_RestAPI/goci-interfaces/goci-rest/src/test/java/uk/ac/ebi/spot/goci/ApiDocumentation.java

Relevant snippets:
-set-up
` this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
                .apply(documentationConfiguration(this.restDocumentation).uris()
                               .withScheme("https")
                               .withHost("www.ebi.ac.uk/gwas/rest")
                               .withPort(443))

                .alwaysDo(this.restDocumentationResultHandler)
                .build();`

-page-example
` this.mockMvc.perform(get("/api/studies?page=1&size=1"))
                .andDo(this.restDocumentationResultHandler.document(
                        responseFields(
                                fieldWithPath("_links").description("<<resources-page-links,Links>> to other resources"),
                                fieldWithPath("_embedded").description("The list of resources"),
                                fieldWithPath("page.size").description("The number of resources in this page"),
                                fieldWithPath("page.totalElements").description("The total number of resources"),
                                fieldWithPath("page.totalPages").description("The total number of pages"),
                                fieldWithPath("page.number").description("The page number")
                        ),
                        links(halLinks(),
                              linkWithRel("self").description("This resource list"),
                              linkWithRel("first").description("The first page in the resource list"),
                              linkWithRel("next").description("The next page in the resource list"),
                              linkWithRel("prev").description("The previous page in the resource list"),
                              linkWithRel("last").description("The last page in the resource list"),
                              linkWithRel("profile").description("Study resource profile"),
                              linkWithRel("search").description("Available search methods")
                        )

                ))
                .andExpect(status().isOk());`

**Comment by wilkinsona** [comment]
The problem is how you've configured the host:

```
.withHost("www.ebi.ac.uk/gwas/rest")
```

That's not just a host. It's a host and a context path. If you want to document the API as if it's deployed with a particular context path, you can do so by using the `contextPath` method on `MockHttpServletRequestBuilder`. It'd look something like this:

```
get("/gwas/rest/api/studies?page=1&size=1").contextPath("/gwas/rest")
```

Unfortunately, Java's `URI` class doesn't prohibit illegal characters in a hostname so there's no straightforward way to police this. I'd have to use a regex or introduce a third-party dependency, neither of which I want to do.
