### ISSUE TITLE
Newline character in snippet tables

### ISSUE THREAD

**Issue by jmisur** [spring-projects/spring-restdocs#351]
In our project we need to output multiline values in tables. For this we need to recognise which template format is being used and output ` +\n` for AsciiDoc and `<br>` for Markdown.
As mentioned in https://github.com/spring-projects/spring-restdocs/pull/350 it might be possible to use special Mustache lambda to provide this newline transparently.

**Comment by wilkinsona** [comment]
Unfortunately, I don't think this is as straightforward as I'd hoped.

@jmisur How are those multiline values being provided? Are they part of a custom snippet, or are they input to one of the existing snippets that's provided out of the box?

**Comment by wilkinsona** [comment]
Given that it's been more than that question above has gone unanswered for more than 6 months, it looks like this is no longer needed.
