### ISSUE TITLE
Default snippets are not considered with RestDocumentationResultHandler#document

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [spring-projects/spring-restdocs#355]
According to http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#configuration it is possible to configure default snippets which are supposed to be always generated.

However, these default snippets are not considered when using `RestDocumentationResultHandler#document` (they are actively removed https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-mockmvc/src/main/java/org/springframework/restdocs/mockmvc/RestDocumentationResultHandler.java#L98).

I created a sample project here: https://github.com/ThanksForAllTheFish/RestDOCS_defaults.

My expectation is that running `./gradlew build` should generate 4 snippets:
- curl-request.adoc
- http-request.adoc
- http-response.adoc
- response-headers.adoc
but only the last one is indeed created.

**Comment by wilkinsona** [comment]
They default snippets are deliberately removed to avoid them being generated twice.

The problem in your test is that you aren't using the original result handler that will produce the default snippets. The approach that you need to take is [described in the documentation](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#customizing-requests-and-responses).
