### ISSUE TITLE
Can't document a field path that contains a dot

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-restdocs#356]
If I have a payload field that contains a dot, such as `api.revision`, then `JsonFieldPath` insists that this is a nested construct and the whole thing breaks from there.
There is no way to escape the dot, or to even bypass Json interpretation as a path, etc.

**Comment by wilkinsona** [comment]
> There is no way to escape the dot

Yes there is. You can use bracket notation such as `"[api.revision]"` as [described in the documentation](http://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-request-response-payloads-json-field-paths).

**Comment by ericbottard** [comment]
My bad, followed the code and assumed it had to jump straight into `extractDotSeparatedSegments()`. Thanks!
