### ISSUE TITLE
Provide reference documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#37]

**Comment by mayboroda** [comment]
Hi, do you have any description what is expected to have in the end of the task?
I can think of:
- apply gradle-asciidoctor plugin to generate docbook
- apply spring-docbook plugin to generate 4 entries for the documentation
- write the documentation

I think the last bullet has to be specified more accurate: chapters, sub-chapters

**Comment by wilkinsona** [comment]
I opened this issue more to get in on my todo list than in expectation that anyone else would tackle it.

My intention is to use a pure Asciidoctor-based approach. That'll probably mean no PDFs for now ([PDF support](http://asciidoctor.org/docs/convert-asciidoc-to-pdf/) is in alpha at the moment), but it'll also mean no Docbook which is a trade-off I'm happy to make.

I haven't thought too much about the structure of the documentation in terms of chapters, sub-chapters, etc yet. If you are interested in helping out, perhaps we can revisit this once a general outline is in place?

**Comment by mayboroda** [comment]
I knew about asciidoc PDF support in alpha that is why I was thinking about docbook (I'm doing the same on my current project). Also I found an interesting plugin for docbook https://github.com/spring-gradle-plugins/docbook-reference-plugin and it's great cause it's making 4 artifacts in the end:
- html
- single-html
- pdf
- epub

That is already branded with spring leaf in background :) (BTW it's used in many spring projects: spring-integration for sure)

And yeah, I can help as long as my English is acceptable :)
