### ISSUE TITLE
Multiple example for same Rest Resources

### ISSUE THREAD

**Issue by obeyler** [spring-projects/spring-restdocs#376]
I need to provide several examples for the same rest resources. My rest API can be invoked with different parameters and some are optionals. I want to provide one example with no option and another with option.
Do realize that I use 
 ```
       result = this.mockMvc.perform(post("/api/create")
                .content(content_without option)
                .contentType(MediaType.APPLICATION_JSON_UTF8)
                .accept(MediaType.APPLICATION_JSON))
                .andDo(document("create/1/"))
                .andExpect(status().is2xxSuccessful())
                .andReturn();

        result = this.mockMvc.perform(post("/api/create")
                .content(content_withoption)
                .contentType(MediaType.APPLICATION_JSON_UTF8)
                .accept(MediaType.APPLICATION_JSON))
                .andDo(document("create/2/"))
                .andExpect(status().is2xxSuccessful())
                .andReturn();
```
this create two subdirectory (1 and 2) of snippet  "create"

 ```
this.mockMvc.perform(get("/v2/api-docs")
                .accept(MediaType.APPLICATION_JSON))
                .andDo(Swagger2MarkupResultHandler.outputDirectory("target/generated-docs")
                        .withPathsGroupedBy(GroupBy.TAGS)
                        .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
                        .withExamples("target/generated-snippets").build())
                .andExpect(status().isOk())
                .andReturn();

```
the "withExample" does not see that there is 2 samples. Is it a bug or a evolution to be able to have several example to insert into documentation ?

**Comment by wilkinsona** [comment]
`Swagger2MarkupResultHandler` isn't part of Spring REST Docs. It was part of https://github.com/springfox/springfox/ at one point but doesn't appear to be there any more. @RobWin may be able to point you to the right repository.

**Comment by RobWin** [comment]
Hi, 
indeed, Swagger2Markup is not part of Springfox anymore and the version in Springfox is outdated.
Please have a look at https://github.com/Swagger2Markup/swagger2markup.
User Guide: http://swagger2markup.github.io/swagger2markup/1.3.1/
Spring Boot Demo: https://github.com/Swagger2Markup/spring-swagger2markup-demo

The Spring Rest Docs integration is part of the extension SPI: http://swagger2markup.github.io/swagger2markup/1.3.1/#_provided_extensions

But you could also use the "Dynamic file import extension" to import any generated Asciidoc file at the extension point `OPERATION_END`.
