### ISSUE TITLE
Support HATEOAS links documentation in embedded resources

### ISSUE THREAD

**Issue by tsypuk** [spring-projects/spring-restdocs#381]
Currently restdocs supports documenting HATEOAS for resources that return the single element, for example:
```
Body = {
  "name" : "SpeakerName",
  "company" : "CompanyName",
  "_links" : {
    "self" : {
      "href" : "https://localhost:8080/speakers/1"
    },
    "topics" : {
      "href" : "https://localhost:8080/speakers/1/topics"
    }
  }
}
```
using: 
```
links(halLinks(),
       linkWithRel("self").description("Link to self section."),
       linkWithRel("topics").description("Link to speaker's topics")));
```
If we are using a collection of resources, we can not document links of embedded elements:
```
Body = {
  "_embedded" : {
    "speakers" : [ {
      "name" : "Speaker1",
      "company" : "company",
      "_links" : {
        "self" : {
          "href" : "https://localhost:8080/speakers/1"
        },
        "topics" : {
          "href" : "https://localhost:8080/speakers/1/topics"
        }
      }
    }, {
      "name" : "Speaker2",
      "company" : "company",
      "_links" : {
        "self" : {
          "href" : "https://localhost:8080/speakers/2"
        },
        "topics" : {
          "href" : "https://localhost:8080/speakers/2/topics"
        }
      }
    } ]
  }
}
```

**So it would be useful to create and use Snippet** that will **parse _embedded collection** and **verify that documented links are present in all elements**. I think it will be good to reuse the same idea as ResponseFieldsSnippet responseFields(FieldDescriptor... descriptors) uses.

And the **signature** can be:
`EmbeddedLinksSnippet(LinkExtractor linkExtractor, LinkDescriptor... descriptors)`
Using it we can specify **_embeddedHal** link extractor and the **same link descriptors**.

**Comment by wilkinsona** [comment]
I'm not sure about this. Assuming that you already have documentation for the speaker resource that will describe the `self` and `topics` links, why not just include a cross-reference to that in the documentation for the resource that provides access to a collection of speakers?

**Comment by tsypuk** [comment]
Thanks @wilkinsona .
Yes this makes sense as work around for documentation.

In this case we are no using the TestDrivenDocumentation that spring rest docs gives us and we rely on the data from another test and it is not good (

So if any element of collection does not have desired properties, we are just documenting the optimistic scenario and including the snippet from another test of single element method with document(). 

It would be more desirable to see failing test with exact message :) Like the responseFields does for fields of collection.

**Comment by wilkinsona** [comment]
> In this case we are no using the TestDrivenDocumentation that spring rest docs gives us and we rely on the data from another test and it is not good (

Sorry, I'm not sure that I understand what you've said here. Can you explain a bit more please?

**Comment by wilkinsona** [comment]
Despite all the 👍 reactions, I'm still not sure about this for the reasons explained [above](https://github.com/spring-projects/spring-restdocs/issues/381#issuecomment-295640356). If you still want to document the links in an embedded resource, you can use the existing links snippet with a custom `LinksExtractor` implementation.

In the absence of a compelling argument against this approach I am going to close this issue. It can be reopened should such an argument be presented in the future.

**Comment by rainer198** [comment]
It may occurr that the entries of the collection resource have fewer links than the single entity (e.g. only the self link to a particular speaker) or links which are only present for collection entries (e.g. for moving a speaker to a different position with the collection). In this case, you cannot reuse the link documentation of the entry entity.
