### ISSUE TITLE
Add support for using WebTestClient to document an API

### ISSUE THREAD

**Issue by dbacinski** [spring-projects/spring-restdocs#384]
Is it possible to use Spring Rest Docs with new WebTestClient from Spring WebFlux?

https://spring.io/blog/2017/02/23/spring-framework-5-0-m5-update

Or for now I have to use RestAssured to make documentation for Spring WebFlux app?

**Comment by wilkinsona** [comment]
No, not yet. You'll have to use REST Assured for the time being. I hope to add support for `WebTestClient` in REST Docs 2.0 but hadn't got around to creating an issue for it so I'll use this one. Thanks for raising it.
