### ISSUE TITLE
Field snippets do not support XML payloads other than application/xml

### ISSUE THREAD

**Issue by bill-okara** [spring-projects/spring-restdocs#393]
Hi,

First of all, I just want to sincerely say THANK YOU for creating this project. I really appreciated the flexibility and robustness it provided for doing documentation (I originally tried to upgrade our existing doc framework with Swagger/OpenApi, but that required too much refactoring of existing servlet based APIs). 

Regarding this ticket, it seems that current AbstractFieldsSnippet.getContentHandler() only selects XmlContentHandler for MediaType.APPLICATION_XML, would it makes sense to also support
- MediaType.TEXT_XML?

As stated in [RFC-3023](https://tools.ietf.org/html/rfc3023#page-5), it seems that both 'application/xml' and 'text/xml' are valid content-type for xml responses.

> If an XML document -- that is, the unprocessed, source XML document
>    -- is readable by casual users, text/xml is preferable to
>    application/xml.  MIME user agents (and web user agents) that do not
>    have explicit support for text/xml will treat it as text/plain, for
>    example, by displaying the XML MIME entity as plain text.
>    Application/xml is preferable when the XML MIME entity is unreadable
>    by casual users.
> 

Thanks!
Bill

**Comment by wilkinsona** [comment]
Thank you for the kind words. Not supporting `text/xml` is an oversight on my part. `XmlContentHandler` should deal with anything that's XML (so not only `application/xml` and `text/xml` but also things like `application/rss+xml` as well).
