### ISSUE TITLE
Support kebab casing for test method names that have underscore in them

### ISSUE THREAD

**Issue by sudr** [spring-projects/spring-restdocs#395]
Currently the kebab-casing for parameterized output directories using "{method-name}" doesn't work if the test method name itself is snake cased (Ex. test_get_returns_success).

We using snake casing for test method names for readability. But when generating the rest docs we'd like to have the option to generate the output directory name as kebab case (Ex. test-get-returns-success). This allows us to keep the naming convention for our directories consistent.

**Comment by wilkinsona** [comment]
This is already possible if you provide you own `WriterResolver` that uses a custom `PlaceHolderResolverFactory`. For example:

```java
@Test
public void test_name_using_snake_case() throws Exception {
    MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
            .apply(new MockMvcRestDocumentationConfigurer(this.restDocumentation)
                    .writerResolver(new StandardWriterResolver(
                            new CustomPlaceholderResolverFactory(), "UTF-8",
                            TemplateFormats.asciidoctor())))
            .build();
    mockMvc.perform(get("/").accept(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk()).andDo(document("{method-name}"));
}

private static class CustomPlaceholderResolverFactory
        implements PlaceholderResolverFactory {

    @Override
    public PlaceholderResolver create(RestDocumentationContext context) {
        return (placeHolder) -> {
            if ("method-name".equals(placeHolder)) {
                return context.getTestMethodName().replace("_", "-");
            }
            return context.getTestMethodName();
        };
    }

}
```

Given that the functionality is pluggable, it can be made to do what you want, and the default implementation seems to meet most people's needs, I think it's best to leave things as they are. Thank you for the suggestion, though.

**Comment by sudr** [comment]
Thanks. This does what I was looking for. And thanks for the code sample that enabled me to implement this.
