### ISSUE TITLE
Operation macro doesn't render request response with pdf asciidoctor backend

### ISSUE THREAD

**Issue by sudr** [spring-projects/spring-restdocs#396]
When using the operation macro in a .adoc file with the asciidoctor PDF backend configuration to generate a pdf, the actual request and response payloads are not being rendered in the PDF. Though the headers (such as "Curl request" and "HTTP response") do get rendered in the PDF.

If I flip the backend to html then html is rendered as expected.

**Comment by wilkinsona** [comment]
That's rather strange as the macro runs at a stage when the backend should be irrelevant. Could you please put together a small sample that illustrates the problem and shows the versions of the various pieces that you are using?

**Comment by sudr** [comment]
I've created a minimal demo project that reproduces this issue:

https://github.com/sudr/restdocs-demo

It's configured for the html backend and works as expected. You can switch it to the pdf backend on line 33 in the pom.xml and validate that the request and response snippets aren't rendered in the generated PDF.

**Comment by wilkinsona** [comment]
Thanks. This looks to be a problem with `asciidoctor-pdf`. I've [opened an issue](https://github.com/asciidoctor/asciidoctor-pdf/issues/815). Unfortunately, until that issue reaches a conclusion, you'll either need to stick to HTML output or to including each snippet individually.
