### ISSUE TITLE
Can I change "Last updated" to build time?

### ISSUE THREAD

**Issue by malafeev** [spring-projects/spring-restdocs#401]
In the bottom of generated html there is "Last updated" line.
Date points to time when adoc file was changed.

If I changed tests then it means that content of html also changed. But "Last updated" is not updated. It is confusing.

**Comment by wilkinsona** [comment]
That's standard Asciidoctor behaviour. Please see [this issue](https://github.com/asciidoctor/asciidoctor/issues/1163) and the issues to which it links.

**Comment by malafeev** [comment]
looks like will never be fixed (linked issues 3-4 years old)

**Comment by wilkinsona** [comment]
I suspect it's a question of priorities and bandwidth. If it's important to you why not offer to help?
