### ISSUE TITLE
Resolve placeholders in both arguments in WriterResolver

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-restdocs#403]
The `StandardWriterResolver` currently replaces placeholders (e.g. `{method-name}`) in the first argument, but not the second, which limits the layout of the snippets a bit. It would be useful to be able to put placeholders in both strings. That way you can have asciidoc snippets in one directory and json (or whatever) in another.

**Comment by wilkinsona** [comment]
@dsyer Once https://build.spring.io/browse/SRD-PUB2-19 has finished, 1.2.3.BUILD-SNAPSHOT should hopefully give you what you were looking for. Please let me know if that's not the case and I'll take another look.

**Comment by dsyer** [comment]
That looks like it would work. When does `1.2.3` make it into Spring Boot dependency management (2.0?).

**Comment by wilkinsona** [comment]
Yep. Boot 2.0's currently using 1.2.2. It'll upgrade to 1.2.3 once it's released.

I may yet finish REST Docs 2.0 in time for it to sneak into Boot 2.0. That's certainly what I'd like to happen but I may run out of time.
