### ISSUE TITLE
NullPointerException when document response test

### ISSUE THREAD

**Issue by albertkurnia** [spring-projects/spring-restdocs#406]
Sorry, I have trouble here. I want to document the rest assured test by putting code below

    final Map<String, String> labels = new HashMap<>();
    labels.put("device", "android");
    labels.put("shipping", "aws");

    final HashMap<String, Object> testVoucherRequest = new HashMap<>();
    testVoucherRequest.put("voucher_code", "dummyCode");
    testVoucherRequest.put("amount", 1000);
    testVoucherRequest.put("merchant_user_id", "dummyMerchantUserId");
    testVoucherRequest.put("labels", labels); 
    
    Map<String, Object> response =
        given()
            .auth().preemptive().basic("username", "pass")
        .contentType(ContentType.JSON)
                .body(testVoucherRequest)
                .filter(document("test-voucher", preprocessRequest(prettyPrint()),
                        responseFields(
                                fieldWithPath("valid").description("status valid or invalid"),
                                fieldWithPath("discount_amount").description("Discount Amount remaining"),
                                fieldWithPath("reason").description("Response reason"),
                                fieldWithPath("reason_params").description("Reason params"))))
        .when()
            .post("/api/v1/redemptions/test")
        .then()
            .statusCode(200)
            .contentType(ContentType.JSON)
            .body("valid", equalTo(true))
            .body("discount_amount", equalTo(250))
            .extract().as(Map.class);

There is NullPointerException when I run this test

`java.lang.NullPointerException at java.util.HashMap.putMapEntries(HashMap.java:500) at java.util.HashMap.<init>(HashMap.java:489) at org.springframework.restdocs.restassured3.RestDocumentationFilter.getConfiguration(RestDocumentationFilter.java:74) at org.springframework.restdocs.restassured3.RestDocumentationFilter.filter(RestDocumentationFilter.java:56)`

**Comment by wilkinsona** [comment]
It looks to me like you're missing some configuration. I can't see any use of `JUnitRestDocumentation` or the `Filter` that's returned from `documentationConfiguration`. The necessary setup is shown in the [REST Assured sample](https://github.com/spring-projects/spring-restdocs/blob/v1.2.1.RELEASE/samples/rest-assured/src/test/java/com/example/restassured/SampleRestAssuredApplicationTests.java). If that doesn't help, please provide a complete example of the problem and we can take another look.

**Comment by albertkurnia** [comment]
the JUnitRestDocumentation

`@Rule
    public final JUnitRestDocumentation restDocumentation = new JUnitRestDocumentation("build/generated-snippets");`

Request Spesification
`private RequestSpecification requestSpecification;`

setup
` @Before
    public void setUp(){
        this.requestSpecification = new RequestSpecBuilder().addFilter(documentationConfiguration(this.restDocumentation).snippets().withTemplateFormat(markdown())).build();
    }`

my test
`@Test
    public void testTestVoucher_WithLabels() {
        List<Merchant> merchants = createDummyMerchants();
        createDummyApiClient("username", "pass", merchants);
        User user = createDummyUser("user1", "password", merchants);
        createDummyVoucher("dummyCode", 25L, user, merchants.stream().findFirst().get(), 100, ZonedDateTime.now().minusDays(2), ZonedDateTime.now().plusDays(2), 5, "shipping=jne;device=android,ios");

        final Map<String, String> labels = new HashMap<>();
        labels.put("device", "android");
        labels.put("shipping", "jne");

        final HashMap<String, Object> testVoucherRequest = new HashMap<>();
        testVoucherRequest.put("voucher_code", "dummyCode");
        testVoucherRequest.put("amount", 1000);
        testVoucherRequest.put("merchant_user_id", "dummyMerchantUserId");
        testVoucherRequest.put("labels", labels);

        Map<String, Object> response =
            given()
                .auth().preemptive().basic("username", "pass")
            .contentType(ContentType.JSON)
                    .body(testVoucherRequest)
                    .filter(document("test-voucher", preprocessRequest(prettyPrint()),
                            responseFields(
                                    fieldWithPath("valid").description("status valid or invalid"),
                                    fieldWithPath("discount_amount").description("Discount Amount remaining"),
                                    fieldWithPath("reason").description("Response reason"),
                                    fieldWithPath("reason_params").description("Reason params"))))
            .when()
                .post("/api/v1/redemptions/test")
            .then()
                .statusCode(200)
                .contentType(ContentType.JSON)
                .body("valid", equalTo(true))
                .body("discount_amount", equalTo(250))
                .extract().as(Map.class);

        assertThat(response).containsOnlyKeys(
                "valid", "discount_amount", "reason", "reason_params"
        );
    }`

and still generate error NullPointerException

**Comment by albertkurnia** [comment]
ok i found it. thanks

**Comment by bouwerp** [comment]
@albertkurnia what was the issue? Do you please mind sharing it?
