### ISSUE TITLE
Wrong version dependency to spring-restdoc-core

### ISSUE THREAD

**Issue by VisiG** [spring-projects/spring-restdocs#407]
I'm using Version 1.2.1.Release from Maven like this:
```
<dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-mockmvc</artifactId>
            <version>1.2.1.RELEASE</version>
        </dependency>
```
But when resolving dependencies "spring-restdocs-mockmvc" 1.1.2.Release is used.

I had trouble when using 
`import static org.springframework.restdocs.payload.PayloadDocumentation.responseBody;`

When i set the correct dependency on my own everything works fine.

See also:[]( http://www.sylvainlemoine.com/2017/06/14/fail-of-the-day---spring-rest-docs-vs-spring-boot-dependencies/)

**Comment by wilkinsona** [comment]
Are you using Spring Boot?

**Comment by VisiG** [comment]
Yes

**Comment by wilkinsona** [comment]
Then you need to override its dependency management. Spring Boot uses REST Docs 1.1.x by default. Add `<spring-restdocs.version>1.2.1.RELEASE</spring-restdocs.version>` to the `<properties>` section of your pom.

**Comment by VisiG** [comment]
Please put an info on the reference site where the build configuration is described. I wasted several hours on this issue.

Thanks for help!
