### ISSUE TITLE
multipart/form-data parameters sent as "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by Meherzi** [spring-projects/spring-restdocs#414]
Hello,
I'm using spring rest doc to generate documentation for a service wich send an email.
The simplest example, we have POST method with foor  'formData' parameter ( to, from, subject and text). This is send as 'application/x-www-form-urlencoded', not as required 'multipart/form-data'. Walkaround is inserting an additional parameter of type 'file', that will make the request as 'multipart/form-data' (correct).
In the generated curl, you can see that content type is mentionned as multipart/form-data whereas the parameters are sent as www-form-urlencoded
![curl](https://user-images.githubusercontent.com/30697588/28929390-b8aafe34-7867-11e7-968e-e644d598f701.png)

**Comment by wilkinsona** [comment]
Can you please share the test that you used to generate the curl snippet you've shown above?

**Comment by Meherzi** [comment]
- This is the standard send test that generates the last curl
```
@Test
	public void standardSend()
		throws Exception
	{

		given(mailgunService.send(Matchers.<Email>
			anyVararg())).willReturn(RESPONSE);

		mockMvc.perform(
			post("/send") // does not work also if I put fileUpload("/send")
				.contentType(MediaType.MULTIPART_FORM_DATA_VALUE)
			.param("to", TO)
			.param("from", FROM)
			.param("subject", SUBJECT)
			.param("text", TEXT))
			.andExpect(status().isOk())
                        .andDo(document("standardSend",
			preprocessRequest(prettyPrint()),
			preprocessResponse(prettyPrint()),
                 ...
      }
```
    Adding a file will generate the wanted curl with the right mediatype 
                  ```
mockMvc.perform( fileUpload("/send").file(fileInAttachment)
				.file(inlineFile)
```

here is the the resource annotation  in the controller
```
@RequestMapping(
		value = "/send",
		method = RequestMethod.POST,
		consumes = MediaType.MULTIPART_FORM_DATA_VALUE,
		produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
	public String sendEmail(
		@ModelAttribute
		@Validated
		Email email)
```

**Comment by wilkinsona** [comment]
Thanks.

`param` is intended for sending request parameters, which aren't really the same things as multipart parts. REST Docs may be able to be enhanced to cope with the way you've used MockMvc, but the expectation at the moment is that you'd use `fileUpload` and `file`:

```
mockMvc.perform(fileUpload("/upload").file("test", "content".getBytes()))
```

**Comment by Meherzi** [comment]
Yes thank you, I got that. The problem here that we expect that the curl in documentation will work wich is not the case  because the decoder just accept multipart form data even if there is  no file parts. 
I'll be thankful if you have any suggestion to generate a curl wich works.

**Comment by wilkinsona** [comment]
As I said above, I believe it should work if you use `fileUpload` and `file`. Do you believe that's not the case?

**Comment by Meherzi** [comment]
I believe that it works with `fileUpload` and `file` but I want that it works also without a file. ( with a `post` and specifying the content type for exemple)  
I think I'm missing somthing in my explanation. In fact, the rest api of sending an email have mandatory parameters and optional one like cc, bcc, attachement and inline. Th server does only accept multipart form data even when there is no file to send.
So I think that it should be a way to select  requestContentType according to what is comsumed by the api in order to generate a curl wich will be accepted.
What I want is this curl

`curl 'http://localhost:8793/send' -i -X POST -H 'Content-Type: multipart/form-data' -F 'to=meherziamira92@gmail.com' -F 'from=support@gmail.com' -F 'subject=Hello' -F 'text=Hello'`

I believe also that the generated curl is conflicting, on one side the content type is set to `MULTIPART_FORM_DATA` and on the other side  the parameter are in `url-from-encoding. ` ?

`curl 'http://localhost:8793/send' -i -X POST -H 'Content-Type: multipart/form-data' -d 'to=meherziamira92%40gmail.com&from=dev.test%40gmail.com&subject=Hello&text=Hello'`

**Comment by wilkinsona** [comment]
> I believe that it works with fileUpload and file and I test it but I want that it works also without a file.

The `MockMvc` API is a bit confusing here. `file` doesn't really mean a file, it's just adding a part to your multipart request. That part could be a file upload, but it doesn't have to be. The example I shows above (`file("test", "content".getBytes())`) is not a file upload.

> with a post and specifying the content type for exemple

`fileUpload` will perform a post and set the content type for you

> I believe also that the generated curl is conflicting

The generated curl is conflicting, but that's because the request is also conflicting. You have explicitly set the content type to `multipart/form-data` but have then configured request parameters and haven't configured any parts.

**Comment by wilkinsona** [comment]
It looks like this issue has now run its course. Please comment if that's not the case and it can be reopened.
