### ISSUE TITLE
Add Context Path in Builder

### ISSUE THREAD

**Issue by ianagius** [spring-projects/spring-restdocs#418]
Hi,
when setting the uris, can you add a method to add the uri context-path?
Example with the following:

```
.uris()
  .withScheme("http")
  .withHost("localhost")
  .withPort(8080)
```
we can add:
```
  .withContextPath("myServiceName")
```

**Comment by wilkinsona** [comment]
There's no need for such a method. As [noted in the documentation](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#configuration-uris) you should "use the `contextPath` method on `MockHttpServletRequestBuilder`".
