### ISSUE TITLE
Add support for using Gru to document an API

### ISSUE THREAD

**Issue by joemccall86** [spring-projects/spring-restdocs#421]
See https://agorapulse.github.io/gru/

Coming from solely writing Spock tests in Grails, both MockMVC and RESTAssured seem to clash stylistically. I think Gru would be a great option to allow for more terse tests to be written, especially for users in the Groovy ecosystem.

**Comment by wilkinsona** [comment]
Interesting suggestion, thank you. I wasn't aware of Gru before. It does look quite nice, particularly if you're a Groovy person.

Do you have a feel for how Gru can be extended and what REST Docs support for Gru should look like? If we can figure out what's possible and sketch out how the support should look, we can then take things from there.

**Comment by joemccall86** [comment]
Sorry for the delay.

I have a basic understanding of extending Gru. I think we would need to create a custom "minion" to handle do the same job as RestAssuredRestDocumentation., and extend the DSL to make it nice to use.

I would imagine it can look like this:

```
@Test
void 'shapes are listed'() {
    gru.test {
        get '/api/shapes', {
            headers Authorization: "Bearer xxxx"
        }
        expect {
            status 200
            snippet document('shapes-list-example',
                    preprocessRequest(modifyUris()
                        .scheme('https')
                        .host('rest.example.com')
                        .removePort()
                    ),
                    preprocessResponse(prettyPrint()),
                    responseFields(
                            //...
                            // Record response fields
                            //...
                    )
            )
        }
    }
}
```

Does that make sense?

**Comment by wilkinsona** [comment]
Yeah, that makes sense. Thanks. I'll leave this one open for now to see if there's any other interest in this. My feeling at the moment is that Gru is something of a niche and this may be better off as a third-party extension rather than being part of REST Docs itself.

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
