### ISSUE TITLE
Support for Spring TestRestTemplate

### ISSUE THREAD

**Issue by jwedel** [spring-projects/spring-restdocs#426]
**Feature Request**

Currently, we write all our web integration with spring's `TestRestTemplate`. It would be nice, if Spring REST Docs could be used. 

One idea would be to provide a fluent API that allows to do the actual REST call at the end:

```
ResponseEntity<LoginResponse> response = restDocs
        .title("Login")
        .description("Login parameters must be provided via JSON body.")
        .postForEntity("/login"), request, LoginResponse.class);
```

or without documentation:

```
ResponseEntity<LoginResponse> response = restDocs
        .skipDocumentation()
        .postForEntity("/login"), request, LoginResponse.class);
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. REST Docs 2.0 will provide support for [documenting an API using Spring Framework 5's `WebTestClient`](https://github.com/spring-projects/spring-restdocs/issues/384) alongside the existing support for using REST Assured. Providing a third option of using `TestRestTemplate` would, I think, be rather confusing and wouldn't gain enough to warrant the additional maintenance cost.

**Comment by jwedel** [comment]
@wilkinsona Thanks for the reply. From the progress bar, I can seen 3/4 of the tasks are done, but is there a planned release date for the 2.0?

**Comment by wilkinsona** [comment]
There's no firm date at the moment for 2.0 M1.
