### ISSUE TITLE
Generate snippets for other technologies

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-restdocs#427]
It would be great if Rest Docs could generate snippets for most popular tools/libraries. Currently only cURL and httpie are supported. For Spring most natural would be probably `RestTemplate` and that's good place to start.

**Comment by wilkinsona** [comment]
@jkubrynski Thanks for opening this after mentioning it on Gitter.

I think the hardest part of this would be dealing with the bodies of the requests and responses. What had you imagined that would look like? Some examples here of the snippet content that you would like to see would be most useful.

**Comment by wilkinsona** [comment]
There's also Spring Framework 5's `WebClient` that we hope will become an even more natural choice than `RestTemplate`.

**Comment by jkubrynski** [comment]
That's a great idea to collect some examples of different technologies and then check what can be done. I'll try to spend some time on that.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
