### ISSUE TITLE
Is there an way to create the api-guide from commandline with asciidoctor?

### ISSUE THREAD

**Issue by tobiashochguertel** [spring-projects/spring-restdocs#434]
Something like this:

`asciidoctor -b xhtml5 -a stylesheet=./stylesheets/asciidoctor.css api-guide.adoc`

But I use the `operation` macro, is this an built in macro from asciidoctor?

`operation::admin-user-create[snippets='request-fields,request-body,http-request,curl-request,http-response,response-body']`

**Comment by wilkinsona** [comment]
> is this an built in macro from asciidoctor?

No, as [described in the documentation](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#working-with-asciidoctor-including-snippets-operation) it's a custom macro provided by Spring REST Docs. It's written in Ruby but relies on AsciidoctorJ for automatic registration of the macro with the Asciidoctor runtime. You could extract the macro from the `spring-restdocs-asciidoctor` module and register it manually with Asciidoctor if you want to use its gem on the command line.
