### ISSUE TITLE
, escaped in generated request snippets

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-restdocs#439]
```
public enum Status {
  OPEN, CLOSED
}
```

```
@RepositoryRestResource(path = "entries")
@Repository
interface EntryRepository extends PagingAndSortingRepository<Entry, Integer>  {

  @RestResource(path = "/statuses")
  List<Entry> findByStatusIn(Set<Status> statuses);
}
```

```
mvc.perform(
            get("/entries/search/statuses")
                .param("statuses", "OPEN,CLOSED")
                .andDo(document("entries-search-by-statuses-example"));
```

```
[source,http,options="nowrap"]
----
GET /entries/search/statuses?statuses=OPEN%2CLOSED HTTP/1.1
Accept: application/hal+json

----
```

Notice the `%2` instead of `,`.

Happens in all 3 generated request snippets: _curl-request.adoc_, _http-request.adoc_, and _httpie-request.adoc_.

**Comment by wilkinsona** [comment]
I believe that's the correct behaviour given your test. You're trying to use `OPEN,CLOSED` as a single value of `statuses`. `,` is reserved as a separator for query parameters so it's encoded to prevent the value being separated into `OPEN` and `CLOSED`. If you want them to be separate values you should send them as such: `.param("statuses", "OPEN", "CLOSED")`.
