### ISSUE TITLE
Upgrade the Grails sample to 3.3.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#445]

**Comment by wilkinsona** [comment]
This is proving to be easier said than done. @jlstrater, do you have any tips on upgrading from Grails 3.2.x to 3.3.x please?

**Comment by jlstrater** [comment]
Ack! Somehow I didn't get the notification for this in October. I'll add it to my todo list for this week.

**Comment by wilkinsona** [comment]
Duplicate of #469
