### ISSUE TITLE
Document URI configuration when using WebTestClient

### ISSUE THREAD

**Issue by zaynetro** [spring-projects/spring-restdocs#455]
`WebTestClientRestDocumentationConfigurer` should support `UriConfigurer` through `uris` method like MockMvc.

Or am I missing something?

Also this is rather strange: https://github.com/spring-projects/spring-restdocs/blob/master/docs/src/test/java/com/example/webtestclient/CustomUriConfiguration.java#L38

MockMvc test in `webtestclient` package.

**Comment by wilkinsona** [comment]
> WebTestClientRestDocumentationConfigurer should support UriConfigurer through uris method like MockMvc.
>
> Or am I missing something?

When you're using `WebTestClient` you get an opportunity to configure the base URI to suit your needs, for example

```java
this.webTestClient = WebTestClient.bindToRouterFunction(route).configureClient()
	.baseUrl("https://api.example.com")
	.filter(documentationConfiguration(this.restDocumentation)).build();
```

I think this means that there's no need to support URI configuration at the REST Docs level. I suspect that this issue means that this needs to be made clear in the documentation.

> Also this is rather strange: https://github.com/spring-projects/spring-restdocs/blob/master/docs/src/test/java/com/example/webtestclient/CustomUriConfiguration.java#L38
>
> MockMvc test in webtestclient package.

Thanks. That file isn't used and should be deleted. I've opened https://github.com/spring-projects/spring-restdocs/issues/456 to take care of that.
