### ISSUE TITLE
Inconsistency between .adoc generated by passing snippets into MockMvcRestDocumentation.document() vs passing snippets to RestDocumentationResultHandler.document()

### ISSUE THREAD

**Issue by Lwiczyn** [spring-projects/spring-restdocs#464]
Previously, my team has been passing all of our RestDocumentationResultHandler
 snippets into the static constructor provided by MockMvcRestDocumentation.document() and everything has been working great. However, recently I tried an optimization where instead we created a RestDocumentationResultHandler and then later called RestDocumentationResultHandler.document(snippets) to add additional description.

The problem is that when we do this, only snippets relating to the snippets passed to .document() are generated such as path-parameters.adoc. We no longer see default snippets generated such as curl-request.adoc.

When debugging, I am seeing that when creating a RestDocumentationResultHandler via MockMvcRestDocumentation, the resultant object has one field: delegate. However, when adding snippets via RestDocumentationResultHandler.document(), the resultant object has two fields: delegate and "$this" which itself has a delegate. I am not sure if this is the root cause of the issue, but it looks off.

Link to demonstration repo: https://github.com/Lwiczyn/SpringRestDocs_document_bug

Thank you for your time.

**Comment by wilkinsona** [comment]
This is working as intended and as described in the javadoc. The two result handlers need to be passed to separate calls to `andDo` or `alwaysDo`.

**Comment by wilkinsona** [comment]
There are also examples of the intended usage in [this section of the reference documentation](https://docs.spring.io/spring-restdocs/docs/1.2.x-SNAPSHOT/reference/html5/#customizing-requests-and-responses).

**Comment by Lwiczyn** [comment]
Can you point me to the place in the documentation where it indicates that failing to use alwaysDo results in certain snippets not being generated? From my reading of your link, alwaysDo looks like a convenience with the example presenting one way of doing things. I would not anticipate the destructive behavior I am seeing from that section and would expect that an option to not generate certain snippets would be called out as a feature.

The javadoc on RestDocumentationResultHandler.document(Snippet... snippets) also gives me the expectation that it functions more as a fluent setter which should be compatible with andDo():

> Creates a new RestDocumentationResultHandler to be passed into ResultActions.andDo(ResultHandler) that will produce documentation using the given snippets.

**Comment by wilkinsona** [comment]
The javadoc you have quoted already does that, IMO. It returns a result handler “that will produce documentation using the given snippets”, not the combination of the given snippets and those of the existing result handler.

**Comment by Lwiczyn** [comment]
I find it difficult to understand why a class's member function would produce a new instance of the class but populated only with the parameters to that member function call with no reference to the values of the original instance's fields. Creating a new instance without reference to the contents of another instance is typically done via a static function of some sort to avoid this exact confusion. Furthermore, if you don't need the member fields, there is no reason to be tied to the instance.

For this reason, I would naively understand the "combination of the given snippets and those of the existing result handler" part to be implicit if the library is following best practices and common patterns. See any of the Java 8 classes which use static factory methods for instantiation, especially the time library which uses immutable objects created statically and then mutated by member functions consistent with functional programming best practices. The instance returned by the mutation is simply the previous instance mutated according to the function with no other data loss. As the RestDocumentationResultHandler is using a similar static instantiation and here a fluent mutation, it gives the impression it is trying to be functionally manipulated in a similar way and is therefore startling when it does not keep non-snippet things equal. It feels much like calling localDateTime.withHour(12) and then losing the minutes, seconds, date, etc.

**Comment by wilkinsona** [comment]
> The instance returned by the mutation is simply the previous instance mutated according to the function with no other data loss

That’s what’s happening here. It’s just the snippets that are being changed.

> and is therefore startling when it does not keep non-snippet things equal.

At the risk of repeating myself, all non-snippet things remain the same.

**Comment by Lwiczyn** [comment]
Apologies, for some reason I had it in my head that the generation of the default snippets had something to do with the presence of the identifier and request pre/postprocessors. I am not sure where that notion came from, but am now quite sure it was wrong. Thank you for bearing with me. I think I've gotten it all straightened out now.
