### ISSUE TITLE
Questions about subsection documentation

### ISSUE THREAD

**Issue by Koizumi85** [spring-projects/spring-restdocs#465]
Hi,

I have some questions to documentation of subsections:

1. I have enabled pretty-printing of response body with `preprocessResponse(prettyPrint())`. But in subsection snippets, the JSON is not properly formatted. It is printed in a single JSON line. In your documentation, the example is properly formatted. Am I doing something wrong? Or did I forget something?

2. Is it possible to generate snippets which does not contain certain subsections?
So for example if the complete payload looks like the following
```
{
   "field1": "Test",
   "subsection": {
      "field2": "Test 2",
      "field3": "Test 3",
      "field4": "Test 4",
      "field5": "Test 5",
   }
}
```
I would love to have an output like the following
```
{
   "field1": "Test",
   "subsection": {
      ...
   }
}
```

This would make it possible to make different sections for different paths of the response without printing the whole response first and repeating subsections of it afterwards.
If it is not possible, I would make a Ticket for it.

3. Is it possible to create a snippet for a subsection of a payload, which is in fact an entry within an array? I could not manage to make this work for response with following scheme:

```
{
   "positions": [
      {
         items: [
           {
              "description": "item 1"
           }
        ]
      },
      {
        items: [
          {
              "description": "item 2"
          }
       }
   ]
}
```

It is complaining, that the path "positions.[0].items.[0]" is not uniquely identifying a subsection of the payload. Strange thing about this: if it is 1 position with 2 items, it is working, but printing the array instead of a single item of it.

Greetings

**Comment by wilkinsona** [comment]
> Am I doing something wrong? Or did I forget something?

No, this is a bug. Thanks for reporting it. I've opened #466.

> Is it possible to generate snippets which does not contain certain subsections?

There's nothing built-in that specifically addresses this, but you may be able to achieve what you want by using a `ContentModifyingOperationPreprocessor` with a custom `ContentModifier` implementation.

> Is it possible to create a snippet for a subsection of a payload, which is in fact an entry within an array?

No, fields paths don't support specific indexes so you can't address an individual item in a list.

If you'd like to see some enhancements please open separate issues that each address a single improvement.

**Comment by Koizumi85** [comment]
Hi @wilkinsona 

Thanks for the answers. I will try the stuff with a custom ContentModifier. If it is successful, I will contribute it, if you think it is an interesting feature.
