### ISSUE TITLE
When using WebTestClient query string parameters from non-GET requests cannot be documented

### ISSUE THREAD

**Issue by florind** [spring-projects/spring-restdocs#472]
I'd like to allow documenting request parameters in PUT requests. There's currently a built-in constraint to only allow documenting request parameters for GET requests (see https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-webtestclient/src/main/java/org/springframework/restdocs/webtestclient/WebTestClientRequestConverter.java#L86)
I understand that params can be moved in the body of the request but sometimes it makes sense to structure the URL in this way.

**Comment by hho** [comment]
I have the same problem for `POST` requests.

If I don't set a `Content-Type`, I get a NPE at https://github.com/spring-projects/spring-restdocs/blob/v2.0.0.RELEASE/spring-restdocs-webtestclient/src/main/java/org/springframework/restdocs/webtestclient/WebTestClientRequestConverter.java#L91

If I do, the documented parameter is not discovered in the request.
