### ISSUE TITLE
[SRD 1.2.2/1.2.3 only] SnippetException for array fields  which are both null and not null for a JSON request/response 

### ISSUE THREAD

**Issue by bessels** [spring-projects/spring-restdocs#475]
After updating SRD from 1.1.2 to 1.2.3 several existing unit tests which generated REST documentation resulted in a SnippetException. Can you perhaps check if there is a link between #398 and #428 - which were included in 1.2.2. All SRD versions between 1.1.2 and 1.2.1 work fine for our unit tests.

Partial and edited snippet from #428: "When a path identifies multiple values with a mixture of null and non-nulls (for example a.[].b and the payload {"a":[ {"b": null},{"b": 1}]} it results in the following exception: org.springframework.restdocs.snippet.SnippetException: Fields with the following paths were not found in the payload: [data.Addresses[].suffix]. 
Specified as fieldWithPath("data.Addresses[].suffix").description("Suffix for address")

Iirc when it was first not optimally specified as
fieldWithPath("data.Addresses[0].suffix").description("Suffix for address")
fieldWithPath("data.Addresses[1].suffix").description("Suffix for address")
the error was: SnippetException: Fields with the following paths were not found in the payload: [data.Addresses[0].suffix], [data.Addresses[1].suffix]. Hence both got mentioned. 

I've checked all tests which were broken and iirc they all had the situation with a field in an array wich was both null and not null for the request/response.

I debugged SRD and found in method findMissingFields(List<FieldDescriptor>) a workaround which worked for me. isNestedBeneathMissingOptionalField gave me the idea to make add .optional() to FieldWithPath.

Actually I have two workarounds:
1) Add .optional to fields which give an error.
2) Changing fields in a request so that in the request or the response the field was always not null. Can't remember if it also works if both are null.

_In our documentation we don't mention if a field is optional or not. Does my .optional() workaround has side effect i've to consider?_

Software:
Spring Rest Docs: 1.2.3
Spring 4.3.7.RELEASE

_Note: I've also noticed that 1.2.3 is stricter/better then 1.1.2. It turned out we had not specified all fiels with fieldWithPath (for the same tests which broke due to the array issue) and this did not gave an exception. Normally SRD correctly gives an exception._

I'm not sure if this is a bug or that its by design. Either way I would appreciate it, if you could look into this.

**Comment by wilkinsona** [comment]
Assuming I have understood your description correctly, this is working as designed. 1.2.2 fixed a bug (#398) where a field that is both null and non-null didn't have to be optional for the test to pass. So, adding `optional()` isn't a workaround, but is what should have been required all along.

**Comment by wilkinsona** [comment]
It's hard to answer that without a concrete example. It could be #402.

**Comment by bessels** [comment]
Thanks. The ticket can be closed.
