### ISSUE TITLE
Different behaviour when displaying query params in snippets when using mockMvc or Rest-assured

### ISSUE THREAD

**Issue by pvardanega** [spring-projects/spring-restdocs#476]
I found a different behaviour when writing snippets which contain an URL with query parameters dependending if using mockMvc or Rest-assured. The problem is present in at least curl-request, http-request and httpie-request snippets.

Both converters [RestAssuredRequestConverter](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-restassured/src/main/java/org/springframework/restdocs/restassured3/RestAssuredRequestConverter.java#L57) and [MockMvcRequestConverter](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-mockmvc/src/main/java/org/springframework/restdocs/mockmvc/MockMvcRequestConverter.java#L68) return an `OperationRequest` that is built from (at least) the URI and the query parameters. The URI created already contains the query parameters. Then, [other query parameters are added if they are not present yet](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-core/src/main/java/org/springframework/restdocs/cli/CurlRequestSnippet.java#L86).

The problem I have is when there are multiple times the same query parameter with different values. For instance, the URL `https://example.com?param=1&param=2` will be generated as described if using mockMvc and `https://example.com?param=1&param=2&param=1,2` if using Rest-assured.

The root cause is that [mockMvc](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-mockmvc/src/main/java/org/springframework/restdocs/mockmvc/MockMvcRequestConverter.java#L173) each value of the same param is added as an item in the parameters' list. Where for [Rest-assured](https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-restassured/src/main/java/org/springframework/restdocs/restassured3/RestAssuredRequestConverter.java#L143) only the value corresponding to the result of `List#toString()` is added.
The consequence is that when checking if the parameters are already added in the URL, for mockMvc it finds that they are already added but not for Rest-assured.

If you acknowledge the issue, I can provide a pull request.

**Comment by wilkinsona** [comment]
Thanks for the detailed report and analysis. What you've identified does indeed look like a bug. A pull request would be most welcome.

**Comment by wilkinsona** [comment]
Closing in favour of PR #477.
