### ISSUE TITLE
Add support for RestTemplate

### ISSUE THREAD

**Issue by hadjiski** [spring-projects/spring-restdocs#478]
According to https://docs.spring.io/spring-restdocs/docs/current/reference/html5/ the following frameworks are supported: Spring MVC’s test framework, Spring WebFlux’s WebTestClient or REST Assured 3

Many component tests though are using just simple RestTemplate, without having the need to add any of the dependencies mentioned above. Now just to use restdocs those component tests must be changed to use let's say rest assured 3.

Would it be possible to add restdocs support for RestTemplate usage?

**Comment by wilkinsona** [comment]
I think it might be possible to support RestTemplate, but I don't think it's worth the initial engineering effort or the ongoing maintenance cost. Spring Framework's WebTestClient is the preferred, modern replacement for RestTemplate and, as you've noted above, it's already supported by REST Docs. Thanks anyway for the suggestion.

**Comment by hadjiski** [comment]
@wilkinsona "WebTestClient is a replacement for RestTemplate" since when? I did not know about that. Can u point me to an article or documentation to read more about this replacement? Would gladly update our tests.

**Comment by wilkinsona** [comment]
Sorry, replacement probably wasn't quite the right word. `RestTemplate` is still part of Spring Framework 5. However, WebClient and WebTestClient are the preferred alternatives now.

**Comment by hadjiski** [comment]
Got it, but can u point me to an article or documentation explaining how and why WebTestClient is the preferable option over RestTemplate. Thanks

**Comment by wilkinsona** [comment]
Sorry, I'm not aware of such an article.

**Comment by mspiess** [comment]
Any chance to reconsider this?
`RestTemplate` does not seem to go away any time soon.
This could also support the new [RestClient](https://docs.spring.io/spring-framework/reference/6.1/integration/rest-clients.html#rest-restclient) with its static method [`create(RestTemplate)`](https://docs.spring.io/spring-framework/docs/6.1.0-RC2/javadoc-api/org/springframework/web/client/RestClient.html#create(org.springframework.web.client.RestTemplate)).

**Comment by mspiess** [comment]
Thanks for pointing me to https://github.com/spring-projects/spring-framework/issues/31275! I will definitely keep an eye on it.
I'd just like a way to generate docs from integration tests, without having to include WebFlux or a third-party dependency.
I just assumed that a lot of the effort for supporting `RestTemplate` and a potential `RestTestClient` would be shared, as I've read that `RestClient` uses `RestTemplate` infrastructure, but from your comment I gather that that's not (necessarily) the case.
