### ISSUE TITLE
NPE when using WebTestClient and documenting a non-GET request with no Content-Type header

### ISSUE THREAD

**Issue by jntakpe** [spring-projects/spring-restdocs#479]
With webflux if the response status is 204 (no content) documenting response fails with a NPE inside WebTestClientRequestConverter.extractParameter since `result.getRequestHeaders().getContentType()
				.equals(MediaType.APPLICATION_FORM_URLENCODED)` doesn't have a content type

**Comment by wilkinsona** [comment]
@jntakpe The response status (204) should have no effect on the headers in the request. It sounds like you may be trying to document a non-GET request with no `Content-Type` request header. Is that the case?

**Comment by jntakpe** [comment]
Yes that's an DELETE request
