### ISSUE TITLE
Junit5 extension does not generate snippet when ran in gradle

### ISSUE THREAD

**Issue by kkocel** [spring-projects/spring-restdocs#489]
I've found out that when I run tests in my IDE snippets are generated, but when I run them in gradle it turns out that they're not.

**Comment by wilkinsona** [comment]
I suspect that's due to a problem with your Gradle setup. The JUnit 5 sample works for me. If you'd like me to investigate further, please provide a sample that demonstrates your problem.

**Comment by kkocel** [comment]
I don't have a direct link so I'm sharing zip :)

[OpenBrewery_BE-master-98528f5028aece5828d91477557f8a743b718886.zip](https://github.com/spring-projects/spring-restdocs/files/1797662/OpenBrewery_BE-master-98528f5028aece5828d91477557f8a743b718886.zip)

**Comment by wilkinsona** [comment]
As suspected, the problem's in your Gradle setup. You haven't customised the class names that JUnit Platform will look at for tests so no tests are run. You can fix the problem by adding the following to your build.gradle:

```groovy
junitPlatform {
    filters {
        includeClassNamePattern '.*Documentation'
    }
}
```

**Comment by kkocel** [comment]
Yes this was it!
