### ISSUE TITLE
Unlike Asciidoctor’s built-in macros, operation macro does not support substitution in its target

### ISSUE THREAD

**Issue by jamesfoster** [spring-projects/spring-restdocs#491]
To allow referring to operations using attribute substitution, such as:
 
`operation::{prefix}-name[]`

Requires a change to the following file to call `sub-attributes`:

>spring-restdocs-asciidoctor/src/main/resources/extensions/operation_block_macro.rb

```ruby
def process(parent, operation, attributes)
  operation = parent.sub_attributes operation  # << --
...
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I think I can see how that might be useful, but can you please describe your particular use-case for using `{prefix}`.

@mojavelinux I'd appreciate your input here if you have a moment. What do you think of a macro allowing substitutions in its target as proposed above?

**Comment by jamesfoster** [comment]
I want to wrap the call to the `operation::` in a common include as we'd like to put some markup around the snippets.

```
:operation-name: my-operation
inlucde::operation.adoc[]
```

>operation.adoc
```
// My custom preamble for {operation-name}
operation::{operation-name}[]
// Wrapping up
```

Not sure there's a nicer way of doing that but hoped that it would work.

**Comment by mojavelinux** [comment]
It's generally recommended to support attribute substitution in the target of a macro. All the built-in macros in Asciidoctor support this, so I think it's the right move.

**Comment by wilkinsona** [comment]
Thanks very much, @mojavelinux.

@jamesfoster, thanks for the additional explanation. Given that all of Asciidoctor’s built-in macros support this, REST Docs’ should too. I’ll correct that in the next maintenance release.

**Comment by jamesfoster** [comment]
Thanks :)

**Comment by jamesfoster** [comment]
When is 1.2.4 due to be released?

**Comment by jamesfoster** [comment]
@wilkinsona Did this make it into 1.2.4-RELEASE? We updated but we're still getting

```
Snippet http-response not found at /build/generated-snippets/{operation-name}/http-response.adoc for operation {operation-name}
```

**Comment by wilkinsona** [comment]
Yes, it should be in 1.2.4 as shown in [the commit](https://github.com/spring-projects/spring-restdocs/commit/0b0c9e1cc44932a563f21d935ec84bf5d84f7c18) that closed the issue.

**Comment by jamesfoster** [comment]
Apologies, it is working. :) We updated `spring-restdocs-core` and `spring-restdocs-mockmvc` but not `spring-restdocs-asciidoctor`

Thanks
