### ISSUE TITLE
Backport Bean Validation 2.0 new constraints

### ISSUE THREAD

**Issue by ylegat** [spring-projects/spring-restdocs#509]
Hello!

Do you think it would be possible to backport in 1.x the constraint annotations that were introduced by Bean Validation 2.0?

#454 was dealing with this task for version 2.x

Thanks for your feedback!

**Comment by wilkinsona** [comment]
Unfortunately not. 1.2.x is in maintenance mode where adding new functionality that depends on new major versions of the Bean Validation API and Hibernate Validator isn't appropriate.

**Comment by ylegat** [comment]
Ok, I understand
