### ISSUE TITLE
Build Failure on mvn package command [ cd samples/rest-notes-spring-hateoas ]

### ISSUE THREAD

**Issue by bismoy2013** [spring-projects/spring-restdocs#51]
Getting this message on my terminal . Hope someone can help me on this .

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ rest-notes-spring-hateoas ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /Users/bismoymurasing/Desktop/OpenSource/spring-restdocs/samples/rest-notes-spring-hateoas/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:47 min
[INFO] Finished at: 2015-04-17T16:37:41+05:30
[INFO] Final Memory: 16M/80M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rest-notes-spring-hateoas: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by wilkinsona** [comment]
> Fatal error compiling: invalid target release: 1.8

The sample requires Java 8 and you're trying to compile with an earlier JDK.

I should probably update the README to make it clear that, while the project itself works fine with Java 7, the samples need to be built with Java 8.

**Comment by bismoy2013** [comment]
Hmmm that makes things much clear now . Thanks :)

**Comment by wilkinsona** [comment]
Reopening to remind me to update the README

**Comment by bismoy2013** [comment]
Ah sure, that Java 7 thing will certainly help those who didn't still update their Java version .

**Comment by wilkinsona** [comment]
On seconds thoughts, it'll make things simpler if the samples and main project have the same Java version requirement. I'll update the samples to build with Java 7.
