### ISSUE TITLE
Is any way to implement Spring - Restdocs on a Java 1.6 project?

### ISSUE THREAD

**Issue by laureano-clausi** [spring-projects/spring-restdocs#512]
Hi there!
We are developers and we are searching how to implement Restdoc on a project with Java V1.6. Is that possible? How?
Thanks in advance.
Regards.

**Comment by wilkinsona** [comment]
No, sorry, it isn’t possible. REST Docs 1.x requires Java 7 and REST Docs 2.x requires Java 8. Perhaps you could use a Java 7 or later VM to run your tests while still using Java 6 at runtime?
