### ISSUE TITLE
POST with application/x-www-form-urlencoded is generating request snippets with content in body and query string params

### ISSUE THREAD

**Issue by jarheadjred** [spring-projects/spring-restdocs#514]
I have an application with a simple zuul route that forwards to another service.

I've setup a RestDoc test to invoke the routed path with a POST and content.
```
mockMvc.perform(
   post("/ivr/auth/brand/{brand}/protocol/openid-connect/token", "mybrand")
      .contextPath("/ivr")
      .contentType(MediaType.APPLICATION_FORM_URLENCODED)                        
      .content("grant_type=client_credentials&client_id=democlient&client_secret=43310292-83d4-44f4-9b47-6536f0d6f6f6"))
   .andExpect(
      status().isOk())
   .andDo(document("authentication-token-example") 
```

That results in the request being successfully served, but the generated `curl-request.adoc` and `request-fields.adoc`  having the body documented correctly but it incorrectly appends the parameters onto the query string.

```
[source,bash]
----
$ curl 'https://localhost:8080/ivr/auth/brand/mybrand/protocol/openid-connect/token?grant_type=client_credentials&client_id=democlient&client_secret=43310292-83d4-44f4-9b47-6536f0d6f6f6' -i -X POST \
    -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
    -d 'grant_type=client_credentials&client_id=democlient&client_secret=43310292-83d4-44f4-9b47-6536f0d6f6f6'
----
```

When I try to use the perform().param() syntax to provide the form data instead of the .perform.content() then my request fails as there seems to be some incompatibility with the way that the org.springframework.cloud.netflix.zuul.filters.pre.FormBodyWrapperFilter interacts with a org.springframework.mock.web.MockHttpServletRequest

Any ideas on how I can get the generated snippets for the request to not add the form parameters as query string parameters?

**Comment by jarheadjred** [comment]
Here are my gradle dependencies snippets for applicable libraries:

```
+--- org.springframework.boot:spring-boot-starter-web: -> 2.0.2.RELEASE (*)
+--- org.springframework.cloud:spring-cloud-starter-netflix-zuul: -> 2.0.0.RC2
+--- org.springframework.restdocs:spring-restdocs-mockmvc: -> 2.0.1.RELEASE
+--- org.springframework.cloud:spring-cloud-contract-wiremock: -> 2.0.0.RC2
```

I think there is an incompatibility with how MockMvc handles forwarded requests. I see it's not really suported. But, it generally works from the restdocs perspective when I pass querystring params in the url, and when I pass the form content as body. If I try using `post(...).params(...)` then I can only make assertions on the `MockMvcResultMatchers.forwarded*` related parts.

**Comment by jarheadjred** [comment]
Here is a small demo project https://github.com/jarheadjred/spring-restdocs-zuul-issue

**Comment by wilkinsona** [comment]
Thanks for the sample. I've successfully reproduced the problem.

Both `MockMvc` and `WebTestClient` are affected with the root cause being that the parameters from a URL-encoded form data request body into the request's parameters. In the `MockMvc` case this is done by the request builder in Spring Framework. In the `WebTestClient` case it's done by REST Docs and has been since the `WebTestClient` support was first introduced.

In terms of the generated snippets, three are affected:

Curl request:
```
[source,bash]
----
$ curl 'https://api.mydomain.com/api/auth/brand/demobrand/protocol/openid-connect/token?grant_type=client_credentials&client_id=pub-ivr-democlient&client_secret=470d588e-29b9-4f10-a04b-28f52addfb25' -i -X POST \
    -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
    -d 'grant_type=client_credentials&client_id=pub-ivr-democlient&client_secret=470d588e-29b9-4f10-a04b-28f52addfb25'
----
```

HTTP request:
```
[source,http,options="nowrap"]
----
POST /api/auth/brand/demobrand/protocol/openid-connect/token?grant_type=client_credentials&client_id=pub-ivr-democlient&client_secret=470d588e-29b9-4f10-a04b-28f52addfb25 HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Host: api.mydomain.com
Content-Length: 109

grant_type=client_credentials&client_id=pub-ivr-democlient&client_secret=470d588e-29b9-4f10-a04b-28f52addfb25
----
```

HTTPie request:
```
[source,bash]
----
$ echo 'grant_type=client_credentials&client_id=pub-ivr-democlient&client_secret=470d588e-29b9-4f10-a04b-28f52addfb25' | http POST 'https://api.mydomain.com/api/auth/brand/demobrand/protocol/openid-connect/token?grant_type=client_credentials&client_id=pub-ivr-democlient&client_secret=470d588e-29b9-4f10-a04b-28f52addfb25' \
    'Content-Type:application/x-www-form-urlencoded;charset=UTF-8'
----
```
