### ISSUE TITLE
Generated restdocs path with bootJar task is wrong.

### ISSUE THREAD

**Issue by Pyohwan** [spring-projects/spring-restdocs#522]
I found out this sample code in Getting started.
```gradle
bootJar {
	dependsOn asciidoctor 
	from ("${asciidoctor.outputDir}/html5") { 
		into 'static/docs'
	}
}
```
### Steps
1. `gradlew clean build`
2. `unzip build/libs/sample.jar`

```
...
   creating: static/
   creating: static/docs/
  inflating: static/docs/index.html  
```

Expected generated html are `BOOT-INF/classes/static/docs` instead of `static/docs`.
And `http://localhost:8080/docs/index.html` is 404 not found.

**Comment by wilkinsona** [comment]
> Expected generated html are BOOT-INF/classes/static/docs instead of static/docs.

Why do you expect them to be in `BOOT-INF/classes`? Spring Boot's static resource handling will serve resources from `classpath:static`. Both `/BOOT-INF/classes/static` and `/static` meet that requirement.

I've just built REST Docs' Spring HATEOAS-based sample to verify the behaviour. The documentation was packaged in `static/docs` and was available at `http://localhost:8080/docs/api-guide.html` and `http://localhost:8080/docs/getting-started-guide.html`

> And http://localhost:8080/docs/index.html is 404 not found.

If that's the case then there's something else going on. I can't tell what as you haven't really described your application. If you'd like me to spend some more time investigating, please spend some time providing a small sample that illustrates the behaviour you have described.

**Comment by Pyohwan** [comment]
@wilkinsona 
sorry. my mistake. configuration was not correct.
