### ISSUE TITLE
asciidoctor-gradle-plugin 1.5.8 and 1.5.8.1 problems (kind of solved)

### ISSUE THREAD

**Issue by watchwithmike** [spring-projects/spring-restdocs#529]
Without making changes to an existing repository, my docs began failing with many instances of this message appearing while generated docs:

```
dropping line containing reference to missing attribute: snippets
```

I previously had the `asciidoctor-gradle-plugin` defined as follows:

```gradle
buildscript {
    repositories {
        maven { url 'http://repo.spring.io/plugins-release' }
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.+'
    }
}
```

This appears to have picked up a [1.5.8](https://mvnrepository.com/artifact/org.asciidoctor/asciidoctor-gradle-plugin/1.5.8) version.  I then tried using [1.5.8.1](https://mvnrepository.com/artifact/org.asciidoctor/asciidoctor-gradle-plugin/1.5.8.1) and got the same result.

Only by rolling back to `1.5.7` was I able to get things working again.

```gradle
buildscript {
    repositories {
        maven { url 'http://repo.spring.io/plugins-release' }
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.7'
    }
}
```

This looks like it might possibly be related to #527 but I didn't see a reference to the plugin there.  I'm not entirely sure what the relationship is between all these plugins so it's quite possible this is just an issue with the asciidoctor-gradle-plugin.

**Comment by watchwithmike** [comment]
I'm going to close this for now.  I thought this change fixed it but I'm still getting the error but in a different format.  More investigation is required.  Sorry for the noise.

**Comment by watchwithmike** [comment]
If anyone happens to look at this issue, I have no idea what sort of cycle I got into but it would seem I was pulling a bad version of something or somebody rolled forward a version that fixed things.  I ended up just reverting back to all my previous definitions, re-ran the asciidoctor task and it just start working.  The only strange bit I still seem to get every now and then is this:

```
2018-07-16T14:08:56.125-07:00 [Task worker for ':'] WARN Ruby : Warning: not setting network stack system property because socket subsystem may already be booted.If you need this option please set it manually as a JVM property.
Use JAVA_OPTS=-Djava.net.preferIPv4Stack=true OR prepend -J as a JRuby option.
```

But my docs are generating so I'm leaving this closed and carrying on...

**Comment by wilkinsona** [comment]
Are you using REST Docs’ Asciidoctor extension? I wonder if you’re being affected by https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/222. I’m doubtful that’s the problem, though. If it was, I don’t think rolling back to 1.5.7 would have helped.

**Comment by watchwithmike** [comment]
Thank you @wilkinsona for that link!  I went back to `1.5.3` and I'm now getting consistent results across builds, project and platforms.
