### ISSUE TITLE
Diagnostics are poor when using JUnit 5 and accidentally using @BeforeAll rather than the required @BeforeEach

### ISSUE THREAD

**Issue by 1lln3ss** [spring-projects/spring-restdocs#538]
Hi,

I updated a project with spring-boot-dependencies to 2.0.4.RELEASE this morning, which in turn updated spring-restdocs dependency to version 2.0.2.RELEASE (upgraded from 2.0.1.RELEASE).  I am also using spring-restdocs-restassured.

The version update of spring-restdocs to 2.0.2.RELEASE seems to cause the following issue when invoking `requestSpec.when().get("/myUri")`:

```
java.lang.NullPointerException
	at org.springframework.restdocs.ManualRestDocumentation.beforeOperation(ManualRestDocumentation.java:89)
	at org.springframework.restdocs.RestDocumentationExtension.lambda$resolveParameter$0(RestDocumentationExtension.java:58)
	at org.springframework.restdocs.restassured3.RestAssuredRestDocumentationConfigurer.filter(RestAssuredRestDocumentationConfigurer.java:69)
	at org.springframework.restdocs.restassured3.RestAssuredOperationPreprocessorsConfigurer.filter(RestAssuredOperationPreprocessorsConfigurer.java:46)
	at io.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
	at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
```

From a quick debugging, I could find that `ManualRestDocumention `doesn't have a context (is null) when `RestDocumentationExtension.resolveParameter(...)` invokes `beforeOperation()`.  I also found that `RestDocumentationExtension` was modified in 2.0.2.RELEASE.

When I force spring-restdocs dependencies to version 2.0.1.RELEASE (while keeping spring-boot-dependencies to version 2.0.4.RELEASE), the issue goes away.

See also, [stackoverflow post](https://stackoverflow.com/questions/51672764/nullpointer-with-spring-restdocs-2-0-2-release-with-restassured)

Thanks.

**Comment by 1lln3ss** [comment]
Here is a public project to reproduce: [https://github.com/1lln3ss/issue-538](url)
Running the test will show the issue.

**Comment by wilkinsona** [comment]
Thanks for the sample. The failure's due to a mistake in your code, but REST Docs' is doing a poor job of dealing with that mistake. We can use this issue to improve that.

The mistake in your code is that REST Docs' context is method-scoped but you are setting it up in a `@BeforeAll` method which makes it class-scoped. As shown in the [JUnit 5 sample](https://github.com/spring-projects/spring-restdocs/blob/26e5cddb458bea56f125e6c1b108b856287f7950/samples/junit5/src/test/java/com/example/junit5/SampleJUnit5ApplicationTests.java#L45), you should use `@BeforeEach` rather than `@BeforeAll`. This worked previously as `RestDocumentationExtension` was stateful so the incorrect scoping was hidden. Extensions should not be stateful (and this was corrected in REST Docs 2.0.2) which is why the mistake has now caused a problem.

**Comment by wilkinsona** [comment]
@sbrannen I think I'd like to return `false` from `ParameterResolver.supportsParameter` when it's called for a `@BeforeAll` method. Assuming that's a reasonable thing to do, is there a recommended way for a `ParameterResolver` to distinguish between a method context and a class context? Looking at `supportsParameter(ParameterContext, ExtensionContext)`, the `ExtensionContext` will be a `MethodExtensionContext` or a `ClassExtensionContext` but both are internal. Is calling `getTestMethod()` and checking for empty a robust way to identify a class extension?

**Comment by sbrannen** [comment]
I think the following should be robust enough:

```java
boolean classLevel = extensionContext.getTestClass().isPresent()
		&& !extensionContext.getTestMethod().isPresent();
```

**Comment by sbrannen** [comment]
For example:

```java
	static class FooParameterResolver implements ParameterResolver {

		@Override
		public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {

			boolean classLevel = extensionContext.getTestClass().isPresent()
					&& !extensionContext.getTestMethod().isPresent();

			if (classLevel) {
				return false;
			}

			return int.class == parameterContext.getParameter().getType();
		}

		@Override
		public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
			return 42;
		}

	}

	@ExtendWith(FooParameterResolver.class)
	static class FooTestCase {

		@BeforeAll
		@AfterAll
		static void all() { // int i) {
		}

		@BeforeEach
		@Test
		@AfterEach
		void intPrimitive(int i) {
		}
	}
```

If you change the signature of `FooTestCase.all()` to `all(int i)`, the test case will then fail due to a lack of a suitable `ParameterResolver`.

**Comment by sbrannen** [comment]
Note: I'm condoning the use of `@BeforeEach` and `@AfterEach` on a `@Test` method. 😉

**Comment by wilkinsona** [comment]
Thank you, @sbrannen!
