### ISSUE TITLE
One rest API doc for multiple controllers in different modules, 

### ISSUE THREAD

**Issue by narayana11ec105** [spring-projects/spring-restdocs#559]
We have a project setup where we have multiple controllers, each serving different purposes and is a separate maven module, running as part of one service. Can we generate apidoc using spring-restdocs for this service which comprises of all the endpoints from all the controllers with request examples?

**Comment by wilkinsona** [comment]
Yes, you can. You’d either run the tests that use REST Docs against the whole service or run the tests against each individual module and then pull things together in a separate post-processing step.

Either approach is really outside the scope of REST Docs itself. It’s more a question of build and test structure.
