### ISSUE TITLE
URL special characters are encoded in generated docs

### ISSUE THREAD

**Issue by Odyldzhon** [spring-projects/spring-restdocs#560]
Thank you for this wonderful project!

I have a case where URL have field with special characters ([RSQL](https://github.com/jirutka/rsql-parser)), for example:
`http://tv/1/movies?query=director.lastName==Nolan and year>=2000`

In a generated document all special characters will be encoded and the query becomes unreadable.
It happens because the method below encode special characters `org.springframework.restdocs.mockmvc.RestDocumentationRequestBuilders.get(urlTemplate , urlVariables)`.

This is how it looks in test for url="tv/{id}/movies?query=director.lastName==Nolan and year>=2000"
```java
.mockMvc
        .perform(get(url, 1)
        ...
        .andDo(generateDoc())
```

Is there any solution or at least workaround to decode the URL for generated document?

**Comment by wilkinsona** [comment]
Which of the generated snippets are you interested in?

**Comment by Odyldzhon** [comment]
Maybe it's working as designed but assume the case described above.
We have endpoint:
> http://tv/1/movies?query=director.lastName==Nolan and year>=2000

In the generated document we are going to show example using snippet:
> http://tv/1/movies?query%3Ddirector.lastName%3D%3DNolan+and+year%3E%3D2000

The example becomes unreadable and doesn't have any sense. I understand that maybe this is not good designed endpoint but this is actually what we have and some how will be nice do document.

It will be nice to have option for that case i.e. to decode a request for documentation.

**Comment by wilkinsona** [comment]
IMO, that isn't unreadable. It's exactly how to URL needs to be when making an HTTP request so I'd argue that it makes sense in the context of an HTTP request snippet. On the other hand, if the URL is also encoded like that in, for example, the curl request snippet, then I think there's room for improvement. As far as I know, curl will encode automatically so, if that's the case, the URL in the snippet should be unencoded.

**Comment by Odyldzhon** [comment]
Thanks, will be nice to have any snippet with no encoded request. Currently curl snippet have encoded request as well.

**Comment by wilkinsona** [comment]
I was mistaken about curl as it does not automatically encode the URL. Providing snippets that do not encode the URL, and therefore may not work without modification, is outside of the scope of REST Docs as the intent of the project is to provide accurate, tested snippets that can be used as-is. Thanks anyway for the suggestion.
