### ISSUE TITLE
responseFields with HATEOAS info duplicated

### ISSUE THREAD

**Issue by umanking** [spring-projects/spring-restdocs#566]
#### situation
when I make RestDocs in TestCode, I would make HATEOAS link information
but to do make responseFields, I got some error

error like that
```java
org.springframework.restdocs.snippet.SnippetException: The following parts of the payload were not documented:
{
  "_links" : {
    "query-events" : {
      "href" : "http://localhost:8080/api/events"
    },
    "self" : {
      "href" : "http://localhost:8080/api/events/1"
    },
    "update-event" : {
      "href" : "http://localhost:8080/api/events/1"
    }
  }
}
```

I know how to do solve this problem 
1. relaxedResponseField
2. write the following _links.query-events.href information
but, why don't you make another method like `fieldWithHalPath` ?

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we don’t want the suppprt for documenting fields to have any knowledge of the structure of hypermedia link formats. That knowledge is already present in the [hypermedia support](https://docs.spring.io/spring-restdocs/docs/2.0.2.RELEASE/reference/html5/#documenting-your-api-hypermedia) which is what I recommend that you use. When documenting the fields, use `subsectionWihPath(`_links)
