### ISSUE TITLE
Adding path in WebTestClient URI customization?

### ISSUE THREAD

**Issue by kkocel** [spring-projects/spring-restdocs#572]
I would like to define default uri with a path that would mask real address and port. Is it possible?

In the documentation there is example with an URI without a path. ( https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#configuration-uris-webtestclient )

**Comment by wilkinsona** [comment]
There's nothing available out of the box that will allow you to use a fake path in the URI. You could implement something yourself as an `OperationPreprocessor`, perhaps using the code in `UriModifyingOperationPreprocessor` as inspiration.

I can't think of a use case for what you're trying to do. Without one, a change to REST Docs cannot be considered. What's causing you to want to have a "fake" path in the documented URIs?

**Comment by kkocel** [comment]
In my use case I don't have any gateway/edge server and all services are served on a path prefix. That's why I want to include such prefix in my documentation. Such prefix is somewhat fake from service perspective but from user perspective it's totally valid.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
