### ISSUE TITLE
Configurable path to templates

### ISSUE THREAD

**Issue by yalinhuang** [spring-projects/spring-restdocs#574]
It would be great to configure the template path, instead of the hard-coded `org/springframework/restdocs/templates/` as in https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-core/src/main/java/org/springframework/restdocs/templates/StandardTemplateResourceResolver.java#L79

**Comment by wilkinsona** [comment]
I'm not sure that I want to add any complexity to support that. Can you please describe how this feature would be useful to you? Also, please note that it's already possible to take control of template resolution by REST Docs to use a template engine with your own `TemplateResourceResolver` implementation.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
