### ISSUE TITLE
Content missing in http-request.adoc when...

### ISSUE THREAD

**Issue by amikmr1** [spring-projects/spring-restdocs#578]
@wilkinsona 

Just a heads-up that the **JSON request-content** is missing in **http-request.adoc** when

    testCompile 'org.springframework.restdocs:spring-restdocs-mockmvc:2.0.1.RELEASE'

is used along with these dependencies: 

    compile 'org.springframework.boot:spring-boot-starter-**web**:2.1.2.RELEASE' &
    testCompile 'org.springframework.boot:spring-boot-starter-**test**:2.1.2.RELEASE'
  
Thanks and best wishes,
~amit

**Comment by wilkinsona** [comment]
Duplicates #515.
