### ISSUE TITLE
NoSuchBeanDefinitionException when configuring test that uses WebTestClient as described in the user guide

### ISSUE THREAD

**Issue by jnizet** [spring-projects/spring-restdocs#582]
The instructions in https://docs.spring.io/spring-restdocs/docs/2.0.3.RELEASE/reference/html5/#getting-started-documentation-snippets-setup cause an exception to be thrown. Replacing WebApplicationContext with ApplicationContext makes the test pass.

Here's a complete minimal project reproducing the issue: https://github.com/jnizet/webtestclientrestdocsissue

[This test with WebApplicationContext](https://github.com/jnizet/webtestclientrestdocsissue/blob/master/src/test/java/com/example/demo/web/UserControllerWithWebApplicationContextDocTest.java) fails, but [this test with ApplicationContext](https://github.com/jnizet/webtestclientrestdocsissue/blob/master/src/test/java/com/example/demo/web/UserControllerWithApplicationContextDocTest.java) passes.

**Comment by wilkinsona** [comment]
Thanks for the sample. `WebApplicationContext` is Servlet-specific so the docs are wrong for the `WebTestClient` case where the context is likely to be for a reactive web app.

**Comment by jnizet** [comment]
Thanks for the explanation. That's what I suspected.

**Comment by wimdeblauwe** [comment]
Just ran into this as well. Will be good if this is fixed, would have avoided my SO question (https://stackoverflow.com/questions/55138027/spring-rest-docs-with-junit-5-and-webflux) :-)
