### ISSUE TITLE
can i document map with dynamic key?

### ISSUE THREAD

**Issue by yepapa** [spring-projects/spring-restdocs#587]
i have a response with dynamic key

```
public class GroupListResponse {
    private Map<GroupUserInfo, Set<GroupInfo>> groupMap;
}
```

and response

```
{
  "groupMap" : {
    "UserInfo(characterId=1, userId=400, tag=null)" : [ {
      "groupId" : "400",
      "groupType" : "BRAWL",
      "name" : "brawl",
      "memberCount" : 10
    } ]
  }
}
```

can i document map with dynamic key?

**Comment by wilkinsona** [comment]
Yes, as [described in the documentation](https://docs.spring.io/spring-restdocs/docs/2.0.x/reference/html5/#documenting-your-api-request-response-payloads-fields-json-field-paths), you can use `*`. In your example, you'd use the following:

- `groupMap.*.[].groupId`
- `groupMap.*.[].groupType`
- `groupMap.*.[].name`
- `groupMap.*.[].memberCount`
