### ISSUE TITLE
Error when using requestFields

### ISSUE THREAD

**Issue by kasperbisgaard** [spring-projects/spring-restdocs#588]
I am getting an error when i add requestFields to my documentation.
`org.springframework.restdocs.snippet.SnippetException: Cannot document request fields as the request body is empty`

The request is NOT empty. The users is being created perfectly and the test passes if i remove the requestFields.

This is my test method:

```
Map<String, Object> userRequest = new HashMap<>();
userRequest.put("email", "test@testing.com");
userRequest.put("password", "testpass");
userRequest.put("passwordConfirmation", "testpass");
userRequest.put("birthday", new Date());
userRequest.put("countryCode", "DKN");
userRequest.put("phoneNumber", "99999999");
userRequest.put("about", "Testing");
userRequest.put("gender", "MALE");
userRequest.put("location", "Somewhere");
userRequest.put("website", "www.testing.com");
userRequest.put("firstName", "John");
userRequest.put("lastName", "Doe");

mockMvc
        .perform(post("/users")
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .accept(MediaTypes.HAL_JSON_VALUE)
                .content(objectMapper.writeValueAsString(userRequest)))
        .andExpect(status().isCreated())
        .andDo(document("users/create-user",
                requestFields(
                        fieldWithPath("email").description("User email address"),
                        fieldWithPath("password").description("User password"),
                        fieldWithPath("passwordConfirmation").description("User password confirmed"),
                        fieldWithPath("countryCode").description("Country code 3 characters"),
                        fieldWithPath("phoneNumber").description("Phone number"),
                        fieldWithPath("firstName").description("First name"),
                        fieldWithPath("lastName").description("Last name"),
                        fieldWithPath("location").description("Geographical location"),
                        fieldWithPath("birthday").description("Birthday - format: YYYY-MM-DD"),
                        fieldWithPath("about").description("About text"),
                        fieldWithPath("gender").description("Gender - MALE or FEMALE"),
                        fieldWithPath("website").description("Website")
                ),
                links(
                        linkWithRel("self").description("Self reference link"),
                        linkWithRel("profile").description("Link to the users profile")
                ),responseFields(
                        fieldWithPath("email")
                                .type(JsonFieldType.STRING)
                                .description("User email"),
                        subsectionWithPath("_links").ignored()
                )
        ));
```

I am using version: 2.0.1.RELEASE

**Comment by wilkinsona** [comment]
There are lots of tests for this and no one else that I'm aware of his encountered the same problem, so I think it must be specific to something that you're doing. Unfortunately, I can't tell what that might be from the snippet provided. Can you please provide a complete and minimal sample that reproduces the problem?

**Comment by kasperbisgaard** [comment]
Hi @wilkinsona 
Thank you for the answer!
I created a new project using spring initializer with rest docs dependency and then i took the pom.xml file from there. Now it works.
I'm not sure if it was the change from version 1.5.5 to 1.5.3, or if it was because i was missing the spring-boot-maven-plugin.

**Comment by wilkinsona** [comment]
Glad to hear you got it working. Thanks for letting me know.

**Comment by perryrobinson** [comment]
Hey @bsgrd 
I am actually running into this same issue on a project. I am using gradle and have this in my `build.gradle` file: 

> compile 'org.springframework.restdocs:spring-restdocs-mockmvc:2.0.0.RELEASE'

I am confused by what exactly you changed to correct this. What did you change from version 1.5.5 to 1.5.3?

**Comment by wilkinsona** [comment]
FWIW, in this context 1.5.5 and 1.5.3 look like versions of AsciidoctorJ to me. That said, I can't see any connection between AsciidoctorJ and the original failure.
