### ISSUE TITLE
Add support for documenting JSON payloads containing arrays

### ISSUE THREAD

**Issue by udaraau** [spring-projects/spring-restdocs#60]
I'm trying to extract response fields (table) for a relatively complex JSON structure which contains array of objects. It is possible to add top level paths with <code>fieldWithPath</code> method, but  is there a  way to add a array of objects and their paths to the response fields in a way similar to following?

Sample JSON
```json
{
        "id": 67,
        "name": "2015-01-20",
        "assets": [
          {
            "id":356,
            "name": "sample"
          }
        ]
}
```
Response structure

|  Path 	|  Type   	| Description  	|
|---	|---	|---	|
|   id	|   Number	|   Unique,system generated ID	|
|   name	|  String 	|   Unique name	|
|   asset[].id| Number   	|   System generated ID for asset	|
|   asset[].name	|   String	|   Asset name	|

**Comment by wilkinsona** [comment]
The implementation only supports (nested) maps at the moment
