### ISSUE TITLE
Provide support for using existing JavaDoc descriptions on typesafe @RequestBody classes

### ISSUE THREAD

**Issue by sqlboy** [spring-projects/spring-restdocs#600]
Maybe this is already a feature?

If I have a controller method like:

`fun create(@RequestBody body: FooSpec) : Any`

Then it seems like to generate REST docs we have to hand copy every property description to the unittest?  Is there a way to get this automatically?

**Comment by wilkinsona** [comment]
Using javadoc is, deliberately, out of the scope of REST Docs. However, the [Auto REST Docs](https://github.com/ScaCap/spring-auto-restdocs) makes this possible.

**Comment by heyarny** [comment]
https://github.com/ScaCap/spring-auto-restdocs is end of life.

I think it should be still part of REST docs to improve documentation based on best practices.
I'm also looking for this feature and seriously thinking to switch to springdocs instead, as this is all supported there to reduce redundancies and work more efficient.

**Comment by wilkinsona** [comment]
Javadoc continues to be out of scope for Spring REST Docs. One of the benefits of the Spring ecosystem is its breadth and the amount of choice that it offers you. If Springdocs, or another alternative, is a better fit for your needs and preferences then making that switch may well be the right thing to do.

**Comment by heyarny** [comment]
Very opinionated reason to close this issue. Thanks anyway.
