### ISSUE TITLE
What is the best way to handle spring mvctests limitation in error scenarios?

### ISSUE THREAD

**Issue by lzhoucs** [spring-projects/spring-restdocs#603]
4 years has passed since https://github.com/spring-projects/spring-restdocs/issues/23, I'd like to check if there's already a good known workaround to handle the error scenarios in spring mvc tests with restdocs, e.g: some way to force a `responseFields(fieldDesc)` without getting the following error
```
org.springframework.restdocs.snippet.SnippetException: Cannot document response fields as the response body is empty
```
even if the response is empty due to the mvc tests' limitation?

I am aware of https://github.com/spring-projects/spring-boot/issues/7321#issuecomment-261498726, I wonder if this is still a good way to go?

**Comment by wilkinsona** [comment]
Yes, that's the recommended approach. REST Docs can't document something that isn't there so if you want to document the body of an error response, you'll need a test that produces such a response.
