### ISSUE TITLE
Assertion of the `Location` header

### ISSUE THREAD

**Issue by mayboroda** [spring-projects/spring-restdocs#61]
This is more a question rather than an issue. So, the problem is during assertion of the `Location` header. Here is a test

```java
@Test
	public void locationHeader() throws Exception {
		MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
				.apply(new RestDocumentationConfigurer().withScheme("http").withHost("api.server.com"))
				.alwaysDo(document("{method-name}-{step}")).build();
                // Here is how I do generate a location to assert against
		String location = linkTo(methodOn(TestController.class).bar()).toUri().toString();
		mockMvc.perform(get("/create").accept(MediaType.APPLICATION_JSON)).andExpect(
				header().string("Location", equalTo(location)));
	}
```

The controller on the other hand is:

```java
	@RestController
	static class TestController {

		@RequestMapping(value = "/create", produces = MediaType.APPLICATION_JSON_VALUE)
		public ResponseEntity<Map<String, String>> bar() {
			Map<String, String> response = new HashMap<String, String>();
			response.put("a", "alpha");
			return ResponseEntity.created(linkTo(methodOn(TestController.class).bar()).toUri()).body(response);
		}
	}
```

And actually the result of the test:
```
Response header Location
Expected: "http://localhost/create"
     but: was "http://api.server.com:8080/create"
java.lang.AssertionError: Response header Location
Expected: "http://localhost/create"
     but: was "http://api.server.com:8080/create"
```
Can someone explain me how I can generate a header correctly?

**Comment by wilkinsona** [comment]
The link building methods in Spring HATEOAS rely on Spring Framework's `RequestContextHolder` to access the current request. The current request is used to determine the scheme, host, and port in the link. Given that you're trying to build a link in a test when there should be no current request, I'm surprised that it works at all.

The above doesn't really matter as t don't think you should be using a link builder in your test. By reusing the exact same logic in your test that you're using in your controller, you're not really testing that the controller is doing the right thing – if there's a bug in the controller then there's a high chance that you test will contain the same bug. I'd update your test to hardcode the expected URI for the Location header.

**Comment by mayboroda** [comment]
cool, that's what I wanted to hear :)
