### ISSUE TITLE
Expand test coverage for AsciidoctorJ 2.x

### ISSUE THREAD

**Issue by ahus1** [spring-projects/spring-restdocs#630]
When experimenting with Spring REST docs and Asciidoctor, I found that the dependency asciidoctorj20Version in gradle.properties points to 2.0.0-RC.3. The current version of [AsciidoctorJ is is 2.1.0 that includes Asciidoctor 2.0.10](https://github.com/asciidoctor/asciidoctorj/releases/tag/v2.1.0).

I'd suggest upgrading to 2.1.0. I've run all tests locally and they complete without error. 

Maybe the variable should be renamed as well (and I am not sure about the library version upgrade policy here), so I didn't create a PR. 

Please advise, and I'll create a pull request.

**Comment by wilkinsona** [comment]
The use of `asciidoctorj20Version` was introduced as part of testing compatibility with AsciidoctorJ 2.0. It should be updated to 2.0.0.

Compatibility with 2.1 is probably also worth testing. If there are any breaking changes from 2.0, then a new `spring-restdocs-asciidoctor-2.1` module would be needed. If there are no breaking changes then it may be appropriate to rename `spring-restdocs-asciidoctor-2.1` to `spring-restdocs-asciidoctor-2.x`. The module's not exposed to users (it's merged into `spring-restdocs-asciidoctor` so the name can be changed with worrying about breaking backwards compatibility.
