### ISSUE TITLE
Add configuration for IntelliJ to allow full preview while editing 

### ISSUE THREAD

**Issue by ahus1** [spring-projects/spring-restdocs#631]
A user of the AsciiDoc plugin for IntelliJ asked how to achieve full preview while editing documentation files.
See asciidoctor/asciidoctor-intellij-plugin/issues/310 for the question and my answer. 
I've prepared a branch here: https://github.com/ahus1/spring-restdocs/tree/poc_extension_intellij

Would you be willing to a accept a pull request for the example projects to include this in master?

**Comment by wilkinsona** [comment]
Thanks for helping out a REST Docs user. Unfortunately, I don't think I'd merge the example is currently written as I don't want users to have to know about the macro's source code or how it's registered. That should be an implementation detail for them with adding a dependency on `spring-restdocs-asciidoctor` being all that's necessary to use it.

I see you have opened https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/312 to improve this situation. If/when that is implemented I'd be happy to reopen and revisit this issue.

**Comment by ahus1** [comment]
@wilkinsona - the next version of the plugin will support spring-rest-docs out of the box. I agree the configuration in the branch is too complicate. 

The upcoming version will detect a generated-snippets folder next to a build.gradle or pom.xml, and activate the spring-rest-docs extension as necessary. For now it will use a version of the plugin bundled in the IDE.

Your thoughts on this are welcome. 

Anyone interested in this feature should follow https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/312 to get a notification once a preview version is available.
