### ISSUE TITLE
Support REST Assured 4

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#635]

**Comment by bric3** [comment]
For reference, while we are probably not using all REST-Assured features or APIs, we are already using REST Assured 4.0.0 and Spring Restdocs 2.0.3.RELEASE together without any visible issues.

**Comment by wilkinsona** [comment]
Thank you, @bric3. That's useful info. This may turn into a just adding some compatibility testing. It may also make sense to do some repackaging as the current REST Assured support is in a `restassured3` package.

**Comment by bric3** [comment]
Ah yes I forgot to say that indeed we are using the API that lives under `restassured3`.

**Comment by wilkinsona** [comment]
I've added some compatibility testing against both 4.0.0 and 4.1.1 (#640). I'll keep this issue open to deal with the `restassured3` package. At the moment, I'm undecided between a couple of options:

- deprecate the `restassured3` package and provide the functionality in a `restassured` package
- provide a `restassured4` package with the same functionality

The first option is cleaner, but backs us into a corner if there's a REST Assured 5 with breaking changes in the future. The second avoids that problem but at the cost of some duplication. I think I'm leaning towards the first option and the moment.

**Comment by bric3** [comment]
Isn't there already a `restassured` package that target RestAssured 2 ?
Also thinking further ahead, if it's not restassured 5 it might be restassured 6 that break compatibility.

**Comment by wilkinsona** [comment]
> Isn't there already a restassured package that target RestAssured 2 ?

There is in 1.2 where it's deprecated. It was removed in 2.0.

**Comment by asaikali** [comment]
On SpringBoot 2.3.1 I updated rest assured to 4.3.1 and groovy to 3.0.4 and things seem to be working just fine. I don't have a lot of tests yet that are using RestDocs just a few as I have just started using RestDocs on this project.

**Comment by wilkinsona** [comment]
Thanks, @asaikali. https://github.com/spring-projects/spring-restdocs/issues/688 has expanded the REST Assured compatibility testing to cover 4.2 and 4.3 and didn't reveal any problems.

**Comment by wilkinsona** [comment]
This has been superseded by #752 where the package has been renamed from `restassured3` to `restassured`.
