### ISSUE TITLE
Optional and Constraints column not populated in my request-fields.adoc file

### ISSUE THREAD

**Issue by elvisols** [spring-projects/spring-restdocs#644]
Hi,
Please help, I'm new to restdocs. I have the following code to generate the 'Optional' and 'Constrain' column in my .adoc file but I can't seem to see any of them except for the defaults |Path|Type|Description
`requestParameters(
                            parameterWithName("size").description("Limit the number of accounts obtained to this number.").attributes(key("custom").value("true"))
                        )...
requestFields(
 
                            fieldWithPath("account_no").description("System account number")                     .optional().attributes(key("typo").value("now2"),key("constraints").value("not less than 3xters"))
                        )
`

**Comment by wilkinsona** [comment]
Have you provided a custom template for the snippet that uses the extra attributes as [described in the documentation](https://docs.spring.io/spring-restdocs/docs/2.0.x/reference/html5/#documenting-your-api-customizing-including-extra-information)?

> The second step is to provide a custom template named request-fields.snippet that includes the information about the fields' constraints in the generated snippet’s table and adds a title:
>
```
.{{title}} 
|===
|Path|Type|Description|Constraints 

{{#fields}}
|{{path}}
|{{type}}
|{{description}}
|{{constraints}} 

{{/fields}}
|===
```

If you'd done that then it's not clear from your description of the problem what may be going wrong. If you would like me to spend some more time investigating, can you please spend some time providing a complete and minimal sample that reproduces the problem? A zipped project attached to this issue would be ideal.

**Comment by elvisols** [comment]
Thanks @wilkinsona I didn't add my snippet earlier. Problem resolved.
