### ISSUE TITLE
Section title out of sequence with operation macro when using leveloffset

### ISSUE THREAD

**Issue by mle-enso** [spring-projects/spring-restdocs#649]
We still experience the same issue that was also referenced in https://github.com/spring-projects/spring-restdocs/pull/638 and thought this should be fine with the 2.0.4 release.

We use the Spring Boot release 2.1.9 and with that Spring RESTDocs 2.0.4 with the following (shrinked to the necessary) index.adoc:

```
= The title
additional info;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:leveloffset: 1
:sectlinks:
:sectnums:
:linkattrs:
:last-update-label!:

Sample explanation

operation::regenerateAllItems[snippets='path-parameters']
```

After building there is still this error which does not show up with Spring RESTDocs 2.0.3:

```
[INFO] asciidoctor: WARN: index.adoc: line 2: section title out of sequence: expected levels 0 or 1, got level 2
```

**Comment by wilkinsona** [comment]
Thanks for the report. It's `:leveloffset: 1` that is causing the problem. We'll need to see if it can be taken into account when create the section(s) for the operation's snippet(s).
