### ISSUE TITLE
{method-name} with uppercase word generates dashes

### ISSUE THREAD

**Issue by chadmalla-ff** [spring-projects/spring-restdocs#658]
Opening a separate issue like told in [#657 ](https://github.com/spring-projects/spring-restdocs/issues/657)

I have in my configuration `alwaysDo(document("{class-name}/{method-name}")` but the method names include a `-` when the method name has a word with all caps.

Example: 
 `GIVEN` becomes `g-i-v-e-n`. I would like it to be `given`.

**Comment by wilkinsona** [comment]
Was there any particular reason for closing this, @chadmalla-ff? A change here seems reasonable to me, but it remains to be decided if it should be handled as a bug or as an enhancement to make things more configurable.

**Comment by chadmalla-ff** [comment]
No particular reason, I just don't require it for my needs at the moment. Although, I can keep it open for the future.
