### ISSUE TITLE
Approach for Microservices?

### ISSUE THREAD

**Issue by ccit-spence** [spring-projects/spring-restdocs#66]
Very interested in implementing Restdocs for documenting our APIs.  Maybe this is already possible, how do you handle documentation when each service is a Microservice?  

The only way I can think of off the top of my head would require a parent pom and then each Microservice ends up being a Module.  This doesn't feel like a right approach for Microservices.  Another option would be git submodules "possibly".  

Has there been any work on this approach?

**Comment by wilkinsona** [comment]
Sorry, I'm struggling to see the connection between microservices and the use of a parent pom or a Git submodule. Can you explain in a bit more detail please?

One area where I can see microservices complicating things is in discovering and accessing the documentation. The best approach that I've heard so far is for each microservice to serve its own documentation from the same URI (`/docs`, for example). You can then piggyback on service discovery to also discover the documentation. Using hypermedia and linking to the service's documentation from its main entry point is another approach.

**Comment by ccit-spence** [comment]
Your right, that was my confusion.  The maven idea was somehow thinking that might be a way to create a docs site.  Not that it was a good idea.

I could see using Zuul to route to the docs and maybe setting up a central docs UI with links to each services set of docs.  

The main thing is I am finding centralized documentation to be a bit of a challenge with Microservices.  I like the idea of keeping docs with each service; then providing a central UI to access them.  

In the example you listed.  I assume you have a route in the gateway that would like like this `/api/service/**` then within the api you have a static directory/resource `/api/service/docs` which would be the docs for each service.  

For the centralized doc serice have it utilize service discovry for listing docs for each service.  This could then span to other none REST services if the same structure is implemented.

This sound close to the right track?

**Comment by wilkinsona** [comment]
Yes, that's the kind of approach I had in mind

**Comment by ccit-spence** [comment]
We will start working on this this week and see how it turns out.  Sounds like it should actually be fairly simple.  Seems as though the key is Discovery to include services within the main docs.  Otherwise a point of contention will be hard coding everything.

I have not tried anything with Restdocs yet, does it support things like Feign and RestTemplate?  My assumption is that each `rel` can be defined in the Mock setup.

**Comment by wilkinsona** [comment]
>  does it support things like Feign and RestTemplate?

No. You use Spring Test's MockMvc API to drive the tests and generation of the documentation.
