### ISSUE TITLE
How to document calls that need JWT token?

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-restdocs#660]
I want to document my API that uses JWT tokens. I am using MockMvc with Restdocs 2.0.4 with Junit 5. I have this setup to get started:

```
@WebMvcTest(UserController.class)
@ExtendWith(RestDocumentationExtension.class)
class UserControllerDocumentation {

    private MockMvc mockMvc;

    @BeforeEach
    void setUp(WebApplicationContext webApplicationContext,
               RestDocumentationContextProvider restDocumentation) {
        this.mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
                                      .apply(springSecurity())
                                      .apply(documentationConfiguration(restDocumentation)
                                                     .operationPreprocessors()
                                                     .withRequestDefaults(removeMatchingHeaders("X.*",
                                                                                                "Pragma",
                                                                                                "Expires"))
                                                     .withResponseDefaults(prettyPrint()))
                                      .build();
    }

    @Test
    void userDetailsExample() throws Exception {
        mockMvc.perform(get("/api/users/me")
                                .with(jwt(createJwtToken())))
               .andExpect(status().isOk())
               .andDo(document("user-details-example", responseFields(
                       fieldWithPath("userId").description("The Azure AD B2C id of the user"),
                       fieldWithPath("name").description("The display name of the user"))));
    }
}
```

With `createJwtToken` being a private method that creates a `org.springframework.security.oauth2.jwt.Jwt` instance.

I would like to see in the request snippet: `Authorization: Bearer JWT_TOKEN_HERE` as the user of the API will need to do that. How could I do that?

I have tried:

1) Writing a [custom preprocessor](https://docs.spring.io/spring-restdocs/docs/2.0.4.RELEASE/reference/html5/#customizing-requests-and-responses-preprocessors-writing-your-own) to add a header. This failed because the preprocessor receives `ReadOnlyHttpHeaders` so I can't add a header.

2) Add a dummy header and replace the header name using the `replacePattern` preprocessor:
```
        mockMvc.perform(get("/api/users/me")
                                .header("DOC-Authorization", "Bearer JWT_TOKEN_HERE")
                                .with(jwt(createJwtToken())))
```
with:
```
  .withRequestDefaults(removeMatchingHeaders("X.*",
                                                             "Pragma",
                                                             "Expires"),
              replacePattern(
                    Pattern.compile("^.*Authorization"),
                    "Authorization"))
```

This also does not work as `DOC-Authorization` is printed.

Are there other options?

**Comment by wilkinsona** [comment]
The pre-processor sounds like the way to go. You can use `org.springframework.http.HttpHeaders.writableHttpHeaders(HttpHeaders)` to create a writeable instance from the read-only headers, add the header, and then use `org.springframework.restdocs.operation.OperationRequestFactory.createFrom(OperationRequest, HttpHeaders)` to create a new request using the updated headers.
