### ISSUE TITLE
spring boot packaging documentation seems wrong

### ISSUE THREAD

**Issue by rburgst** [spring-projects/spring-restdocs#664]
in #521 only the task name was changed. However, in order for the files to end up in the correct place they need to be placed in `BOOT-INF/classes`

```
bootJar {
    dependsOn asciidoctor
    from ("${asciidoctor.outputDir}/html5") {
        into 'BOOT-INF/classes/static/docs'
    }
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but it isn't necessary to package the documentation in `BOOT-INF/classes`. In the root of the jar it will be available to the app class loader and can be found and served by Spring MVC's static resource handling. You can see this in action by building and running one of the samples.

**Comment by rburgst** [comment]
FYI, in my example I had it package to a different location and there it needed to be in BOOT-INF/classes

i.e.  I had the following config

```
public class WebConfig implements WebMvcConfigurer
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        if (!registry.hasMappingForPattern("/external/v1/docs/**")) {
            registry.addResourceHandler("/external/v1/docs/**").addResourceLocations("classpath:/rest/docs/external/v1/");
        }
    }
```

and the following in my `build.gradle`
```
bootJar {
    dependsOn asciidoctor

    from("${asciidoctor.outputDir}/html5/external.html") {
        into "/rest/docs/external/v1"
    }
```
and the resource was only available if packaged into `BOOT-INF` , so the above example did not work.

**Comment by rburgst** [comment]
maybe note that I am on spring boot 2.2.2

**Comment by rburgst** [comment]
I double checked with the `testng` example and there it works. I am unsure why it doesnt with my onfiguration
