### ISSUE TITLE
Default snippet encoding to UTF-8 and allow it to be configured

### ISSUE THREAD

**Issue by fabriciocolombo** [spring-projects/spring-restdocs#67]
How do i configure the generated snippets encoding to UTF-8?

**Comment by wilkinsona** [comment]
The snippets are currently written using the JVM's default encoding. Do you have a need to write the snippets in an encoding other than the default for your environment?

**Comment by wilkinsona** [comment]
Nevermind, thinking about it some more, ensuring that builds are repeatable is reason enough to use a specific encoding. It should probably be configurable with a sensible default (UTF-8, I think).

**Comment by fabriciocolombo** [comment]
I running on Windows 7 x64, and default Charset is windows-1252, but source code is UTF-8. I currently work around setting the file.encoding to UTF-8 in my GRADLE_OPTS.
It would be nice to have a setting for this.

**Comment by fabriciocolombo** [comment]
Thank you
