### ISSUE TITLE
List of required fields for objects in array

### ISSUE THREAD

**Issue by oharkusha** [spring-projects/spring-restdocs#672]
Due to swagger documentation, I expect to generate a document like that:
```
type: array,
  items: {
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      name:
        type: string
    required:
      - id
      - username
```
The field descriptor has an **optional** property.
`val fieldDescriptor = PayloadDocumentation.fieldWithPath(path).description(description).let { if (optional) it.optional() else it }`

Then I use ResourceDocumentation.resource(ResourceSnippetParameters(..., ..., fieldDescriptorLists).

I expect to have all **optional == false** fields as **required** accordingly to swagger documentation.

Do I make it in the wrong way?  Or the library doesn't support this? Any workaround?

Thank you in advance!

**Comment by wilkinsona** [comment]
`ResourceDocumentation` is provided by the third-party extension, https://github.com/ePages-de/restdocs-api-spec.
