### ISSUE TITLE
Artifactory does not return latest version

### ISSUE THREAD

**Issue by gkaran** [spring-projects/spring-restdocs#68]
I' m trying to fetch the latest version from the artifactory to fix the setup of my project (since some things have changed) but I do not get the latest one.

The version I'm getting is "0.1.0.BUILD-20150325.144113-28" while the latest is "0.1.0.BUILD-20150513.102043-51".

Just letting you know so that you can fix this or advice in case I'm doing something wrong.

**Comment by wilkinsona** [comment]
What coordinates are you using? The artifact id changed from `spring-restdocs-core` to `spring-restdocs` a while ago. All the old `spring-restdocs-core` snapshots have been remove from the repo so I would guess you're seeing a locally cached version of one of the old artifacts.

**Comment by gkaran** [comment]
I'm using "org.springframework.restdocs:spring-restdocs:0.1.0.BUILD-SNAPSHOT".

I tried removing the library and adding it back, but again I get the old version.

**Comment by wilkinsona** [comment]
Strange. The earliest snapshot version [in the repository](http://repo.spring.io/libs-snapshot/org/springframework/restdocs/spring-restdocs/0.1.0.BUILD-SNAPSHOT/) is `0.1.0.BUILD-20150429.090949-42` so, wherever the old version is coming from, I don't think it's repo.spring.io. Are you behind a proxy? Perhaps it's cached a stale version? Running Maven or Gradle with debug output enabled should show where it download's coming from.

**Comment by gkaran** [comment]
It seems that IntelliJ IDEA was keeping a cached version somewhere. Removing this worked like a charm. Sorry for this.
