### ISSUE TITLE
Pathparameter documentation does not add the optional field

### ISSUE THREAD

**Issue by MrMedTech** [spring-projects/spring-restdocs#692]
Hi,
I have a problem with documenting my path parameters.
` pathParameters(parameterWithName("id").description("Id of the product").optional())`

I've read the [docs ](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-path-parameters)about this topic and I expected that if I add the optional parameter, the resulting standard snippet will include it and represent it in the table.
Instead I get a table only consisting of the name and the description.
Is that the expected behaviour? 
I tried to add a custom snippet to override the default but my table body then was always empty.

**Comment by wilkinsona** [comment]
> I've read the docs about this topic and I expected that if I add the optional parameter, the resulting standard snippet will include it and represent it in the table.

Whether or not a path parameter is optional affects whether or not the test will fail of the parameter isn't present. The information isn't included in the generated table by default.

If you want to include it in the table, you were on the right path by trying to use a [a custom template](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-customizing-snippets) to do so. A template that adds a column for optional would look like this:

```
|===
|Parameter|Description|Optional

{{#parameters}}
|{{name}}
|{{description}}
|{{optional}}

{{/parameters}}
|===
```
