### ISSUE TITLE
Artifacts suddenly not available

### ISSUE THREAD

**Issue by gkaran** [spring-projects/spring-restdocs#697]
It seems that we are unable to get artifacts from either the snapshots or the releases artifactory for spring-restdocs because the `maven-metadata.xml` and `spring-restdocs-*.pom` files are missing.

We came across this issue today. Seems something is off with the artifactories.

**Comment by wilkinsona** [comment]
Everything looks OK to me. For example, [here's 2.0.5.RELEASE in the release repository](https://repo.spring.io/libs-release-local/org/springframework/restdocs/spring-restdocs-core/2.0.5.RELEASE/):

```
../
spring-restdocs-core-2.0.5.RELEASE-javadoc.jar   16-Sep-2020 15:29  457.33 KB
spring-restdocs-core-2.0.5.RELEASE-sources.jar   16-Sep-2020 15:29  195.11 KB
spring-restdocs-core-2.0.5.RELEASE.jar           16-Sep-2020 15:29  278.89 KB
spring-restdocs-core-2.0.5.RELEASE.pom           16-Sep-2020 15:29  6.21 KB
```

[2.0.6 snapshots](https://repo.spring.io/libs-snapshot-local/org/springframework/restdocs/spring-restdocs-mockmvc/2.0.6.BUILD-SNAPSHOT/) look fine too:

```
../
maven-metadata.xml                                                  16-Sep-2020 17:30  1.23 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.141445-2-javadoc.jar   16-Sep-2020 14:24  45.37 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.141445-2-sources.jar   16-Sep-2020 14:24  15.10 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.141445-2.jar           16-Sep-2020 14:24  19.83 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.141445-2.pom           16-Sep-2020 14:24  5.85 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.152946-3-javadoc.jar   16-Sep-2020 15:39  45.37 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.152946-3-sources.jar   16-Sep-2020 15:39  15.10 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.152946-3.jar           16-Sep-2020 15:39  19.83 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.152946-3.pom           16-Sep-2020 15:39  5.85 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.171946-4-javadoc.jar   16-Sep-2020 17:30  45.38 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.171946-4-sources.jar   16-Sep-2020 17:30  15.10 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.171946-4.jar           16-Sep-2020 17:30  19.83 KB
spring-restdocs-mockmvc-2.0.6.BUILD-20200916.171946-4.pom           16-Sep-2020 17:30  5.85 KB
```

Can you provide some links to locations where the pom files are missing?

**Comment by gkaran** [comment]
We were actually using the "spring-restdocs" artifacts and not "spring-restdocs-core". So far we were using the snapshot channel from [here](https://repo.spring.io/snapshot/org/springframework/restdocs/spring-restdocs/) but since we starting having issues we tried switching to the release [here](https://repo.spring.io/release/org/springframework/restdocs/spring-restdocs/).

Our artifact was:
```
group: 'org.springframework.restdocs', name: 'spring-restdocs', version: '1.0.0.RELEASE'
```

Is this artifact no longer maintained and we need to switch to `spring-restdocs-core` ?

**Comment by wilkinsona** [comment]
> We were actually using the "spring-restdocs" artifacts and not "spring-restdocs-core".

`spring-restdocs` only provides the documentation zip. Unless I am forgetting something from the early days of REST Docs, that's always been the case. It's never been intended to be used as a dependency. It's published to Artifactory purely because that's a step in our documentation publication pipeline. 

> we need to switch to spring-restdocs-core ?

Typically, you'd use `spring-restdocs-mockmvc`, `spring-restdocs-restassured`, or `spring-restdocs-webtestclient` depending on which testing framework you're using. This is [described in the reference documentation](https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/#getting-started-build-configuration). Each of those thee modules depends on `spring-restdocs-core`.

**Comment by gkaran** [comment]
Thank you. So far this was working for us - I don't know what changed to be honest. We will proceed with the dependency switch.
