### ISSUE TITLE
Customization of Request and Response columns

### ISSUE THREAD

**Issue by mayboroda** [spring-projects/spring-restdocs#70]
Right now we can have only three columned table for request and response fields, but what if we need to add an additional column for some requests or responses or rename an existing columns?

***Suggestion 1***
To add a factory for column fields like so

```java
.andDo(document("assets/banks").response().withFields(
    fieldWithPath("id").description("UUID of the asset."),
    fieldWithPath("name").description("Name of the asset.")
)
```
And if we need to add ***size*** column to response table:
```java
.andDo(document("assets/banks").response(withColumn("size")).withFields(
    fieldWithPath("id").description("UUID of the asset.").column("size", "0..12"),
    fieldWithPath("name").description("Name of the asset.").column("size", "15..20")
)
```

Also if we need to rename default column ***description*** into ***info***:
```java
.andDo(document("assets/banks").response(
    withDescriptionAs("info"),
    withColumn("size")
).withFields(
    fieldWithPath("id").description("UUID of the asset.").column("size", "0..12"),
    fieldWithPath("name").description("Name of the asset.").column("size", "15..20")
)
```
***Suggestion 2***
To create a ***ColumnDescriptor*** class so we can extend columns more flexible.

```java
.andDo(document("assets/banks").withResponseFields(
    fieldWithPath("id").with(description("UUID of the asset."), size(0, 23))
)
```
Then in case of renaming a default field you'll have to extend it and rename it.

P.S.
There is also an open question around the order of columns.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. If a change is made here, then it should be made in such a way as to make all of the generated tables configurable, not just those for request and response fields. Basically, anything that uses `TableWriter`. At the time of writing that's links, request and response fields, and query parameters.

**Comment by wilkinsona** [comment]
Custom snippets can now be used to relabel table columns and reorder the columns. Custom snippets coupled with custom attributes on the descriptors can now be used to add arbitrary columns. Please see the [updated reference documentation](http://docs.spring.io/spring-restdocs/docs/1.0.x-SNAPSHOT/reference/html5/#documenting-your-api-customizing) for further information.

**Comment by mayboroda** [comment]
Thanks, already got an email about your commits. Thank you very much for this improvement. I didn't have time to finish my version of this issue, but I've also created an BaseDescirptor :)
Now I can remove all the custom stuff I had and use this out of the box.
Thanks again.
