### ISSUE TITLE
can not make response body in http-response.adoc when using AsyncResult

### ISSUE THREAD

**Issue by digimon1740** [spring-projects/spring-restdocs#701]
Using Spring REST docs with MockMvc and Kotlin in our project 
However, some api does not make response in http-response.adoc. I guess because that apis return asyncResult by CompletableFuture instead of response.contentAsString of MvcResult.

in fact, there is correct response in the api controller and passed test cases successfully. 
is there another way to make response in http-response.adoc? 

## sample code
```
 @Test
    fun shouldReturnContent() {
        val result = mockMvc.perform(
            get("/contents/{id}", "test")
            .andDo(print())
            .andDo(document(
                "content",
                preprocessResponse(prettyPrint())
            ))
            .andExpect(status().isOk)
            .andReturn()

        val response = result.asyncResult // this is asyncResult by CompletableFuture
        logger.info("response : {}", response)
        assertThat(response).isNotNull

        val actual = response.data
        assertThat(actual).isNotNull
```

### generated-snippets/contents/http-response.adoc
```
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers

----
```

**Comment by wilkinsona** [comment]
You're trying to document the request and response before the async processing has completed. Instead, you should be using `perform(asyncDispatch(mvcResult))` and calling REST Docs at that point. There's a [general example of using `asyncDispatch`](https://docs.spring.io/spring-framework/docs/5.2.8.RELEASE/spring-framework-reference/testing.html#spring-mvc-test-async-requests) in the Spring Framework reference documentation.

If the above doesn't help, please provide a complete and minimal sample and we can re-open the issue and take another look.

**Comment by digimon1740** [comment]
@wilkinsona thanks for your guide it works perfectly 💯
