### ISSUE TITLE
Support request and response headers documentation

### ISSUE THREAD

**Issue by andreasevers** [spring-projects/spring-restdocs#71]
Similar as documenting fields on top of links, headers are also useful to document.

Especially for versioning through content negotiation and JWT tokens it's important to be have documentation of required headers.

I could create a PR if this is a feature that fits into spring restdocs.

**Comment by wilkinsona** [comment]
Sorry for the slightly delayed response; I've just got back from paternity leave.

My assumption thus far has been that headers are something that should be used consistently across an entire API and, therefore, should only be documented once. For example, this is the approach that GitHub have taken, with various HTTP headers being documented in the [overview section of their documentation](https://developer.github.com/v3/#overview).

That said, even if it'll only be used once in the documentation, having support for producing a table of headers where you can be sure that the header names match those consumed and produced by the service is probably still of value.

If you'd like to create a PR I'd be more than happy to accept the contribution.

**Comment by andreasevers** [comment]
Thank you for considering this enhancement. I will soon create a PR in a similar way the support for request and response fields were designed.

**Comment by andreasevers** [comment]
During implementation, the following question comes up:
Can we apply the same assertions on headers as fields and links? Does it make sense to fail the build if a request or response header hasn't been documented?

Among others, the response header "Content-Length" doesn't seem worthy of being documented.

Perhaps a less strict validation should be applied for headers. How about asserting that the ones that are documented should be present in the operation, but those which are extra in the operation should be ignored for the assertion?

**Comment by andreasevers** [comment]
Giving it some more thought, wouldn't it be best to validate only custom headers (which are not present in HttpHeaders class)?

This would mean the following assertions:

Headers present in the documentation have to be present in the operation.
Headers present in the operation fall in two categories:
- Headers present in the operation and present in the HttpHeaders class don't have to be present in the documentation (but can be present).
- Headers present in the operation but not present in the HttpHeaders have to be present in the documentation.

Does this sound reasonable or too custom?

**Comment by wilkinsona** [comment]
You make a good point about `Content-Length`, particularly in a response.

I don't think using `HttpHeaders` to decide what should and should not be documented is the right answer. For example, you might want to document the `Content-Type` header to describe the supported request formats.

I think some more thought's required on this one. If Spring REST Docs isn't going to do any validation of the headers that have been documented, then there's no point in it having specific support for documenting them. For this feature to make sense, I think we need to find some sensible and easy to describe rules for the validation. As you suggested, limiting that validation to only checking that a documented header is present could well be the right answer.
