### ISSUE TITLE
empty "message" in error responses after upgrading to spring-boot 2.3.0+

### ISSUE THREAD

**Issue by pszemus** [spring-projects/spring-restdocs#710]
Hello
After upgrading to spring-boot 2.3.0+ default error endpoint (`/error`) response returns an empty `message` field.

E.g: in your sample `rest-notes-spring-hateoas` application: https://github.com/spring-projects/spring-restdocs/blob/v2.0.5.RELEASE/samples/rest-notes-spring-hateoas/src/test/java/com/example/notes/ApiDocumentation.java#L118 this message is not returned after upgrading to spring-boot 2.3.0:

[output of `.andDo(print())`]
```
    MockHttpServletRequest:
          HTTP Method = GET
          Request URI = /error
           Parameters = {}
              Headers = []
                 Body = <no character encoding set>
        Session Attrs = {}

    Handler:
                 Type = org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController
               Method = org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#error(HttpServletRequest)

    Async:
        Async started = false
         Async result = null

    Resolved Exception:
                 Type = null

    ModelAndView:
            View name = null
                 View = null
                Model = null

    FlashMap:
           Attributes = null

    MockHttpServletResponse:
               Status = 400
        Error message = null
              Headers = [Content-Type:"application/json"]
         Content type = application/json
                 Body = {"timestamp":"2021-01-27T10:53:40.222+00:00","status":400,"error":"Bad Request","message":"","path":"/notes"}
        Forwarded URL = null
       Redirected URL = null
              Cookies = []
```

and the documented `build\generated-snippets\error-example\http-response.adoc` becomes:
```
[source,http,options="nowrap"]
----
HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 135

{
  "timestamp" : "2021-01-27T10:46:33.000+00:00",
  "status" : 400,
  "error" : "Bad Request",
  "message" : "",
  "path" : "/notes"
}
----
```

I think it's because of disabling of the error message on default error page introduced in spring-boot 2.3.0: https://github.com/spring-projects/spring-boot/issues/20505

I've tested the latest 2.2 branch (2.2.13.RELEASE) 👍 , 2.3.0.RELEASE 👎  and latest (2.4.2) 👎

**Comment by wilkinsona** [comment]
Your analysis is correct and is the standard behaviour with Spring Boot 2.3 and later. REST Docs' samples are using an older version of Boot so this is to be expected at the moment. I've opened https://github.com/spring-projects/spring-restdocs/issues/711 to update the samples to use Spring Boot 2.4. Adapting to the change in the error response will be taken care of as part of that.
