### ISSUE TITLE
FieldTypesDoNotMatchException when required field has a null value

### ISSUE THREAD

**Issue by Adam198590** [spring-projects/spring-restdocs#716]
I have such required fields in my POJO

```
...
    @NotNull
    private final ArtifactTypeRest type;
    @NotNull
    private final LocalDate releasedAt;
...
```

and documented them accordingly:

```
...
fieldWithPath("type").description("artifact type").type(JsonFieldType.STRING),
fieldWithPath("releasedAt").description("artifact release date").type(JsonFieldType.STRING),
...
```

when i provide `null` value for them then i have such exception:

> The documented type of the field 'type' is String but the actual type is Null

or

> The documented type of the field 'releasedAt' is String but the actual type is Null

there was a similar situation here:
https://github.com/spring-projects/spring-restdocs/issues/365

but for optional fields.

**Comment by wilkinsona** [comment]
This is working as designed. If the field's value can be `null` (or if it can be missing entirely) it should be marked as optional.
