### ISSUE TITLE
Drop support for Asciidoctor 1.x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#718]

**Comment by jnizet** [comment]
This would really be nice to have, because the gradle asciidoctor plugin that is suggested in the documentation is not compatible with gradle 7.

**Comment by wilkinsona** [comment]
I think we can separate the two. I see no reason why the documentation can't recommend the use of a more up-to-date version of the Asciidoctor Gradle Plugin even while Asciidoctor 1.x is still supported. I've opened https://github.com/spring-projects/spring-restdocs/issues/734.

**Comment by wilkinsona** [comment]
Superseded by #751.
