### ISSUE TITLE
Provide full example for the current version of Spring Boot

### ISSUE THREAD

**Issue by ccleve** [spring-projects/spring-restdocs#722]
As of today, the current version of Spring Boot is 2.4.5.  There are no sample applications that show how to make this project work with Junit 5 and the current testing style (@SpringBootTest, etc.).

There are Junit5 snippets in the documentation for this project, but they lack import statements and need some surgery to get them to work.

Just do a simple, working application that tests a Rest endpoint and generates API documentation.

**Comment by wilkinsona** [comment]
There's a [JUnit-5 based sample](https://github.com/spring-projects/spring-restdocs/tree/v2.0.5.RELEASE/samples/junit5) that's [linked from the reference documentation](https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/#getting-started-sample-applications). It uses `@SpringBootTest` and works as-is when upgraded to Spring Boot 2.4.5.

I've opened https://github.com/spring-projects/spring-restdocs/issues/723 to upgrade all of the Spring Boot-based samples to use 2.4.5, but I can't see a need for a new sample. Thanks anyway for the suggestion.
