### ISSUE TITLE
Unresolved directive in <stdin>

### ISSUE THREAD

**Issue by iggykarpov** [spring-projects/spring-restdocs#727]
I see this:
...
What You Need
Unresolved directive in <stdin> - include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

Unresolved directive in <stdin> - include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

Starting with Spring Initializr
...

here:
https://spring.io/guides/gs/testing-web/

Thanks

**Comment by wilkinsona** [comment]
@iggykarpov Thanks for letting us know but that's unrelated to Spring REST Docs. Can you please open an issue [here](https://github.com/spring-guides/gs-testing-web) instead?
