### ISSUE TITLE
  timeout on blocking read for 5000 MILLISECONDS 

### ISSUE THREAD

**Issue by wsc58888** [spring-projects/spring-restdocs#731]
@Before
	public void setUp() {

		final TcpClient theTcpClient = TcpClient.create()
				.option(ChannelOption.SO_TIMEOUT, 100000) 
				.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 100000) 
				.doOnConnected(theConnection -> {
					theConnection.addHandlerLast(new ReadTimeoutHandler(100000, TimeUnit.MILLISECONDS));// 客户端获取读到信息的时间
					theConnection.addHandlerLast(new WriteTimeoutHandler(100000, TimeUnit.MILLISECONDS));// 远程将信息写入客户端完成的时间
				});
		ClientHttpConnector httpConnector = new ReactorClientHttpConnector(HttpClient.from(theTcpClient));
		 
		this.webTestClient = WebTestClient.bindToServer(httpConnector)
				.filter(documentationConfiguration(restDocumentation)).baseUrl(webBaseUrl).build();
	}

也配置了.
@AutoConfigureWebTestClient(timeout = "100000")//10 seconds

**Comment by wilkinsona** [comment]
Thanks for the report, but REST Docs isn’t involved in making the request-response exchange that’s being documented. It looks like the endpoint that you are calling isn’t responding within 5000ms. That is out of REST Docs control.
