### ISSUE TITLE
Change the Documentation in setting up tests to use `WebClientTest` for Servlet based.

### ISSUE THREAD

**Issue by talentedasian** [spring-projects/spring-restdocs#735]
The documentation for setting up tests where you build and bind `WebClientTests` to application contexts does not specify whether to use `MockMvcWebTestClient` or `WebClientTest`. It should specify whether to use `(**MockMvcWebTestClient** and **WebClientTest**).bindToApplicationContext` for servlet based or projects that use webflux respectively. This cost me so much nuisance and time for a trivial mistake.

**Comment by wilkinsona** [comment]
Thanks for the report and sorry for confusion. Unfortunately, it's not clear to me from where the confusion arose. REST Docs does not yet officially support `MockMvcWebTestClient` (`https://github.com/spring-projects/spring-restdocs/issues/691` is tracking that work) and, as far as I can tell, the documentation consistently shows the use of `WebTestClient.bindToApplicationContext` for building the `WebTestClient`.

**Comment by talentedasian** [comment]
The documentation suggested to use WebTestClient but using it causes it to have a `noSuchBean` named **webHandler**. I don't know if this is what happens with non-servlets but this only happens I think with servlet based projects. Using the ` MockMvcWebTestClient` class solved my problem and binding it with a WebApplicationContext instead of just an ApplicationContext. 

In my opinion the documentation isn't really at fault and it was my ignorance about WebClient but adding clarifications on whether to use `MockMvcWebTestClient` or `WebTestClient` if MockMvcWeb... gets full support in the future would be a great help :)

**Comment by wilkinsona** [comment]
This'll be covered in the documentation updates that are made as part of #691.
