### ISSUE TITLE
operation:: doesn't work after upgrading to asciidoctor 3.3.2 version

### ISSUE THREAD

**Issue by AlexCzar** [spring-projects/spring-restdocs#737]
build.gradle.kts:
```kotlin
plugins {
	id("org.asciidoctor.base") version "3.3.2"
	id("org.asciidoctor.jvm.convert") version "3.3.2"
}
val snippetsDir by extra { file("build/generated-snippets") }
tasks {
	testI {
		outputs.dir(snippetsDir)
	}

	asciidoctor {
		sourceDir(file("$projectDir/src/docs"))
		setOutputDir(File(buildDir, "docs"))
		inputs.dir(snippetsDir)
		inputs.dir(file("src/docs"))
		attributes(mapOf("snippets" to snippetsDir))
		dependsOn(testI)
	}
}
```
source file
```asciidoc
=== Get client

operation::client-get-by-id[snippets='curl-request,http-request,http-response']
```
resulting HTML file has following intstead of results of `operation::*` expansion
```html
<h3 id="_get_client"><a class="link" href="#_get_client">Get client</a></h3>
<div class="paragraph">
<p>operation::client-get-by-id[snippets='curl-request,http-request,http-response']</p>
</div>
```
This worked before upgrading to latest asciidoctor plugin.
When the source adoc file is opened in IntelliJ with asciidoctor plugin installed, all the snippets show up in the preview pane.

NOTE: `testI` is just a test task for a custom source set.

**Comment by wilkinsona** [comment]
That sounds like a regression in the Asciidoctor Gradle Plugin to me. The operation macro's tested against numerous versions of AsciidoctorJ:

- `1.5.8.1`
- `1.6.2`
- `2.0.0`
- `2.1.0`
- `2.2.0`
- `2.3.0`
- `2.4.2`

I've just added `2.5.1` to that locally and it passes. Why do you believe that this is a REST Docs problem?

**Comment by AlexCzar** [comment]
isn't `operation:: ` a rest-docs concept? How do I check if there is a regression?

**Comment by wilkinsona** [comment]
I've just checked the `rest-notes-spring-hateoas` sample in this repository. It [uses 3.3.2 of the `org.asciidoctor.jvm.convert` plugin](https://github.com/spring-projects/spring-restdocs/blob/c6e7b567e34d316cbb2424d44d011e2de971201b/samples/rest-notes-spring-hateoas/build.gradle#L4) and the `operation` macro without any problems.

> isn't operation:: a rest-docs concept? How do I check if there is a regression?

Yes, but it's not responsible for the macro being called. That's done by Asciidoctor.

Looking at your example, I can't see any sign of the `spring-restdocs-asciidoctor` dependency. Have you set up that dependency and configured Asciidoctor to use it? You can see an example of that in the sample that I linked to above.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by AlexCzar** [comment]
Yes, I did have it (just omited the `dependecies` block for brevity), but previously there was a provided `asciidoctor` configuration and there was no need to add it to the task.
Now seeing the example in hateos, I've updated my build script to explicitly define the configuration and add it to the task.
It works now.
Thanks a ton for the support!

**Comment by wilkinsona** [comment]
Glad to hear you got it working. https://github.com/spring-projects/spring-restdocs/issues/680 is tracking some documentation updates to show how to configure the newer versions of the Asciidoctor Gradle Plugin.

**Comment by diabe30** [comment]
i have a similar issue, but it looks like the repo that has the build script can't be located.
