### ISSUE TITLE
Spring-restdocs-core 2.0.5.jar LinksSnippet: line 155 possible error

### ISSUE THREAD

**Issue by jordensy** [spring-projects/spring-restdocs#740]
Hi,

I am writing some POST REST test that uses HATEOAS to add links in the response. £Even though the response is showing the links, the content-type = application/hal+json and I see that during the debugging the liknks get extracted well, I still get an error that the links are not documented. While I expect them to be documented.

After further debugging I see in class LinksSinppet line 155 following statement:

if (!undocumentedRels.isEmpty() || !missingRels.isEmpty()) { 
      String message = "";
	if (!undocumentedRels.isEmpty()) {
		message += "Links with the following relations were not documented: " + undocumentedRels;
	}
....

Both my HashSets are empty so It will come in the logic saying that my links are undocumented. But they are documented in the test method!
if a Hashset that is called undocumentedRels is empty I would think that this means that they are documented.
so why is the negation in front of !undocumentedRels.isEmpty() required ?

Maybe I oversee things wrong but I think it is a mistake.

Either the name was miss schoosen  or the negation should be not there

**Comment by wilkinsona** [comment]
The if is checking that either undocumentedRels is not empty or missingRels is not empty. If you are entering the if-block, one or both must not be empty. That means that you either have not documented a link or you have documented a link that isn’t present in the response.

Let’s take a step back as we’ve jumped straight to discussing a possible cause without the problem being explained. Can you please provide a small example that reproduces the behaviour that you have described?

**Comment by jordensy** [comment]
Please close the issue. the problem is something else. Allthough the message is confusing. It keeps saying that this payload part is undocumenten. Even I did say that _links have to be ignored

"_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/profielen/1",
      "type" : "GET"
    },
    "profielen" : [ {
      "href" : "http://localhost:8080/api/profielen",
      "type" : "GET"
    }, {
      "href" : "http://localhost:8080/api/profielen/add",
      "type" : "POST"
    } ]
  }

for some reason the ignoreUndocumentedFields = false. even after doing this:
fieldWithPath("_links").description("HAL links").ignored()
So now it is complaining about the self and profielen subfields. but even adding them with ignored does not help. so not sure how to deal with this and also do not find a good example

**Comment by jordensy** [comment]
Solved:

I should use: subsectionWithPath("_links").description("HAL links")
instead of: fieldWithPath("_links").description("HAL links")

pfff: hard one (for me)

**Comment by wilkinsona** [comment]
I was just about to comment with that suggestion. That’s the right thing to do. It’s described [here](https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/#documenting-your-api-request-response-payloads-fields). Suggestions welcome if you think this could be made more clear.
