### ISSUE TITLE
Document how to use Spring REST Docs with the WebTestClient with Spring-Boot

### ISSUE THREAD

**Issue by brneto** [spring-projects/spring-restdocs#741]
Where in the documentation I could present a example of using it with WebTestClient + Spring-Boot.
e.g.
```java
@WebFluxTest
@AutoConfigureRestDocs
class ControllerTests {

    private WebTestClient webClient;

    @BeforeEach
    void setUp(
            @Autowired ApplicationContext context,
            @Autowired WebTestClientRestDocumentationConfigurer configurer) {

        webClient = WebTestClient
                .bindToApplicationContext(context)
                .configureClient()
                .filter(configurer)
                .entityExchangeResultConsumer(document("{class-name}/{method-name}"))
                .build();
    }
}
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. `@AutoConfigureRestDocs` is a Spring Boot feature and it’s already [covered in its reference documentation](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-rest-docs).

**Comment by brneto** [comment]
@wilkinsona But in this case there's misleading information between the Spring Boot and the Spring REST Docs documentation.

The [Spring REST Docs documentation](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documentating-your-api-parameterized-output-directories) states that we "cannot parameterise the output directory when using `WebTestClient`." That's where I'm making myself available to add my code example above.

**Comment by wilkinsona** [comment]
I'm with you now. Thanks for the clarification. That's already been taken care of in the latest snapshots. See https://github.com/spring-projects/spring-restdocs/issues/713 for details and https://docs.spring.io/spring-restdocs/docs/2.0.6.BUILD-SNAPSHOT/reference/#documentating-your-api-parameterized-output-directories for the updated docs.

**Comment by brneto** [comment]
@wilkinsona What do you think we also add a JUnit 5 example somewhere in this documentation?

**Comment by wilkinsona** [comment]
The documentation already has a [section on using JUnit 5](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-documentation-snippets-setup-junit-5).

**Comment by brneto** [comment]
Great! Thanks @wilkinsona !

Shouldn't we also comment somewhere that we could also obtain the `WebTestClientRestDocumentationConfigurer` bean from the context if the test class is using the `@AutoConfigureRestDocs` annotation?

Sorry keep bothering you! :|

**Comment by wilkinsona** [comment]
Generally speaking, there's no need to do so. The REST Docs auto-configuration in Spring Boot will apply the `WebTestClientRestDocumentationConfigurer` to the auto-configured `WebTestClient` automatically. As you're using `@AutoConfigureRestDocs`,  your example above should probably be changed to use a `WebTestClientBuilderCustomizer` to  add the `entityExchangeResultConsumer` to the client.

**Comment by brneto** [comment]
Would be possible share with me a link to any documentation explaining how I could change my example to use `WebTestClientBuilderCustomizer` instead, please?

**Comment by wilkinsona** [comment]
I don't think we have a specific example for this particular combination. `WebTestClientBuilderCustomizer` is [documented here](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#boot-features-testing-spring-boot-applications-customizing-web-test-client). You use one to apply your customizations which, in this case, is the addition of the entity exchange result consumer. That allows you to replace your `@BeforeEach` method and inject the `WebTestClient` instead. In combination, that leaves your test class looking something like this:

```java
@WebFluxTest
@AutoConfigureRestDocs
class ControllerTests {

	@Autowired
	private WebTestClient webTestClient;

	@TestConfiguration
	static class RestDocsParameterizedOutput {

		@Bean
		WebTestClientBuilderCustomizer restDocsParameterizedOutput() {
			return (builder) -> builder.entityExchangeResultConsumer(document("{class-name}/{method-name}"));
		}

	}

}
```

**Comment by wilkinsona** [comment]
We could add this to the Spring Boot docs, where there's [already an example showing the equivalent configuration with MockMvc](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-rest-docs-mock-mvc).

**Comment by brneto** [comment]
@wilkinsona That's a very good idea. It's could help others like me! And thank you so much for your example above! That's amazing!

If you want I can create a PR for your example above. Would you mind?

**Comment by wilkinsona** [comment]
I wouldn't mind at all. Thanks for the offer.

While the issue I just opened is targeted at 2.4.x, a PR based off main would still be useful. If you do that [this](https://github.com/spring-projects/spring-boot/blame/7f0c9fbbd7ac7114b9666ae97e9474b6567ef835/spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/testing.adoc#L754) is where the new documentation should be added. Alternatively, if you'd prefer to base your PR off the 2.4.x branch, the new documentation should go [here](https://github.com/spring-projects/spring-boot/blame/253e4b25b1e049661e450f8366f69c8b6dab9156/spring-boot-project/spring-boot-docs/src/docs/asciidoc/spring-boot-features.adoc#L8066).

**Comment by brneto** [comment]
I just noticed an issue with this approach with my Spring Contract Testing. I'm investigating why first. I share it with you anyway.

I have a base contract base class that implements an abstract class where the `RestAssureWebTestClient` happens.
e.g.

ContractBase:
```java
abstract class ChassisBase extends ContractTest {

    @MockBean
    private Service service;

    @BeforeEach
    void setUp() {
        // init
        webTestClientSetup();

        // given
        var entity =
                new Entity()
                        .setId(1L)
                        .setName("test name")
                        .setDescription("description test");

        given(service.findAllItems())
                .willReturn(Flux.just(entity));
    }
}
```

AbstractContractTest (**working**):
```java
@WebFluxTest
@AutoConfigureRestDocs
abstract class ContractTest {

    @Autowired
    private ApplicationContext context;

    @Autowired
    private WebTestClientRestDocumentationConfigurer configurer;

    void webTestClientSetup() {
        RestAssuredWebTestClient.webTestClient(
                WebTestClient
                        .bindToApplicationContext(context)
                        .configureClient()
                        .filter(configurer)
                        .entityExchangeResultConsumer(document("{class-name}/{method-name}"))
                        .build());
    }
```

AbstractContractTest (**not working**):
```java
@WebFluxTest
@AutoConfigureRestDocs
abstract class ContractTest {

    @TestConfiguration
    static class RestDocsParameterizedOutput {

        @Bean
        WebTestClientBuilderCustomizer restDocsParameterizedOutput() {
            return builder -> builder.entityExchangeResultConsumer(document("{class-name}/{method-name}"));
        }
    }

    @Autowired
    private WebTestClient webClient;

    void webTestClientSetup() {
        RestAssuredWebTestClient.webTestClient(webTestClient);
    }
```
