### ISSUE TITLE
Update Gradle examples to use configurations for dependencies that are Gradle 7-compatible

### ISSUE THREAD

**Issue by brneto** [spring-projects/spring-restdocs#743]
The [Spring REST Docs documentation](https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#getting-started-build-configuration) suggests add `spring-restdocs-mockmvc` dependency in the `testCompile` configuration.

Gradle 7.2 do not use this configuration anymore but instead `testCompileOnly` also with dependency `spring-restdocs-webtestclient` it is working only in the `testImplementation` configuration.

See:
https://gitter.im/spring-projects/spring-restdocs?at=6123547ceb72173430e02917
https://gitter.im/spring-projects/spring-restdocs?at=61235b29aa48d1340c298457

**Comment by brneto** [comment]
@wilkinsona As done before I'm happy to help in this documentation update if you may want.

**Comment by wilkinsona** [comment]
On closer inspection, this was already done as part of https://github.com/spring-projects/spring-restdocs/issues/719.
