### ISSUE TITLE
Support code block titles

### ISSUE THREAD

**Issue by kenblair** [spring-projects/spring-restdocs#77]
Asciidoctor supports titles in code blocks.  Unfortunately this must be included in the snippets themselves unless there's a method I'm unaware of.  It would be nice to have support for specifying a title.  Considering forking and opening a PR but curious as to whether or not this has already been looked at.

**Comment by wilkinsona** [comment]
Nice idea. I'm not aware of anyone having looked at this already. A PR would be great, thank you.

Have you thought about what the API would look like for specifying the title? The snippets that are generated by default (`curl-request`, `http-request`, and `http-response`) will present a bit of a challenge as there's no obvious place to supply the titles.

**Comment by wilkinsona** [comment]
It's just occurred to me that you can already do this thanks to Asciidoctor's ability to include portions of a file. You can include the start of the snippet, set the title, and then include the rest of the snippet:

```
include::{snippets}/error-example/http-response.adoc[lines=1..2]
.A title for the code block
include::{snippets}/error-example/http-response.adoc[lines=2..-1]
```

Admittedly, this is rather clunky but it does address the problem of providing a title for the snippets that are generated by default.

**Comment by kenblair** [comment]
Interesting as a workaround at least.

> Have you thought about what the API would look like for specifying the title?

I haven't had as much time to look at the code as I'd like.  For our purposes I simply added title to the AsciidoctorWriter as an option and then passed it along the entire chain to see if I liked the result.  I do like the result but I don't consider that a good approach. 

Looking through code it occurred to me that there's more than a few aspects (file name, extension, directory name) that I'd love to see configurable which are basically hardcoded currently.  Some refactoring and exposing configuration (I'm not sure how yet) could open up quite a few options.

**Comment by wilkinsona** [comment]
This is now possible using a custom template and a `title` attribute. Here's an example for `curl-request`:

##### Custom curl-request.snippet:
```
[source,bash]
.{{title}}
----
$ curl {{arguments}}
----
```

##### Test code:
```java
mockMvc.perform(get("/")).andDo(
				document("index").withCurlRequest(
						attributes(key("title").value("Access the index using curl"))));
```

Please see the [updated reference documentation](http://docs.spring.io/spring-restdocs/docs/1.0.x-SNAPSHOT/reference/html5/#documenting-your-api-customizing) for further information.
