### ISSUE TITLE
RestDocumentationRequestBuilders' methods for multipart file uploads are not aligned with MockMvc's MockMvcRequestBuilders

### ISSUE THREAD

**Issue by marcgemis** [spring-projects/spring-restdocs#770]
The documentation under https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/#documenting-your-api-request-parts for MockMvc has 
`this.mockMvc.perform(multipart("/upload").file("file", "example".getBytes()))`

I think this should be
`this.mockMvc.perform(fileUpload("/upload").file("file", "example".getBytes()))`

as fileUpload is defined in RestDocumentationRequestBuilders and multipart in MockMvcRequestBuilders

**Comment by wilkinsona** [comment]
Thanks, @marcgemis. Rather than changing the docs, I think that `RestDocumentationRequestBuilders` should be updated so that it offers `multipart` methods. The existing `fileUpload` methods should probably be deprecated as well to keep things closely aligned with `MockMvcRequestBuilders`.

**Comment by marcgemis** [comment]
Please note that in https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/#documenting-your-api-request-parts-payloads-body "fileUpload" is used in the documentation. This will have to be updated when "multipart" became the new standard.
