### ISSUE TITLE
provide support for GraphQl(Tester)

### ISSUE THREAD

**Issue by cforce** [spring-projects/spring-restdocs#779]
Please add doc generation for tests excecuted via GraphQlTester Clients
https://docs.spring.io/spring-graphql/docs/1.0.0-SNAPSHOT/reference/html/#testing

Tx

**Comment by wilkinsona** [comment]
Duplicates #767. @cforce, please feel free to comment on that issue with your thoughts on the questions that I asked @ArtyomGabeev in [this comment](https://github.com/spring-projects/spring-restdocs/issues/767#issuecomment-1007288620).

**Comment by cforce** [comment]
Tx, i did 
https://github.com/spring-projects/spring-restdocs/issues/767#issuecomment-1013680841
