### ISSUE TITLE
Support limitation of JSON response within the code snippets

### ISSUE THREAD

**Issue by vicmosin** [spring-projects/spring-restdocs#78]
The one of the coolest things about restdocs is that we can use MVC Test framework for two purposes:
1. Test the code
2. Make a code snippet for documentation

I personally prefer to have only one version of tests (and to NOT split tests for tests of functionality and tests for documentation). And sometimes there cases where I need to test a collection of 50 items retrieval but I don't need them all in the snippets, just a couple will be enough. So it will be nice if we will have some way to limit the items quantity which will go to code example.

For example:
```
RestDocumentation.document("index")
    .withLimit(10)
    .withResponseFields(
         fieldWithPath("_links").description("<<resources-index-links,Links>> to other resources")
    )
    .withLinks(
         linkWithRel("self").description("This <<resources-index,Index resource>>"),
         linkWithRel("user").description("The <<resources-users,User resource>>"),
   )
)
```

**Comment by wilkinsona** [comment]
Spring REST docs doesn't really understand the format of a response payload so it has no good way of enforcing a limit. Instead, I'd use a custom response post-processor. Something like this:

```java
@Test
public void test() {
	this.mockMvc.perform(get("/").accept(MediaType.APPLICATION_JSON))
			.andExpect(status().isOk())
			.andDo(modifyResponseTo(limitItems()).andDocument("post-processed"));
}

private ResponsePostProcessor limitItems() {
	return new ContentModifyingReponsePostProcessor() {

		@Override
		public String modifyContent(String originalContent) {
			// Manipulate the content as required
			return modifiedContent;
		}
	};
}
```

**Comment by andreimaneasa** [comment]
@wilkinsona What is the equivalent for the class ContentModifyingReponsePostProcessor in the 2.0.x realeses?

**Comment by wilkinsona** [comment]
You can find information about the current API for modifying request and response content in the [reference documentation](https://docs.spring.io/spring-restdocs/docs/2.0.x/reference/html5/#customizing-requests-and-responses-preprocessors-writing-your-own), including `ContentModifyingOperationPreprocessor` which is what `ContentModifyingReponsePostProcessor` became during 1.0's development.

**Comment by andreimaneasa** [comment]
👍 Ok. Thanks
