### ISSUE TITLE
Reference doc link is wrong

### ISSUE THREAD

**Issue by librucha** [spring-projects/spring-restdocs#783]
Hi all.

On the project web [page](https://spring.io/projects/spring-restdocs#learn) is link to current doumentation which is wrong
`https://docs.spring.io/spring-restdocs/docs/current/reference/html/`

Working link is:
`https://docs.spring.io/spring-restdocs/docs/current/reference/`

Libor

**Comment by wilkinsona** [comment]
Thanks. The location on the docs server has been updated to align with previous releases. I'll use this issue to make the same change for 2.0.7 snapshots so the problem doesn't occur again.
