### ISSUE TITLE
withResponseDefaults works but withRequestDefaults does not in kotlin

### ISSUE THREAD

**Issue by JogoShugh** [spring-projects/spring-restdocs#786]
Hello,
I thought the following would work to remove the string " - i  " from the request snippet rendered as curl requests, but I'm thinking now that I would have to somehow post process the snippet instead. Is that possible?

Thanks!

```kotlin
    @BeforeEach
    fun setUp(webApplicationContext : WebApplicationContext,
              restDocumentation : RestDocumentationContextProvider) {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
            .apply<DefaultMockMvcBuilder?>(documentationConfiguration(restDocumentation)
                .uris()
                .withScheme("https")
                .withHost("site.tech")
                .withPort(443)
                .and()
                .operationPreprocessors()
                .withRequestDefaults(prettyPrint(),
                    replacePattern(Pattern.compile(" -i "), "")
                    )
                .and()
                .operationPreprocessors()
                .withResponseDefaults(prettyPrint())
            )
            .build()
    }
```

**Comment by wilkinsona** [comment]
The request and response defaults are applied to the HTTP request and HTTP response. All this happens before any of the snippet generation is performed. It appears that what you are trying to do is to post-process the output of the curl snippet but what you have configured is pre-processing of the HTTP request before it's documented.

It sounds like what you'd like to be able to do is covered by https://github.com/spring-projects/spring-restdocs/issues/552. That issue also shows a workaround with a custom `CurlRequestSnippet` sub-class that removes the `-I`.
