### ISSUE TITLE
Improve diagnostics when no type is provided for an optional field that is not in the payload

### ISSUE THREAD

**Issue by niharay** [spring-projects/spring-restdocs#83]
Marking a response field "optional" still results in error "Payload does not contain field".

**Comment by wilkinsona** [comment]
I would guess it's failing when it tries to resolve the field's type. Did you provide one? Like this, for example:

```
fieldWithPath("a.b").description("Foo").optional().type(FieldType.STRING)
```

If this is the case, the error message could certainly be more helpful.

**Comment by niharay** [comment]
Thanks for replying. I was missing the field's type in response fields after calling the optional method.

Another qq how can I not document/hide headers ?

**Comment by wilkinsona** [comment]
http://docs.spring.io/spring-restdocs/docs/1.0.0.M1/reference/html5/#_removing_headers

**Comment by niharay** [comment]
Thanks for your help.

**Comment by niharay** [comment]
This removes the headers from the response. Is there anyway to remove the headers from the request before documenting it I dont want them to be part of http-request.adoc?

**Comment by wilkinsona** [comment]
No, not at the moment. Please open a separate issue

**Comment by wilkinsona** [comment]
Reopening to remind me to improve the error message
