### ISSUE TITLE
Remove specific headers from the request before documenting it to http-request.adoc

### ISSUE THREAD

**Issue by niharay** [spring-projects/spring-restdocs#84]
At times we need to provide documentation to clients for future application supporting say OAuth which might be disabled in test environment. It will be great if we can replace/customize the headers we want to show in the Documentation. 

Thanks

**Comment by awendland** [comment]
This would also be useful when a JSON payload is in the request and the cURL output includes a "Content-Length: ..." header. Though the Content-Length header should be sent in real client apps, it would be nice to be able to remove it from the cURL output for simplification of the example requests and so that it is easier for someone testing the API to modify the sample requests.

**Comment by gauravbrills** [comment]
Another scenario for the same shall be to hide basic auth details from curl snippets of secured endpoints.
Also have a wish if there would be something by which we can mask certain fields in responses .Though I think this can be taken care by dummy data but just one on my wishlist .

**Comment by wilkinsona** [comment]
> Another scenario for the same shall be to hide basic auth details from curl snippets of secured endpoints.

I think you might be able to avoid this by setting up your test to run as a particular user, so you wouldn't need to provide the credentials with the request. You could use [Spring Security Test's `@WithMockUser`](http://docs.spring.io/spring-security/site/docs/4.0.x/reference/htmlsingle/#test-method-withmockuser), for example.

> Also have a wish if there would be something by which we can mask certain fields in responses

Have you seen `replacePattern` on `ResponsePostProcessors`?

**Comment by gauravbrills** [comment]
ahh thanks @wilkinsona that will work .. 

Also I had another point if you can add more meanigful types to the  FieldTypes enum for say LINKS ,href etc .. will enrich the docs as now they just populate as dumb Objects .

**Comment by wilkinsona** [comment]
> Also I had another point if you can add more meanigful types to the FieldTypes enum for say LINKS ,href etc .. will enrich the docs as now they just populate as dumb Objects .

This is going way off topic for this issue, but `FieldType` is an enumeration of the different types in a JSON payload and, as JSON doesn't know anything about links, hrefs etc, it's not appropriate to include them in the enum

**Comment by gauravbrills** [comment]
@wilkinsona  ya that sounds apt .. Also the replacePattern actually masks the whole json response .What if what I want is to mask only values and not the field keys in the json ?

**Comment by wilkinsona** [comment]
> What if what I want is to mask only values and not the field keys in the json ?

It'll only replace whatever's matched by the regular expression. Are you saying that you can't write a regular expression that will only match the values?

**Comment by gauravbrills** [comment]
The issue is if I apply the pattern on some text then it shall match both values and keys and any other text in the json like links .As I want to mask only values so yes I think I will not be able to write a regex that only matches values . 

so say if my json is 
`
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
`
and I apply some regex it will ideally mask everything 

`{
    "xxxxxxxxxxxxxxxx": {
        "xxxxxxxxxx": "xxxxxxxxxxxxxx xxxxxxxxxxxxxxxx",
		"GxxxxxxxxDxxxx": {
            "xxxxxxxxxx": "S",
			"GxxxxxxxxLxxxxxx": {
                "GxxxxxxxxExxxxxxxx": {
                    "ID": "SGML",
					"SxxxxxxAxx": "SGML",
					"GxxxxxxxxTxxxxxx": "Sxxxxxxxxxxxxxx Gxxxxxxxxxxxxxxxxxxxx Mxxxxxxxxxx Lxxxxxxxxxxxxxx",
					"Axxxxxxxxxxxx": "SGML",
					"Axxxxxxxxxx": "ISO 8879:1986",
					"GxxxxxxxxDxxxx": {
                        "xxxxxxxx": "A xxxxxxxx-xxxxxxxxxxxx xxxxxxxxxxxxxxxx, xxxxxxxx xxxx xxxxxxxxxxxx xxxxxxxxxxxx xxxxxxxxxxxxxxxxxx xxxxxxxx xxxx DxxxxBxxxxxx.",
						"GxxxxxxxxSxxxxAxxxxxx": ["GML", "XML"]
                    },
					"GxxxxxxxxSxxxx": "xxxxxxxxxxxx"
                }
            }
        }
    }
}`

hence it wont be possible to make regex very restrictive only to values. Any suggestions
