### ISSUE TITLE
Documentation links are outdated

### ISSUE THREAD

**Issue by ByronLudwig** [spring-projects/spring-restdocs#865]
Clicking on any of the Sample links results in 404:
![image](https://user-images.githubusercontent.com/14773418/200861328-46d058ce-5810-4ae9-824a-d735d301db95.png)
![image](https://user-images.githubusercontent.com/14773418/200861379-1cfb6b3d-bb95-453d-94f8-88b0a807431d.png)

**Comment by wilkinsona** [comment]
Thanks. The links have been corrected.
