### ISSUE TITLE
http-request.adoc does not use documentationConfiguration()..withHost() value

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#87]
The generated `http-request.adoc` does not include the host set with the documentationConfiguration.

However the generated `curl-request.adoc` *does* use the host set.

**Comment by wilkinsona** [comment]
@marceloverdijk Are you using M1? If so, could you give a snapshot a try? I think https://github.com/spring-projects/spring-restdocs/commit/833a01d6a5de8b5b343de23697df04df0099057a may have already taken care of this

**Comment by marceloverdijk** [comment]
Yes, latest snapshot indeed includes the host like:

    GET /api/customers HTTP/1.1
    Host: myhost.com

However I think I would prefer just:

    GET http://myhost.com/api/customers HTTP/1.1

as it reads nicer I think.

**Comment by wilkinsona** [comment]
Just for the record, the `http-request` snippet is intended to be an actual valid HTTP/1.1 request. While what you've suggested may read more nicely, it wouldn't be a valid HTTP/1.1 request. Such a request must include the `Host` header and it also must not include any scheme, host, port etc information in the request path.

**Comment by mjmeyer** [comment]
for grins, if we need to show the port and are willing to produce a custom http-request.snippet in test/resources, what would be the property name to use with mustache to get the port value that we set in mockmvc.UriConfigurer.withPort()?

**Comment by wilkinsona** [comment]
@mjmeyer The port isn't in the model that's created by `HttpRequestSnippet` so you'll need to use a custom `HttpRequestSnippet` subclass that adds it. Something like this:

```java
public class CustomHttpRequestSnippet extends HttpRequestSnippet {

	@Override
	protected Map<String, Object> createModel(Operation operation) {
		Map<String, Object> model = super.createModel(operation);
		model.put("port", operation.getRequest().getUri().getPort());
		return model;
	}

}
```

You can then use `{{port}}` in your Mustache template.
