### ISSUE TITLE
Spring REST Docs documentation doesn't match Spring Initializr output for maven project

### ISSUE THREAD

**Issue by dashaun** [spring-projects/spring-restdocs#878]
Starting with start.spring.io to build a new project, I'm getting

```
<plugin>
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctor-maven-plugin</artifactId>
<version>1.5.8</version>
...
<plugin>
```

Following the documentation, I tried to use the operation macro `operation::`

It didn't work at all.
The `include::` macro works as expected.

In the docs:

https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/#getting-started-build-configuration

We can see:

```
<plugin> 
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctor-maven-plugin</artifactId>
<version>2.2.1</version>
...
</plugin>
```

I expected the `operation::` macro to work.  I was using it by default in the past.

Should the initializr be updated?
Should the docs be updated?

What is the expected approach for a user to use the `operation::` macro?

Given the initializr generated pom.xml, I simply switched the 1.5.8 version to 2.2.1 and things work as expected.

So, at this point, my assumption, is that the initializr needs to provided version 2.2.1 of the plugin, with the pom.xml.

**Comment by wilkinsona** [comment]
> So, at this point, my assumption, is that the initializr needs to provided version 2.2.1 of the plugin, with the pom.xml.

That's right, I think. It's a Maven problem that's somewhat similar to https://github.com/spring-io/start.spring.io/issues/676. Please open a [start.spring.io issue](https://github.com/spring-io/start.spring.io/issues).
