### ISSUE TITLE
Document how to enable pretty printing of the response for every test

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#88]
To enable pretty printing I now have:

        mockMvc.perform(get(VAT_RATES_LIST_PATH))
                .andExpect(status().isOk())
                .andDo(modifyResponseTo(prettyPrintContent())
                        .andDocument("my-example"));

To avoid to put this `prettyPrintContent` everywhere it would be nice to something like:

        mockMvc = MockMvcBuilders
                .webAppContextSetup(webApplicationContext)
                .alwaysDo(modifyResponseTo(prettyPrintContent()))

(note I tried this but it does not work)

**Comment by wilkinsona** [comment]
What you tried doesn't work as the `ResponseModifier` that's returned from `modifyResponseTo` is lost. You're never calling `andDocument` on it, so no documentation of the modified response is performed.

As things stand, this will work:

```java
@Before
public void createMockMvc() {
	this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
			.apply(new RestDocumentationConfigurer()).build();
	this.prettyPrint = modifyResponseTo(prettyPrintContent());
}

@Test
public void testOne() throws Exception {
	this.mockMvc.perform(get("/")).andDo(
			this.prettyPrint.andDocument("first-example"));
}

@Test
public void testTwo() throws Exception {
	this.mockMvc.perform(get("/")).andDo(
			this.prettyPrint.andDocument("second-example"));
}
```

You can take things a step further by using a parameterised output directory:

```java
@Before
public void createMockMvc() {
	this.mockMvc = MockMvcBuilders
			.webAppContextSetup(this.context)
			.apply(new RestDocumentationConfigurer())
			.alwaysDo(
					modifyResponseTo(prettyPrintContent()).andDocument(
							"{method-name}")).build();
}

@Test
public void testOne() throws Exception {
	this.mockMvc.perform(get("/"));
}

@Test
public void testTwo() throws Exception {
	this.mockMvc.perform(get("/"));
}
```

If, in some of the tests, you want to do some more documentation, you can save a reference to the `RestDocumentationResultHandler` created in `@Before` and then using it in the tests:

```java
@Before
public void createMockMvc() {
	this.document = modifyResponseTo(prettyPrintContent()).andDocument(
			"{method-name}");
	this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
			.apply(new RestDocumentationConfigurer())
			.alwaysDo(this.documentationHandler).build();
}

@Test
public void testOne() throws Exception {
	this.mockMvc.perform(get("/")).andDo(
			this.document.withLinks(linkWithRel("rel").description("bar")));
}

@Test
public void testTwo() throws Exception {
	this.mockMvc.perform(get("/"));
}
```

There's very little (no?) mention of this in the documentation so we can use this issue to address that.

**Comment by jochenchrist** [comment]
+1
Would be nice to see.
