### ISSUE TITLE
Provide a preprocessor to hide arbitrary fields from http requests/responses generated snippets

### ISSUE THREAD

**Issue by AugustoRavazoli** [spring-projects/spring-restdocs#885]
Hello.

When building the `mockMvc` instance, it would be cool if exists a built-in preprocessor to hide arbitrary fields, like `id`. Something like this:
```java
private MockMvc mockMvc;

@Before
public void setup() {
    this.mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
        .apply(documentationConfiguration(this.restDocumentation).operationPreprocessors()
	    .withRequestDefaults(preprocessRequest(ignoreFields("id"))) 
	    .withResponseDefaults(prettyPrint())) 
	    .build();
}
```
So if in the test class we have a resource with an `id` field, the generated snippet will not have it. If is there a easy way to do this, sorry, I can't find a simple solution.

**Comment by wilkinsona** [comment]
Do you want to hide the `id` field completely so that it will never appear in the documentation, not even in things like HTTP request and response snippets, request and response body snippets, and so on?

**Comment by AugustoRavazoli** [comment]
Yes, that's it.
