### ISSUE TITLE
Add ability to post-process operations

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-restdocs#899]
Currently you can configure pre-processors for all operations, which allow changing the headers and body of the request and response. However, this happens before the body is parsed and used to process the field documentation. That means any changes must preserve a valid structure.

Without the ability to post-process, it does not appear possible to e.g. truncate a response body for the generated snippets.

**Comment by OrangeDog** [comment]
The current workaround for asciidoc is to manually construct that section:
```asciidoc
[#_index_http_response]
==== HTTP Response
[source,http,options="nowrap"]
----
include::{snippets}/index/http-response.adoc[lines=3..35]
...
----
```

**Comment by OrangeDog** [comment]
@wilkinsona that looks like a very specific solution where you have to know the keys and how to filter them in advance (also not sure why it casts the `Map` to an `Object` and then does a load of checks as to whether it's a `Map`).

In the specific case, I was looking for something more general like "limit all responses to N lines or M bytes", and in the general case the ability to do anything without worrying about later parsing.

**Comment by wilkinsona** [comment]
Never say never, but I'm not keen on introducing a new abstraction just for this at the moment. In the meantime, if you don't want to do the truncation in a pre-processor, you could do it as part of the snippets being written using a custom `WriterResolver`. Here's a sketch of what that might look like:

```java
static class TruncatingWriterResolver implements WriterResolver {
	private final WriterResolver delegate = new StandardWriterResolver(
			new RestDocumentationContextPlaceholderResolverFactory(), "UTF-8", TemplateFormats.asciidoctor());
	@Override
	public Writer resolve(String operationName, String snippetName,
			RestDocumentationContext restDocumentationContext) throws IOException {
		return new TruncatingWriter(this.delegate.resolve(operationName, snippetName, restDocumentationContext));
	}
}
static class TruncatingWriter extends Writer {
	private final Writer delegate;
	private int remaining = 100;
	TruncatingWriter(Writer delegate) {
		this.delegate = delegate;
	}
	@Override
	public void write(char[] cbuf, int off, int len) throws IOException {
		if (this.remaining <= 0) {
			return;
		}
		len = Math.min(len, this.remaining);
		this.delegate.write(cbuf, off, len);
		this.remaining -= len;
	}
	@Override
	public void flush() throws IOException {
		this.delegate.flush();
	}
	@Override
	public void close() throws IOException {
		this.delegate.close();
	}
}
```

You may want to truncate differently, or not at all in some cases, based on the `snippetName`. You can plug in the custom resolver like this:

```java
MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
	.apply(new MockMvcRestDocumentationConfigurer(this.restDocumentation)
		.writerResolver(new TruncatingWriterResolver()))
	.build();
```

**Comment by OrangeDog** [comment]
Aha, that should do it.

**Comment by OrangeDog** [comment]
Actually it doesn't, because it's writing the whole snippet not just the HTTP body.
Therefore it also truncates e.g. the `----` from the end of the code block.

To do it in the writer you'd need specific code to reproduce the end of each template.

**Comment by wilkinsona** [comment]
> To do it in the writer you'd need specific code to reproduce the end of each template.

Correct. What I shared was only a sketch to illustrate the technique. As I said above, you may need to modify how the truncation is performed based on the snippet that's being written.

Another option is to use a [Mustache lambda](https://github.com/samskivert/jmustache?tab=readme-ov-file#lambdas) that can perform truncation and custom snippet templates that determine what's truncated.

The lambda can be set up something like this:

```java
Map<String, Object> templateContext = new HashMap<>();
templateContext.put("truncated", new Mustache.Lambda() {

	@Override
	public void execute(Fragment fragment, Writer writer) throws IOException {
		String content = fragment.execute();
		if (content.length() > 30) {
			content = content.substring(0, 30) + "…";
		}
		writer.append(content);
	}

});
MustacheTemplateEngine templateEngine = new MustacheTemplateEngine(
		new StandardTemplateResourceResolver(TemplateFormats.asciidoctor()), StandardCharsets.UTF_8,
		Mustache.compiler().escapeHTML(false), templateContext);
MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(this.context)
	.apply(documentationConfiguration(this.restDocumentation).templateEngine(templateEngine))
	.build();
```

To use it you'd provide one or more [custom snippet templates](https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/#documenting-your-api-customizing-snippets). For example, you might have an `org/springframework/restdocs/templates/http-response.snippet` file with the following contents:

```
[source,http,options="nowrap"]
----
HTTP/1.1 {{statusCode}} {{statusReason}}
{{#headers}}
{{name}}: {{value}}
{{/headers}}
{{#truncated}}{{responseBody}}{{/truncated}}
----
```

Note the use of `{{#truncated}}{{responseBody}}{{/truncated}}` to limit the size of the response body. With the lambda above, this template would produce output similar to the following:

```
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
a: alpha
Content-Type: application/json;charset=UTF-8
Content-Length: 51

{"a":"alpha","links":[{"rel":…
----
```
