### ISSUE TITLE
Any concern that the underlying asciidoc gradle plugin doesn't work with Java 17 or 21?

### ISSUE THREAD

**Issue by virtualdogbert** [spring-projects/spring-restdocs#913]
Is there any concern or workaround to the asciidoc gradle plugin, that generates the documentation from the .adoc, which doesn't work with Java 17 or 21, and hasn't been touched in several months?

https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/684

**Comment by wilkinsona** [comment]
None that we're aware of. This project's own build uses Java 17 and the Asciidoctor Gradle plugin without any problems.
