### ISSUE TITLE
Using JWT Token to Access Resource Server

### ISSUE THREAD

**Issue by sdack-cloud** [spring-projects/spring-restdocs#919]
### resource server

        JwtAuthenticationToken authentication = (JwtAuthenticationToken) SecurityContextHolder.getContext().getAuthentication();

I passed TOKEN during the request

There is a token value in HttpServletRequest, But JwtAuthenticationToken  is null

```
    @BeforeEach
    void setUp(WebApplicationContext webApplicationContext, RestDocumentationContextProvider restDocumentation) {
        this.mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
                .apply(documentationConfiguration(restDocumentation))
                .alwaysDo(print())
                .build();
    }
```

```
        this.mockMvc.perform(post("/user")
                .accept(MediaType.APPLICATION_JSON)
                .contentType(MediaType.APPLICATION_JSON)
                .header(HttpHeaders.AUTHORIZATION,token)
                .content("{}")
        )
                .andExpect(status().isOk())
```

**Comment by sdack-cloud** [comment]
org.springframework.restdocs:spring-restdocs-mockmvc:3.0.1

**Comment by wilkinsona** [comment]
This doesn't really have anything to do with Spring REST Docs as you'd see the same behavior with MockMvc alone. You need to configure `MockMvc` to interact with Spring Security as [described in the Spring Security documentation](https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/setup.html).
