### ISSUE TITLE
modifyResponseTo(prettyPrintContent()) Not printing JSON pretty.

### ISSUE THREAD

**Issue by niharay** [spring-projects/spring-restdocs#92]
Here is how I am using pretty printing. Please let me know if I missed something.
.andDo(modifyResponseTo(prettyPrintContent())
                        .andDocument("application-claim-credentials-example")

**Comment by wilkinsona** [comment]
That looks right to me. There are tests that cover this so, without more information, I can't diagnose the problem. Can you please share a sample project that shows pretty printing not working?

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment if you're still having trouble and we can re-open the issue.
