### ISSUE TITLE
JavaDoc support

### ISSUE THREAD

**Issue by heyarny** [spring-projects/spring-restdocs#927]
I know there is an issue (https://github.com/spring-projects/spring-restdocs/issues/600) which was declined, but still want to bring this to the front to open a discussion why this shouldn't be supported?

I have been using REST docs for quiet a long time and we have coding guidelines which enforce the user to write JavaDocs.
With additional REST docs we have a lot of redundancies and lack of efficient working.

And for anyone suggesting https://github.com/ScaCap/spring-auto-restdocs: it is end of life. Reason: switched to [springdoc](https://springdoc.org/).

Thanks

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-restdocs/issues/600#issuecomment-2076597197.
