### ISSUE TITLE
Issue with the Junit Rest Documentation with the spring docs 2.0.5.Release and spring boot version 2.7.6 version in controller testcases

### ISSUE THREAD

**Issue by DarthVader3011** [spring-projects/spring-restdocs#929]
```
@SpringBoooTest(WebEnvironment=SpringBootTest.WebEnvironment.Random.Port)
@AutoConfigureMockMvc
class testSpec extends Specification{

    @Autowired 
    private WebAPplicationContext context;

    @Rule 
    JunitRestDocumentation junit = new JunitRestDocumentation()

    @AutoWired
    private MockMvc mockMvc

    void setup{
        this.mockMvc = MockMvcBuilder.webAppContextsetup(this.context)
            .apply(documentationConfiguration(junitRestDocumenation).operationPreprocessors()
            .withRequestDefault("").withResponseDefaule("").build()
    }

    //some test cases
    def "" () {

    }

}
```

When I execute the  above test case  which in Spock groovy, the Junit REST documentation object is unable to initialize the context, leading to a null pointer exception.The junitRestDocumenation object contains a ManualRestDocumentaion which has outputDir and context ..so i am getting context as null ...

The Asciidoctorj version i am using is 2.4.0

**Comment by wilkinsona** [comment]
I suspect Spock isn't calling the rule. Does https://spockframework.org/spock/docs/2.3/migration_guide.html#_junit_4_support help?

**Comment by DarthVader3011** [comment]
thanks, adding spock-junit4 in gradle it worked. Thanks Wilkinsona cheers
