### ISSUE TITLE
Documenting path parameters does not work with MockMvcTester's fluent API

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#939]
It works if you use `MockMvcTester.perform(RequestBuilder)` and `RestDocumentationRequestBuilders` but this loses much of the benefit of `MockMvcTester` as you then can't use its fluent API to build the request.

https://github.com/spring-projects/spring-framework/issues/33509 will make the URI template, if any, available from `MockHttpServletRequest`. REST Docs should use it with Framework 6.2. This will allow the fluent `MockMvcTester` API to be used to build the request and also remove the need for `RestDocumentationRequestBuilders` when using Framework 6.2.

**Comment by eiswind** [comment]
@wilkinsona is there an artifact available that I can use to crosscheck my tests? It doesn't seem to come with 3.0.1.

**Comment by wilkinsona** [comment]
That's to be expected as 3.0.1 was released in November 2023. Please try with 3.0.2-SNAPSHOT that's available from https://repo.spring.io/snapshot.

**Comment by eiswind** [comment]
Thx. Works like a charm.
