### ISSUE TITLE
Add support for `org.springframework.web.client.RestClient`

### ISSUE THREAD

**Issue by donalmurtagh** [spring-projects/spring-restdocs#946]
The latest HTTP client for testing a Spring application is [org.springframework.web.client.RestClient](https://spring.io/blog/2023/07/13/new-in-spring-6-1-restclient), but according to the docs it is not currently supported by spring-restdocs.

For most users, RestClient is a better choice than WebClient/WebTestClient as the latter imposes a reactive API and a dependency on Spring WebFlux.

**Comment by wilkinsona** [comment]
Thanks for the suggestion but this would [require a test-focussed variant of `RestClient`](https://github.com/spring-projects/spring-restdocs/issues/478#issuecomment-1810694961 ) (like `WebTestClient` is to `WebClient`). That's being tracked by https://github.com/spring-projects/spring-framework/issues/31275. Until that's implemented, there's nothing that can be done here so I'm going to close this issue as it's not actionable at the moment and may never be actionable.
