### ISSUE TITLE
AbstractMethodError when using Asciidoctor extension with AsciidoctorJ 3.0.0

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-restdocs#949]
https://github.com/asciidoctor/asciidoctorj/releases/tag/v3.0.0

First issue I encountered was:

> `java.lang.AbstractMethodError`: Receiver class `org.springframework.restdocs.asciidoctor.DefaultAttributesPreprocessor` does not define or inherit an implementation of the resolved method '`abstract org.asciidoctor.extension.Reader process(org.asciidoctor.ast.Document, org.asciidoctor.extension.PreprocessorReader)`' of abstract class `org.asciidoctor.extension.Preprocessor`.

**Comment by bpfoster** [comment]
I see this error during build if attempting to upgrade org.asciidoctor:asciidoctor-maven-plugin to v3.1.0

**Comment by wilkinsona** [comment]
This is hopefully fixed in the latest 3.0.3-SNAPSHOT available from https://repo.spring.io/snapshot. Please give it a try if you have a minute.

**Comment by bpfoster** [comment]
Can't speak to OP's use case, but for mine, can confirm using asciidoctor-maven-plugin 3.1.0 and spring-restdocs-asciidoctor 3.0.3-SNAPSHOT together works great, thanks @wilkinsona!
