### ISSUE TITLE
Restdocs generation does not obey @ActiveProfiles set on test class

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#95]
Could it be that restdocs does not obey to `@ActiveProfiles` set?

    @RunWith(SpringJUnit4ClassRunner.class)
    @SpringApplicationConfiguration(classes = Application.class)
    @ActiveProfiles("docs")
    @Transactional
    @WebAppConfiguration
    public abstract class AbstractMockMvcDocumentation {

I've set specific active profile for my documentation tests.
However this does not seem to get picked up.
Instead the default profile is used for this tests.

In my integration test, which have the same setup this `@ActiveProfile` does work as expected.

**Comment by wilkinsona** [comment]
Spring REST Docs isn't involved in deciding which profiles should be active so the problem must lie elsewhere. Perhaps you could post on Stackoverflow with an example that reproduces the problem?

**Comment by marceloverdijk** [comment]
Sorry was indeed a problem on my side.
