### ISSUE TITLE
How to document JSON array field

### ISSUE THREAD

**Issue by rozhok** [spring-projects/spring-restdocs#96]
Hello guys, I'm wondering how to document following response:
```
[ "Red", "Green", "Blue" ]
```
I want to document unnamed array and failing with following constructions:
```
.withResponseFields(
        fieldWithPath("*").description("List colors")));
```
or
```
.withResponseFields(
        fieldWithPath("$[]").description("List colors")));
```

Thanks in advance.

**Comment by wilkinsona** [comment]
You should use `[]` as the path. I've added in test in b1a6840 to verify that it works.

**Comment by rozhok** [comment]
Thanks for blazing fast reply!
I'm also wondering is it possible to document an empty array in response...

**Comment by wilkinsona** [comment]
If the array is empty you'll have to mark the field as optional and explicitly provide a type for its contents. For example:

```java
.withResponseFields(
        fieldWithPath("[]").description("List of colors").optional().type(FieldType.STRING));
```

**Comment by rozhok** [comment]
Many thanks! :+1: 
Can't wait until path variables will be supported.
