### ISSUE TITLE
Ability to document query parameter type (like e.g. Number)

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#97]
Although Query parameters are standard strings, api services quite often expect explicit types like e.g. a integer.

It would be nice to be able to document the type of the query parameter like:

    parameterWithName("page").type("Number")....

Currently there is no support of documenting the type.

**Comment by marceloverdijk** [comment]
I've quickly looked at source code and if you are interested I can make a PR to add a new `ParameterType` type to `ParameterDescriptor`. Similar as `FieldDescriptor` has a `FieldType`.
And of course adding to to the `QueryParametersSnippetResultHandler`. If not provided the default type in the snippet should be `String`.

**Comment by wilkinsona** [comment]
I don't think it makes sense for this to be handled in the same way as field types. Field types have a known set of possibilities (as defined by the JSON specification). Query parameters can be anything that you can represent as a string. In other words, the type would have to be free-form, at which point it might as well be part of the description. Using a separate column to describe the type is another variant of #70.

**Comment by marceloverdijk** [comment]
Yes, when raising this issue I wasn't aware of #70. That should be sufficient.
