### ISSUE TITLE
No indication generated for .optional() marked fields

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-restdocs#99]
Documenting a field as optional does not result in any indication in the generated documentation.

    fieldWithPath("description").optional().description("The description of the product."),

Besides the Path, Type and Description columns, maybe simply add an Optional column to the generated table.

**Comment by wilkinsona** [comment]
That's intentional. `optional` just tells Spring REST docs whether or not to fail if the field's not present in the request or the response. 

Including an `optional` column in the request or response field's snippet is covered by #70 (which I'm working on at the moment).

**Comment by marceloverdijk** [comment]
Ok great to hear you are working on 70. Looking forward to this!

**Comment by marceloverdijk** [comment]
@wilkinsona I noticed the `optional` field of the `FieldDescriptior` is added to the model for template rendering.
Wouldn't you think it would be consistent to add an `optional` field to `ParameterDescriptor` as well and do:

    parameterWithName("page")
        .description(pageDescription)
        .optional()

I would recommend this instead of 

    parameterWithName("page")
        .description(pageDescription)
        .attributes(
            key("optional").value(true))

This would be much more consistent when writing the `Java asciidoctor documentation`.

**Comment by wilkinsona** [comment]
The key difference is that a field being optional or not means something to Spring REST Docs. There's no concept, as far as Spring REST Docs is concerned, of path parameters being optional. If/when path parameters can be optional then it would certainly make sense for that information to be added to the model automatically.
